### ISSUE TITLE
AppImage cannot render main content for Ubuntu 22.04

### ISSUE THREAD

**Issue by buffalus** [xiaoyifang/goldendict#107]
Hi,

Can the AppImage render content in the tab?
My OS is Ubuntu 22.04.

Thanks

**Comment by xiaoyifang** [comment]
recommend to build from source for Ubuntu22

**Comment by buffalus** [comment]
Hi, could you please provide another AppImage version for Ubuntu 22.04?  Sorry I don't have the knowledge to build. 
Thank you very much!

**Comment by xiaoyifang** [comment]
appimage builder does not support lastest Ubuntu version.
