### ISSUE TITLE
BUG: Scan flag disappeared in the latest alpha

### ISSUE THREAD

**Issue by GPLv3-fan** [xiaoyifang/goldendict#110]
The Scan pop-up has an option to show a GoldenDict flag after selecting a word in any software.

That Scan Flag is very useful and IS NOT AVAILABLE in the latest alpha. Disappeared !

**Comment by xiaoyifang** [comment]
seems to be affected by my new add option in the trayicon.
try to enable "clipboard tracking" through the trayicon and have a check.

**Comment by GPLv3-fan** [comment]
Dear Xiao,

Yesterday I had enabled the scan flag option but not the new "Tracking Clipboard". Unfortunately, the scan flag was missing.

After your latest commit 1 hour ago, the "scan flag" option works correctly again.

 Thank you very much :D
