### ISSUE TITLE
Failure to index some .dsl files

### ISSUE THREAD

**Issue by GPLv3-fan** [xiaoyifang/goldendict#111]
There seems to be a regression that causes a failure to index some .dsl dictionaries. I suspect that is related to changes introduced in the last few months. Certainly, the problem was not present on January when I first indexed all my dictionaries.

**Steps to reproduce with the latest alpha:**

_1) Load a new .dsl dictionary. For example:_
https://send.vis.ee/download/a374906c87c81341/#GHA8mq0i2455dTV0buRu4Q

_2) The index process never finishes. It seems to cause a loop and eventually the software crashes._

My OS is Manjaro KDE x11 (Stable version) with GoldenDict webengine from Arch User Repository. The failure is not only with the above .dsl file but also with others. I had to deactivate the "full text search" function to avoid crashes on GD.

**Comment by xiaoyifang** [comment]
Can not be reproduced on Windows, will check on Linux later
![image](https://user-images.githubusercontent.com/105986/176072846-4d2d2e60-e9d2-4548-bc3d-1b6d76491a0c.png)

**Comment by xiaoyifang** [comment]
try again.

**Comment by GPLv3-fan** [comment]
Thank you very much Xiao !

 I indexed again > 100 .dsl dictionaries without any problems.
