### ISSUE TITLE
Ctrl/Shift click to open new tab works not every time, but every other time

### ISSUE THREAD

**Issue by 429IhD0** [xiaoyifang/goldendict#113]
On Wikipedia, shift or ctrl clicking a link to open the link in new tab doesn't work every time.

It works every *other* time, i.e. the 1st, 3rd, 5th ... times, but not the 2nd, 4th, 6th, ... times.

Any idea why this might be the case?

Thanks!

**Comment by xiaoyifang** [comment]
plz,give a more specific steps to reproduce the issue

**Comment by xiaoyifang** [comment]
need more information .
reopen in the future when get more information.
