### ISSUE TITLE
[Feature Request] Add option to auto-collapse dictionaries

### ISSUE THREAD

**Issue by ghost** [xiaoyifang/goldendict#115]
**Problem Description:** Some dictionaries are needed only occasionally, and most of the time the user wants to skip it. Currently, GoldenDict auto-expands all dictionaries and users needs to scroll down and see ALL the dictionaries in a group.  It is a waste of time to scroll down skipping a dictionary when it is used only ocassionally. 

**Solution:** An option to make GD usage more efficient is to add an ability to **auto-collapse** dictionaries. 

"[DictTango](https://forum.freemdict.com/t/topic/2354/1032)" for Android has that ability: auto-expand and auto-collapse. If a user wants to auto-collapse a dictionary, it would keep the desired position, but it would only appear after clicking over the Dictionary Title.

_Here is a concrete example:_
It is possible to add "Google Translate" to GoldenDict thanks to @xinebf :
https://github.com/xinebf/google-translate-for-goldendict

![grafik](https://user-images.githubusercontent.com/58692066/176952987-eae91ba2-9046-4384-bace-f32a4f2862b0.png)

Around 80% of time I would like to consult traditional .mdx dictionaries on GoldenDict and only 20% I would like to see the translation provided by Google. It would be very beneficial to be able to add “Google Translate” at the Top of a group (first position) and auto-collapse so that only when really necessary it would appear:

![grafik](https://user-images.githubusercontent.com/58692066/176953466-4fc3b65a-c18d-4464-8b45-97bb4fe3f3d5.png)

**Comment by xiaoyifang** [comment]
gd has an option to auto-collapse article(dictionary) when article size reach the limit.

**Comment by GPLv3-fan** [comment]
Yes, auto-collapsing by article size is useful with really large dictionaries (e.g. encyclopedias) but it is impossible to use that feature to collapse a specific dictionary always. 

Using a size limit for collapsing is not so convenient in some cases where dictionaries are small in size. Putting a low limit for collapsing would collapse everything.

I guess that it should be doable to auto-collapse arbitrarily and to keep that info on the "Configuration Folder". If it is not so easy, we can just close this issue.

**Comment by xiaoyifang** [comment]
Plan:
1. add an option "[ ] keep dictionary collapsed during session "
2. when enabled , the collapsed dictionary will continue to collapsed during the next search
