### ISSUE TITLE
[Bug] I need to hold Command + C  for 1.sec to copy a word after I open goldendic

### ISSUE THREAD

**Issue by crokobit** [xiaoyifang/goldendict#124]
I need to hold Command + C  for 1.sec to copy a word after I open goldendic on Mac.

Version:
[6.3.1-GoldenDict_macos-11_331cb296.dmg](https://github.com/xiaoyifang/goldendict/releases/download/v22.7.23-GreatHeat.220723.331cb296/6.3.1-GoldenDict_macos-11_331cb296.dmg)

MacOS 12.2.1
MacBook Pro (14-inch, 2021)

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/183321835-94bc290d-f998-448f-bde9-8688ee6e761e.png)

disable this option and check again .

Was it affected by the above option?
