### ISSUE TITLE
缩放不是100%时的过渡问题

### ISSUE THREAD

**Issue by YLXDXX** [xiaoyifang/goldendict#125]
平台：Debian 11
Q版本：5.15.2
GD版本：最新

1. 当页面缩放不是100%时，即用Crtr++放大或缩小页面，查寻单词时，会有一个从100%页面到实际页面的过程，时间零点几秒，好像是个过渡动画？不知是特性还是问题？
2. 另外在页面内选词，双击查寻时，先是跳到新页面的最上面，再是页面回滚至选词时所在词典的位置，时间零点几秒，比第一个稍长。

上面两个问题，在原版的GD中不存在，望修复

**Comment by xiaoyifang** [comment]
第1个，qt5.15.2的bug，用基于qt6.3.1的版本
第2个，跳转到上次的词典是页面加载完后进行的，一半会有延迟。可以考虑把这个跳转的选项关掉

**Comment by YLXDXX** [comment]
Debian现在还是6.2.4，等它更到6.2.5的时候再来试一下。

“跳转到上次的词典是页面加载完后进行的，一般会有延迟” ，仔细看了一下，官方也是有的，只不过延迟非常小。

这个“跳转的选项”是个很好的特性，在词典内遇到不懂的单词，直接双击就行，方便快捷，跳转选项关掉太可惜了
