### ISSUE TITLE
[Bug] Websites cannot be used within GoldenDict (regression)

### ISSUE THREAD

**Issue by Immunize2** [xiaoyifang/goldendict#129]
After some commits this month, several websites cannot be displayed correctly. In July the same websites were working perfectly.

Websites:
https://corpora.uni-leipzig.de/de/res?corpusId=deu_news_2021&word=%GDWORD%
https://skell.sketchengine.eu/#result?lang=de&query=%GDWORD%&f=concordance

![grafik](https://user-images.githubusercontent.com/111645935/185749574-087dc7fd-c202-4b9a-95b9-aa59dab0790e.png)

**Comment by darnn** [comment]
Do you happen to know what the last build was where websites were working? I tried them several months apart, and the previous time websites weren't working either.

**Comment by Immunize2** [comment]
@darnn I am not sure. I updated GD  the first week of August and the problem happened. 

Versiones before August were okay. I was updating weekly (AUR version)

**Comment by darnn** [comment]
I tried 6.3.1-GoldenDict-Windows.331cb296-041324, and when "as link" was checked, websites weren't displayed properly (see here: https://github.com/goldendict/goldendict/issues/1374#issuecomment-848997466), and when it was unchecked, they weren't displayed at all. Which is different from the current error, but also not great.
For the record, this doesn't happen in the controversial fork of GD created by a Chinese developer that you might have seen mentioned here, which is what I actually use day to day, precisely because it actually displays websites properly, without disrupting the other dictionaries.

**Comment by Immunize2** [comment]
@nonwill is just a dirty and disgusting person ! The illegal fork GD++ tracks users and shows Communist propaganda... 

Dirty @nonwill was banned from PDAWiki and FreeMDict forum.... hahahaha

**Comment by darnn** [comment]
Setting all that aside, the fact of the matter is, it displays websites properly and current GD builds do not. I'm not arguing for its ideological superiority, merely pointing out that this problem has been resolved there months ago.

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/185775480-4bec6fce-c52b-449e-b4bd-8b30ad0e3bad.png)

as to https://skell.sketchengine.eu/#result?lang=de&query=%GDWORD%&f=concordance
seems currently does not  support such links with hashtag in them

**Comment by xiaoyifang** [comment]
ab13be73fd989ce9deec6a6b838257422f1767c9

**Comment by darnn** [comment]
If you're looking at specific websites, could you check these?
https://www.morfix.co.il/%GDWORD%
https://wellisch.co.il/%D7%97%D7%99%D7%A4%D7%95%D7%A9/%GDWORD%

**Comment by darnn** [comment]
Also, Skell does have an api you can query, but making the results plaintext is beyond my capabilities:
https://skell.sketchengine.eu/api/run.cgi/concordance?query=smart&lang=English&format=json

**Comment by xiaoyifang** [comment]
About the website dictionaries ,only offer basic support for them.

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/commit/c171d5b8bb803057db1cc1de86351e10b6b29e2e#commitcomment-83986614

**Comment by xiaoyifang** [comment]
https://github.com/goldendict/goldendict/issues/1553#issuecomment-1248445055
