### ISSUE TITLE
关于自动跳转问题

### ISSUE THREAD

**Issue by ausonD** [xiaoyifang/goldendict#131]
你好！

http://dict.youdao.com/w/eng/%GDWORD%
https://www.bing.com/dict/search?q=%GDWORD%
https://zh.hinative.com/search/questions?utm_medium=referral&utm_source=hinative&utm_content=global_header_questions_index&language_id=22&q=%GDWORD%&button=
https://www.thesaurus.com/browse/%GDWORD%
![图片](https://user-images.githubusercontent.com/107112623/186558249-e1fc8fb2-06db-4b86-aa54-aafca8668f19.png)

目前我使用的是8.23的版本，增加了几本网页词典放在mdx字典的后面，但现在不管查什么词，都会在查词后几秒钟（5-10s）跳转至某一个网络词典的页面（图中即为查询supervisors后过了几秒自动跳转的页面）

每次基本都需要手动拉回mdx词典查询释义，如果关闭网络词典，这又为翻译造成了很大不便。

不知是我配置有什么问题亦或是有其他相关问题？

谢谢抽空查看我的report。

**Comment by xiaoyifang** [comment]
每次应该都是跳到有道吧。
这个是有道词典的网页的操作。
后续看下能否限制

**Comment by ausonD** [comment]
> 每次应该都是跳到有道吧。 这个是有道词典的网页的操作。 后续看下能否限制

应该不止 很多都是 关闭有道后，必应     Hi native      Do native speak      word reference  等等网站皆为如此，似乎不同的词典排序会跳转到不同的网页

**Comment by xiaoyifang** [comment]
网站控制的，如果禁用掉script就不会跳了，但是内部的各种点击事件（展开，折叠）之类的功能也没法用了。

暂时没好办法。

**Comment by ausonD** [comment]
能否考虑暂时设置一个像导航栏、字典栏一样可拖动的小图标，可以快捷打开/关闭script，这样也可以按需打开关闭，毕竟很多网站还是不需要script的。

另外能问问大大有什么好的翻译方案吗？我是从欧路跳过来的，大大的软件确实非常丝滑流畅，很是喜欢，但可能也算美中不足的一点就是没有翻译引擎，加上GD的资源有限，找了很多地方也没有得到一个较为靠谱的翻译方式，目前只能使用quicker进行一些弥补。

![20220826，07 53 41](https://user-images.githubusercontent.com/107112623/186788713-fdb91179-d7da-46ef-b781-32f349afb3f7.jpg)
个

**Comment by xiaoyifang** [comment]
fixed in 5c9b6b0171a503a01634c2cf3320605ddf955aec

**Comment by Ethkuil** [comment]
> 能否考虑暂时设置一个像导航栏、字典栏一样可拖动的小图标，可以快捷打开/关闭script，这样也可以按需打开关闭，毕竟很多网站还是不需要script的。
> 
> 另外能问问大大有什么好的翻译方案吗？我是从欧路跳过来的，大大的软件确实非常丝滑流畅，很是喜欢，但可能也算美中不足的一点就是没有翻译引擎，加上GD的资源有限，找了很多地方也没有得到一个较为靠谱的翻译方式，目前只能使用quicker进行一些弥补。
> 
> ![20220826，07 53 41](https://user-images.githubusercontent.com/107112623/186788713-fdb91179-d7da-46ef-b781-32f349afb3f7.jpg) 个

[调用Google翻译的Python库](https://github.com/xinebf/google-translate-for-goldendict).
