### ISSUE TITLE
[Feature] Add option to change the search column background

### ISSUE THREAD

**Issue by Immunize2** [xiaoyifang/goldendict#132]
A recent update changes the background color of the "search" column.

The new color makes it very difficult to read text within the "search" area:

![grafik](https://user-images.githubusercontent.com/111645935/188292509-99cc2313-2db7-4f24-b5ae-048bbdad631e.png)

**Would it be possible to allow users to decide the background color of the search area ?**

I really need to read the content in the search box and the current background makes it very hard.  Is there a chance to add some customization feature ?

**Comment by xiaoyifang** [comment]
seems a regression
do you use modern style and have you customized the style ?

**Comment by xiaoyifang** [comment]
> Would it be possible to allow users to decide the background color of the search area ?
yes,follow the instruction http://goldendict.org/wiki/index.php/FAQ#:~:text=Search%20box%20and%20wordlist%20fonts

**Comment by xiaoyifang** [comment]
![Uploading image.png…]()

**Comment by Immunize2** [comment]
> do you use modern style and have you customized the style ?

**Modern style without any customization.**

I also think that the problem is a regression. It might be related to the latest commits in August/September.

**Comment by Immunize2** [comment]
Problem solved with the latest commit (bccfc52) !

Thank you very much @xiaoyifang  :1st_place_medal: 

![grafik](https://user-images.githubusercontent.com/111645935/188314095-1d2b2464-0c3f-4783-b9d5-7fa3ff487bfa.png)
