### ISSUE TITLE
Doesn't work on Lubuntu 22.04

### ISSUE THREAD

**Issue by satirdanKahraman** [xiaoyifang/goldendict#137]
I downloaded "22.8.24-alpha.f0e3c389" version on appimage for lubuntu but when I query, it stays on the blank screen.

![image](https://user-images.githubusercontent.com/85233642/188953469-f7e97726-3d85-4309-8e06-dc56399b94e0.png)
![image](https://user-images.githubusercontent.com/85233642/188953596-2ee050ba-cc1d-4452-ad67-9e75a8a2b8a8.png)

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/issues/107

**Comment by xiaoyifang** [comment]
I think I should remove appimage in a later time.
for the following reasons:
- appimage can not built on newer ubuntu 
- does not support qt6 well
- and all other issues.

recommend the linux users to build the goldendict from source .

**Comment by xiaoyifang** [comment]
this appimage should be work.
https://github.com/xiaoyifang/goldendict/releases/tag/v22.9.24-alpha.221027.f2dc49a2

I only testified it in fedora

**Comment by satirdanKahraman** [comment]
thanks for your efforts! :)
