### ISSUE TITLE
document request for difference with the upstream

### ISSUE THREAD

**Issue by Ethkuil** [xiaoyifang/goldendict#147]
I found this repo when looking through `goldendict/goldendict`. This repo has more than 1k commits ahead of the upstream(and only 3 commits behind), so I'm curious about what are the differences(I only know about the environment, like version of Windows and Qt from README).

---

我在翻GoldenDict的官方仓库时发现了这个repo，看到这个repo相比upstream新了一千多个commits，所以比较好奇有哪些区别。从README只发现了“支持更新的环境”这点。

**Comment by xiaoyifang** [comment]
You can get a rough idea from here 
https://github.com/xiaoyifang/goldendict/blob/staged/CHANGES.md
