### ISSUE TITLE
Qt6.3版无法记住在词条结果页面做的设置

### ISSUE THREAD

**Issue by pureal** [xiaoyifang/goldendict#149]
有些词典在词条结果页面可以通过点击按钮进行配置，比如选择是否显示例句的中文翻译。在Qt5.15中可以记住这一设置（保存到localstorge?），在下次打开gd后保持之前的设置。而6.3版在每次重启软件后这些设置丢失。是否可以修复这一bug呢？谢谢!

**Comment by xiaoyifang** [comment]
听起来是词典本身的设置，跟软件无关。
