### ISSUE TITLE
在使用LDOCE5++ v2.15时例句发音会连读产生混响

### ISSUE THREAD

**Issue by elisir516** [xiaoyifang/goldendict#154]
如题，连读开始时间相差很短。
之前的版本也有这个问题。
对比一下，goldendict++和官方ru.下载的都没事。

**Comment by xiaoyifang** [comment]
应该是词典问题，词典用的是在线发音。
多次点击的时候，是网页在播放，没有经过gd软件。

**Comment by elisir516** [comment]
感谢回复。
找到原因了。之前是把goldendict++下的content文件夹直接拷了过来，带有它的索引。把content下全部清空，然后拷入该词典，就没问题了。

**Comment by xiaoyifang** [comment]
原则上不应该会受到这个的影响
不过没问题，就ok
