### ISSUE TITLE
Article disappears when multiple .js files are used

### ISSUE THREAD

**Issue by epistularum** [xiaoyifang/goldendict#156]
Trying to display two or more different dictionaries that make use of a .js file results in one of the entries getting hidden.

Two dictionaries:
https://user-images.githubusercontent.com/34507493/192153557-287880ac-dfcf-4a3c-aedb-c56a1f7b786f.mp4

More than two:
https://user-images.githubusercontent.com/34507493/192153549-997da71d-75b0-427f-bc06-430722a42944.mp4

**Comment by xiaoyifang** [comment]
I did not get the idea.
Do you mean display the same dictionary (in two different folders) twice ,will result in one of them hidden?

**Comment by epistularum** [comment]
It doesn't just happen with the same dictionary. Perhaps this video explains it better:

https://user-images.githubusercontent.com/34507493/192187010-6f77f38b-daa1-49ce-affd-a1290d0bc562.mp4

**Comment by xiaoyifang** [comment]
I think the reason is because this part of js
```
function(e) {
			 e.innerHTML = e.innerHTML
				.replace(/<script src="(.*?)kojien.js" type="text\/javascript"><\/script><div class="hw">([^<]*)(.*?)<\/div>/, '<div class="hw">$2$3</div><div class="image" onclick="enlarge(this)"><img src="$1img/$2.png" onerror="hide(this)" /><br><img src="$1img/$22.png" onerror="hide(this)" /></div>')
				.replace(/{([一-�])}/g,"<tk>$1</tk>");
		}


```

the replace function is problematic

**Comment by epistularum** [comment]
I see, please excuse me for the time wasted on this issue!
