### ISSUE TITLE
建议单字级简繁转换，并外置对照表，可自定义

### ISSUE THREAD

**Issue by asgsdbrseg** [xiaoyifang/goldendict#157]
由于opencc把含「黄」的词语都进行了词语级转换，导致「黄」无法被正确匹配，如「黄门」无法匹配「黄門」、「黄钟」无法匹配「黄鐘」、「黄鍾」。建议只进行单字级转换。
「锺」可以匹配「鍾」，但「鍾」不能匹配「锺」。其他尚有不少字无法匹配，不一一列举。建议对照表可自定义。

**Comment by xiaoyifang** [comment]
>对照表可自定义

目前是可以自己定义的，修改下opencc目录下的相关配置文件。可以采用自定义的。

**Comment by asgsdbrseg** [comment]
是否支持每个标签页单独分组？

**Comment by xiaoyifang** [comment]
> 是否支持每个标签页单独分组？

没大明白你的意思，具体描述下

**Comment by asgsdbrseg** [comment]
![image](https://user-images.githubusercontent.com/68012384/194310030-a76fd83e-2e5e-45bf-8b1c-d2c3a81a72c3.png)
目前切换分组，会在所有标签页生效，我希望在不同标签页启用不同分组，搜索不同的词语

**Comment by xiaoyifang** [comment]
是个想法，一些交互的方面需要考虑。
比如上面切换分组的时候，下面的标签页（标签页可能还不存在）是否要对应切换。
下面的标签页切换，上面的的分组的选项是不是也要跟着变换。
分组数据改动（比如删掉一个分组）的时候，标签页怎么处理。

**Comment by xiaoyifang** [comment]
这个问题转到https://github.com/xiaoyifang/goldendict/issues/165 。
此issue关闭。
