### ISSUE TITLE
在显示器启用缩放的情况下词典略缩图缩放不正确，非常模糊。

### ISSUE THREAD

**Issue by 12vpn** [xiaoyifang/goldendict#160]
![无标题](https://user-images.githubusercontent.com/44104393/193432278-61a3ab3c-2a4d-4a57-a675-691103641e39.png)
注意右上角略缩图，goldendict把原来原来512x512的logo压缩为32x32，然后又将它显示为100多个像素的大小，导致图片非常模糊，希望作者能修复一下，谢谢！

**Comment by xiaoyifang** [comment]
怎么放大到这个大小的。

**Comment by 12vpn** [comment]
> 怎么放大到这个大小的。

Ctrl+加号放大。

**Comment by xiaoyifang** [comment]
2c9fdd522749bdbc1cb19eb3ddc022c205fd8258

增大到50x50
