### ISSUE TITLE
发音词典点击后没有声音

### ISSUE THREAD

**Issue by Pseud0nymer** [xiaoyifang/goldendict#164]
m1 MacBook Pro
macOS Monterey: 12.6  
22.9.23-AutumnEquinox.7e83b920 on 2022/10/01

点击mdx/mdd里的音频项目不发音，

但GD官方论坛开发者版本（如下方）发音是没问题的

GoldenDict 电子词典程序，版本 1.5.0-RC2-372-gc3ff15f
(c) 2008-2013 Konstantin Isakov (ikm@goldendict.org)
授权基于 GNU 公共授权 GPLv3 或更高版本
基于 Qt 5.12.1 (Clang 8.1.0 (clang-802.0.38),64 位）

如果能解决一下，深为感激！

**Comment by xiaoyifang** [comment]
估计音频格式是spx的吧，如果是的话，mac版本的是不支持的。
可以设置下通过外置播放器播放音频。

**Comment by Pseud0nymer** [comment]
谢谢您的答复！
确实是spx，但下面这个版本支持的很好
请问控制声音的是包里哪个目录？我互换一下试试😄


来源想必您也知道：https://sourceforge.net/projects/goldendict/files/early%20access%20builds/Qt5-based/64bit/

**Comment by xiaoyifang** [comment]
应该没法简单互换。

采用外置播放设置会更简单一点。
![image](https://user-images.githubusercontent.com/105986/194310107-235ccec8-59a1-4354-aa0c-166b3cc500ff.png)

有人是这么配置的。
/Applications/VLC.app --play-and-stop -I dummy
![image](https://user-images.githubusercontent.com/105986/194310665-8c179bc0-310a-4f7f-9a05-cfbf49ccdbe3.png)

**Comment by xiaoyifang** [comment]
或者自动编译的版本中的macos homebrew版本你也可以尝试下。

**Comment by Pseud0nymer** [comment]
您好， 请问homebrew版本的代码是多少？


我在安装了homebrew后在终端输入下面的代码后似乎报错了
brew install qt # or use official offline installer
qmake CONFIG+=release   CONFIG+=zim_support   CONFIG+=chinese_conversion_support QMAKE_APPLE_DEVICE_ARCHS="x86_64 arm64"
make 
make install
========================下面是结果================
***@***.*** ~ % brew install qt # or use official offline installer
qmake CONFIG+=release   CONFIG+=zim_support   CONFIG+=chinese_conversion_support QMAKE_APPLE_DEVICE_ARCHS="x86_64 arm64"
make 
make install
fatal: not in a git directory
Warning: No remote 'origin' in /opt/homebrew/Library/Taps/homebrew/homebrew-cask, skipping update!
fatal: not in a git directory
Warning: No remote 'origin' in /opt/homebrew/Library/Taps/homebrew/homebrew-core, skipping update!
fatal: not in a git directory
Warning: No remote 'origin' in /opt/homebrew/Library/Taps/homebrew/homebrew-services, skipping update!
==> Homebrew has enabled anonymous aggregate formula and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics have been recorded yet (nor will be during this `brew` run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

Warning: No available formula with the name "#".
==> Searching for similarly named formulae...
These similarly named formulae were found:
a2ps                                 firebase-cli                         libquicktime                         radamsa
a52dec                               firefoxpwa                           libquvi                              radare2
aacgain                              fish                                 libraqm                              ragel
。。。。

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/releases/tag/v22.9.24-alpha.221012.78d21723
可以试下上面的mac dmg版本，使用ffmpeg+libao的引擎，看下spx是不是可以正常播放了。

**Comment by Pseud0nymer** [comment]
谢谢，不过报错了


------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               GoldenDict [60219]
Path:                  /private/var/folders/*/GoldenDict.app/Contents/MacOS/GoldenDict
Identifier:            org.goldendict
Version:               22.9 (???)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-10-16 15:48:48.1262 +0800
OS Version:            macOS 12.6 (21G115)
Report Version:        12
Anonymous UUID:        3D504B65-6B42-D244-0D11-D5A0C62902FF

Sleep/Wake UUID:       7C4EBCB9-253B-4E5F-93AE-094F390104B7

Time Awake Since Boot: 70000 seconds
Time Since Wake:       1856 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '/usr/local/share/vcpkg/packages/ffmpeg_x64-osx-dynamic/lib/libavcodec.58.dylib'
Referenced from: '/private/var/folders/*/GoldenDict.app/Contents/MacOS/GoldenDict'
Reason: tried: '/usr/local/share/vcpkg/packages/ffmpeg_x64-osx-dynamic/lib/libavcodec.58.dylib' (no such file), '' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   Rosetta Runtime Routines	       0x1038d3940 ???
1   <translation info unavailable>	       0x1039221cc ???
2   dyld                          	       0x2034eba72 abort_with_payload_wrapper_internal + 80
3   dyld                          	       0x2034ebaa4 abort_with_payload + 9
4   dyld                          	       0x203499699 dyld4::halt(char const*) + 615
5   dyld                          	       0x2034955b5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3995
6   dyld                          	       0x2034944e4 start + 388

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7fff33944 0x7ff7fff2f000 + 18756
1   runtime                       	    0x7ff7fff413e0 0x7ff7fff2f000 + 74720
2   runtime                       	    0x7ff7fff42e58 0x7ff7fff2f000 + 81496


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000030a4c7930   x3: 0x00000000000000fd
    x4: 0x000000030a4c7530   x5: 0x0000000000000000   x6: 0x2a08002172baa768   x7: 0x0000002017fffa35
    x8: 0x000000030a4c7530   x9: 0x0000000000000000  x10: 0x00000000000000fd  x11: 0x000000030a4c7993
   x12: 0x00000000000000fd  x13: 0x000000030a4c7930  x14: 0x0000000000000001  x15: 0x0000000000000006
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x800000010b93cb70  x19: 0x00000001038c9000
   x20: 0x00000000000007ff  x21: 0x000000010b941fa0  x22: 0xffffffffffffffff  x23: 0x00000001038d3914
   x24: 0x00000002034eba72  x25: 0x00000001038d31f4  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x00000002034d598e   fp: 0x000000002c000000   lr: 0x00000001039221cc
    sp: 0x000000010b93cb70   pc: 0x00000001038d3940 cpsr: 0x80001000
   far: 0x0000000103922000  esr: 0x56000080  Address size fault

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x20348f000 -        0x2034fafff dyld (*) <71febccd-d9dc-3599-9971-2b3407c588a8> /usr/lib/dyld
    0x7ff7fff2f000 -     0x7ff7fff5efff runtime (*) <1f0f0114-cfb6-304b-8183-8ef52c21f8b4> /usr/libexec/rosetta/runtime

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=9096K resident=0K(0%) swapped_out_or_unallocated=9096K(100%)
Writable regions: Total=156.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=156.4M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Rosetta Arena                     4096K        2 
Rosetta Generic                    784K      193 
Rosetta IndirectBranch              32K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                20K        2 
Rosetta Thread Context              20K        2 
Stack                             8176K        1 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       13.3M        6 
VM_ALLOCATE (reserved)             100K        8         reserved VM address space (unallocated)
__DATA                            1424K       14 
__DATA_CONST                       400K        8 
__LINKEDIT                        1280K       15 
__TEXT                            7856K       11 
dyld private memory               1024K        1 
mapped file                        6.1G       55 
===========                     =======  ======= 
TOTAL                              6.3G      321 
TOTAL, minus reserved VM space     6.3G      321 



-----------
Full Report
-----------

{"app_name":"GoldenDict","timestamp":"2022-10-16 15:48:48.00 +0800","app_version":"22.9","slice_uuid":"215fd5f1-9aba-3c7f-acb7-722ce37b2498","build_version":"","platform":1,"bundleID":"org.goldendict","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6 (21G115)","incident_id":"50117F0E-B0F5-41C1-A978-6223AB32E602","name":"GoldenDict"}
{
  "uptime" : 70000,
  "procLaunch" : "2022-10-16 15:48:37.5650 +0800",
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro17,1",
  "procStartAbsTime" : 1680629414603,
  "coalitionID" : 12746,
  "osVersion" : {
    "train" : "macOS 12.6",
    "build" : "21G115",
    "releaseType" : "User"
  },
  "captureTime" : "2022-10-16 15:48:48.1262 +0800",
  "incident" : "50117F0E-B0F5-41C1-A978-6223AB32E602",
  "bug_type" : "309",
  "pid" : 60219,
  "procExitAbsTime" : 1680882876807,
  "translated" : true,
  "cpuType" : "X86-64",
  "procName" : "GoldenDict",
  "procPath" : "\/private\/var\/folders\/*\/GoldenDict.app\/Contents\/MacOS\/GoldenDict",
  "bundleInfo" : {"CFBundleShortVersionString":"22.9","CFBundleIdentifier":"org.goldendict"},
  "storeInfo" : {"deviceIdentifierForVendor":"24D36884-D8B9-5391-A883-504EF3DA4507","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.goldendict",
  "crashReporterKey" : "3D504B65-6B42-D244-0D11-D5A0C62902FF",
  "wakeTime" : 1856,
  "sleepWakeUUID" : "7C4EBCB9-253B-4E5F-93AE-094F390104B7",
  "sip" : "disabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: '\/usr\/local\/share\/vcpkg\/packages\/ffmpeg_x64-osx-dynamic\/lib\/libavcodec.58.dylib'","Referenced from: '\/private\/var\/folders\/*\/GoldenDict.app\/Contents\/MacOS\/GoldenDict'","Reason: tried: '\/usr\/local\/share\/vcpkg\/packages\/ffmpeg_x64-osx-dynamic\/lib\/libavcodec.58.dylib' (no such file), '' (no such file), '' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":1502039,"threadState":{"x":[{"value":6},{"value":1},{"value":13057685808},{"value":253},{"value":13057684784},{"value":0},{"value":3028670893065414504},{"value":137841605173},{"value":13057684784},{"value":0},{"value":253},{"value":13057685907},{"value":253},{"value":13057685808},{"value":1},{"value":6},{"value":521},{"value":0},{"value":9223372041343978352},{"value":4354510848},{"value":2047},{"value":4489224096},{"value":18446744073709551615},{"value":4354554132},{"value":8645425778,"symbolLocation":80,"symbol":"abort_with_payload_wrapper_internal"},{"value":4354552308},{"value":0},{"value":0},{"value":8645335438,"symbolLocation":10,"symbol":"__abort_with_payload"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4354875852},"cpsr":{"value":2147487744},"fp":{"value":738197504},"sp":{"value":4489202544},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4354554176,"matchesCrashFrame":1},"far":{"value":4354875392}},"frames":[{"imageOffset":4354554176,"region":"Rosetta Runtime Routines","symbolLocation":10560,"imageIndex":0},{"imageOffset":4354875852,"region":"<translation info unavailable>","imageIndex":0},{"imageOffset":379506,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":1},{"imageOffset":379556,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":42649,"symbol":"dyld4::halt(char const*)","symbolLocation":615,"imageIndex":1},{"imageOffset":26037,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3995,"imageIndex":1},{"imageOffset":21732,"symbol":"start","symbolLocation":388,"imageIndex":1}]},{"id":1502446,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18756,"imageIndex":2},{"imageOffset":74720,"imageIndex":2},{"imageOffset":81496,"imageIndex":2}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8645046272,
    "size" : 442368,
    "uuid" : "71febccd-d9dc-3599-9971-2b3407c588a8",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703127760896,
    "size" : 196608,
    "uuid" : "1f0f0114-cfb6-304b-8183-8ef52c21f8b4",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  }
],
  "sharedCache" : {
  "base" : 140703150325760,
  "size" : 19331678208,
  "uuid" : "3765e290-e8ae-3af7-92bf-da62dfb8ac4f"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=9096K resident=0K(0%) swapped_out_or_unallocated=9096K(100%)\nWritable regions: Total=156.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=156.4M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nRosetta Arena                     4096K        2 \nRosetta Generic                    784K      193 \nRosetta IndirectBranch              32K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nStack                             8176K        1 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       13.3M        6 \nVM_ALLOCATE (reserved)             100K        8         reserved VM address space (unallocated)\n__DATA                            1424K       14 \n__DATA_CONST                       400K        8 \n__LINKEDIT                        1280K       15 \n__TEXT                            7856K       11 \ndyld private memory               1024K        1 \nmapped file                        6.1G       55 \n===========                     =======  ======= \nTOTAL                              6.3G      321 \nTOTAL, minus reserved VM space     6.3G      321 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60f8ddccefea4203d95cbeef",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    },
    {
      "rolloutId" : "6112dda2fc54bc3389840642",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "631730a28520965d1cba0681"
      },
      "deploymentId" : 240000143
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro17,1, BootROM 7459.141.1, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: DELL U2718QM, 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition), Main, MirrorOff, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Mar 23 2022 19:57:59 version 18.60.27.0.7.8.129 FWID 01-570be953
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
PCI Card: pci1b73,1100, USB eXtensible Host Controller, ***@***.***,0,0
PCI Card: pci1b73,1100, USB eXtensible Host Controller, ***@***.***,0,0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB30Bus
USB Device: ThinkPad Thunderbolt 3 Dock MCU
USB Device: ThinkPad Thunderbolt 3 Dock USB Audio
USB Device: USB30Bus
USB Device: USB5734
USB Device: ThinkPad TBT3 LAN
USB Device: USB2734
USB Device: Hub Controller
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Device: ThinkPad Thunderbolt 3 Dock, Lenovo, 1, 33.1

**Comment by xiaoyifang** [comment]
多谢，先revert。
