### ISSUE TITLE
xapian版本占用cpu值很高

### ISSUE THREAD

**Issue by abc16361** [xiaoyifang/goldendict#168]
试了近日两xapian版本，任务管理器下挂载的welcome!-GoldenDict占用很高cpu值。 原先的普通版这两天每次打开也要先扫描词典的index，不是很爽。

ps. 系统是 Windows 10

![gd-cpu](https://user-images.githubusercontent.com/101362122/195787177-fa93b611-87c0-488e-bd8d-2202f17a5181.png)

谢谢！

**Comment by xiaoyifang** [comment]
提供版本号。

cpu占用应该是再做全文索引。

**Comment by abc16361** [comment]
xapan版是这两个
6.3.1-GoldenDict.exe_windows-2019_20221012-experimental-xapian.zip
6.4.0-GoldenDict.exe_windows-2019_20221014-experimental-xapian.zip （今天）
cpu值上次更高，今天这个降低了，但仍高。 

普通版是这个
6.3.1-GoldenDict.exe_windows-2019_20221012.zip
昨天用时打开都会先扫下index，但今天就没有，总体感觉还可以。
前一两天发现C盘没了空间，查看发现roaming下的godendict/index占了9+gb，不知何时出现，现已用新的文件夹，目前稳定，在用6.3.1-GoldenDict.exe_windows-2019_20221012.zip。

**Comment by xiaoyifang** [comment]
xapian的版本相比普通版会占用比较多的磁盘空间
可以将C盘index目录 链接 到其他磁盘。使用mklink的命令

**Comment by abc16361** [comment]
好的， 谢谢！
