### ISSUE TITLE
Entry Icons Broken

### ISSUE THREAD

**Issue by Eosphorus** [xiaoyifang/goldendict#169]
Ever since version '6.3.1-GoldenDict.exe_windows-2019_20221010', there is a problem with the display of the dictionary icons in the enty display.
They are simply too big in some cases and aren't reduced to a standard size.
![icon thing](https://user-images.githubusercontent.com/8929191/196117601-851a241d-d4f5-42eb-96d5-2910c6bd1866.jpg)

Thanks for reading.

**Comment by xiaoyifang** [comment]
seems like a regression introduced by https://github.com/xiaoyifang/goldendict/issues/160

But,has not been reproduced in my machine

**Comment by Eosphorus** [comment]
Indeed, changing display style and add-on style solves the problem.

Thanks for the quick reply.
