### ISSUE TITLE
silently die on indexing in portable version

### ISSUE THREAD

**Issue by ovdikklop** [xiaoyifang/goldendict#174]
if one create folder portable (that meant to store portable indexes) next to goldendict.exe, it just silently die after some time.  No matter xapian or reguler build.
I suppose that this is an issue with one of my dictionaries, but i cannot figure out with which one, because there are no crash logs.

**Comment by xiaoyifang** [comment]
start the goldendict with --log-to-file such as
` goldendict --log-to-file`  it will log some debug info in the log.txt.

or you can use bisearch method to find out the dictionary which cause the crash.
