### ISSUE TITLE
添加Anki制卡支持

### ISSUE THREAD

**Issue by WritingWithFire** [xiaoyifang/goldendict#175]
我在首选项页面看到了这个
![image](https://user-images.githubusercontent.com/66851780/197367286-fda69618-61bd-4666-b0ca-d6612b34cb25.png)

嗯，不知道是我不会用还是什么原因，如果这个功能已经添加，有好心人能告诉我怎么用吗

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/blob/staged/howto/how%20to%20connect%20with%20anki.md

**Comment by WritingWithFire** [comment]
As always thanks for ur patience
