### ISSUE TITLE
能否改变ctrl + c + c的快捷键

### ISSUE THREAD

**Issue by WritingWithFire** [xiaoyifang/goldendict#176]
ctrl + c + c很容易与其他软件的快捷键冲突，是否有方法改成其他的？
首选项里面虽然可以改，但不知为何不起作用

冲突软件：snipaste 1.16.2，冲突键位：ctrl + c

**Comment by xiaoyifang** [comment]
目前没办法，gd依赖ctrl+C ，将文本拷贝到剪贴板 ，  ctrl+C+C 实际上是剪贴板取词。

**Comment by WritingWithFire** [comment]
或许gd的取词功能还需要大的改进。。。

**Comment by xiaoyifang** [comment]
是的。结合其他ocr工具，灵活性会高一下。
