### ISSUE TITLE
Add hotkey for backwards and forwards on Mac

### ISSUE THREAD

**Issue by itkind** [xiaoyifang/goldendict#178]
Hi,pressing option and the arrow key is not the same as clicking backwards to jump exactly to the place you been before. Is it possible to assign a hotkey for that? Thanks

**Comment by xiaoyifang** [comment]
from code perspective,alt+arrow should be the same as click the button

**Comment by itkind** [comment]
I tested it again and you are right. There is an other issue with going backwards: if you double click a word to open a new entry and then going back, you don't go back to the exact place where you double clicked the word but rather to a higher position.

**Comment by xiaoyifang** [comment]
have you enable the option "jump to target article"

**Comment by itkind** [comment]
Do you mean the option "automatically scroll to target article"? Yes but this is not working backwards.

**Comment by xiaoyifang** [comment]
unchecked the above option and try again

**Comment by itkind** [comment]
Same behaviour

**Comment by xiaoyifang** [comment]
will check at a later time

**Comment by xiaoyifang** [comment]
can  not be reproduced on Windows. 
macos can  be wait for other's help

**Comment by itkind** [comment]
Is it possible to assign the backspace as the shortcut for backwards?
