### ISSUE TITLE
Broken dictionary entry icons

### ISSUE THREAD

**Issue by epistularum** [xiaoyifang/goldendict#179]
I have disabled all custom styles and this is using the "Modern" display style.
![image](https://user-images.githubusercontent.com/34507493/198003036-74948698-71ea-49c5-9405-def95c899a40.png)
![image](https://user-images.githubusercontent.com/34507493/198003434-a46ca46c-c676-4491-a856-3df15bfa2450.png)

**Comment by xiaoyifang** [comment]
all the dictionary or just one of them?

**Comment by epistularum** [comment]
@xiaoyifang All of them.

**Comment by xiaoyifang** [comment]
can not reproduce it ,but I think it was a regression.
already revert some code ,can you check again?

**Comment by epistularum** [comment]
@xiaoyifang Issue has been fixed! As always, thank you very much for the work done ♥
