### ISSUE TITLE
点击“后退”切回上一查询后 ， “在以下字典中找到”列表未更新

### ISSUE THREAD

**Issue by ausonD** [xiaoyifang/goldendict#184]
如视频中所指，不知是否能烦请够修复一下呢？

https://user-images.githubusercontent.com/107112623/199021323-41c64ba9-436f-441d-800b-ae1342219e3c.mp4

**Comment by xiaoyifang** [comment]
不好修改。后退本身只是网页的后退。

右侧的词典是gd处理的。后退的时候，无法同步。

先放着吧。

**Comment by xiaoyifang** [comment]
已修改

**Comment by ausonD** [comment]
太牛了 ！

大侠有捐助渠道吗

**Comment by xiaoyifang** [comment]
没计划
