### ISSUE TITLE
Dark Mode for Windows?

### ISSUE THREAD

**Issue by loyukfai** [xiaoyifang/goldendict#188]
Is it possible to implement a dark mode for Windows? (and possibly other OS too)

Something just follow the system setting would be nice.

Thanks in advance.

**Comment by xiaoyifang** [comment]
can be achieved with  custom style sheets

**Comment by loyukfai** [comment]
Thanks! But can I make it automatically follow the system-wide theme change which happens on sunrise and sundown?

Cheers.

**Comment by leanhdung1994** [comment]
There is a great dark theme here https://github.com/Giai-Ngo/Goldendict-theme/tree/main/Dark%20theme.

**Comment by xiaoyifang** [comment]
license is Attribution-NonCommercial 2.0 Generic ([CC BY-NC 2.0](https://creativecommons.org/licenses/by-nc/2.0/))
does it compatible with gpl3?

**Comment by BEST8OY** [comment]
@xiaoyifang 
Why it doesn't get fully dark ?(arch linux)
![Screenshot from 2022-11-10 04-01-18](https://user-images.githubusercontent.com/70865987/200971763-88ce0246-b4f6-4174-9beb-354ea55ead49.jpg)

**Comment by xiaoyifang** [comment]
How do you customize the stylesheet?
I guess there are some styles has not been applied.

**Comment by BEST8OY** [comment]
> How do you customize the stylesheet? I guess there are some styles has not been applied.

I applied them as guided in these two theme
https://github.com/Giai-Ngo/Goldendict-theme/tree/main/Dark%20theme
https://github.com/goldendict/goldendict/wiki/GoldenDict-Dark-Theme
Maybe these themes are old?

**Comment by xiaoyifang** [comment]
seems like that the style has lack the dark style for toolbar

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/206882132-404190b1-f003-423c-8212-0aaa3c446829.png)

**Comment by shenlebantongying** [comment]
On macOS, there is already a native dark mode (with glitches that should be fixed).

On Linux, modifying the default style is a norm. The proper way to have a dark theme on linux should be 

* using a Qt-based DE like lxqt or KDE
* use Qt theme changer like qt5ct
* use a DE/disto that has better Qt support like Xfce or Fedora.

Doing dark theming on our side should be limited to Windows only.

<img width="1043" alt="Screenshot 2022-12-22 at 12 43 21 AM" src="https://user-images.githubusercontent.com/20123683/209065411-d8134940-812f-45e1-a7d0-c15216f1c683.png">

**Comment by xiaoyifang** [comment]
https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5
