### ISSUE TITLE
couldn't open in macOS Ventura 13.0(22A380)

### ISSUE THREAD

**Issue by hyde357** [xiaoyifang/goldendict#193]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               GoldenDict [77213]
Path:                  /Applications/GoldenDict.app/Contents/MacOS/GoldenDict
Identifier:            org.goldendict
Version:               22.9 (???)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-11-05 15:18:43.8735 +0800
OS Version:            macOS 13.0 (22A380)
Report Version:        12
Anonymous UUID:        C25BE915-49F2-8A4D-390D-8B9B9A1116AF

Sleep/Wake UUID:       A1FD7933-0B1E-4674-A1BC-BA8800BF4D96

Time Awake Since Boot: 200000 seconds
Time Since Wake:       114789 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/share/vcpkg/packages/ffmpeg_arm64-osx-dynamic/lib/libavutil.56.dylib
Referenced from: <84D28425-BE8C-3818-B40D-1523EBD25B36> /Applications/GoldenDict.app/Contents/Frameworks/libswresample.dylib
Reason: tried: '/usr/local/share/vcpkg/packages/ffmpeg_arm64-osx-dynamic/lib/libavutil.56.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/vcpkg/packages/ffmpeg_arm64-osx-dynamic/lib/libavutil.56.dylib' (no such file), '/usr/local/share/vcpkg/packages/ffmpeg_arm64-osx-dynamic/lib/libavutil.56.dylib' (no such file), '/usr/local/lib/libavutil.56.dylib' (no such file), '/usr/lib/libavutil.56.dylib' (no such file, not in dyld cache)Library not loaded: /usr/local/share/vcpkg/packages/ffmpeg_arm64-osx-dynamic/lib/libavcodec.58.dylib
Referenced from: <B4001F74-5EE1-3088-9333-DEEC34FB253E> /Applications/GoldenDict.app/Contents/Frameworks/libavformat.dylib
Reason: tried: '/usr/local/share/vcpkg/packages/ffmpeg_arm64-osx-dynamic/lib/libavcodec.58.dylib' (no such
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x18e62ee58 __abort_with_payload + 8
1   dyld                          	       0x18e6396c0 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x18e6396f4 abort_with_payload + 16
3   dyld                          	       0x18e5c80a4 dyld4::halt(char const*) + 328
4   dyld                          	       0x18e5c5098 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4204
5   dyld                          	       0x18e5c3dc4 start + 2404

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016b879ef0   x3: 0x00000000000000a9
    x4: 0x000000016b879af0   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000037  x14: 0x0000000000000005  x15: 0xffffffffffffffff
   x16: 0x0000000000000209  x17: 0x000000018e5c1344  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016b879af0  x21: 0x00000000000000a9  x22: 0x000000016b879ef0  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x00000001ea4c03c0  x26: 0x000000016b87b3e0  x27: 0x000000016b87b248
   x28: 0x0000000000000000   fp: 0x000000016b879ac0   lr: 0x000000018e6396c0
    sp: 0x000000016b879a80   pc: 0x000000018e62ee58 cpsr: 0x00001000
   far: 0x0000000104a7c000  esr: 0x56000080  Address size fault

Binary Images:
       0x18e5be000 -        0x18e6484af dyld (*) <1f56ab4e-f398-3a9c-bfba-fbbd17808963> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 2226
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)
Writable regions: Total=19.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=19.6M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__AUTH                             572K      132 
__AUTH_CONST                      10.3M      276 
__DATA                            15.1M      300 
__DATA_CONST                      20.9M      313 
__DATA_DIRTY                       678K       97 
__FONT_DATA                        2352        1 
__LINKEDIT                       772.9M       37 
__OBJC_CONST                      1160K      107 
__OBJC_RO                         65.1M        1 
__OBJC_RW                         1981K        1 
__TEXT                           382.9M      327 
dyld private memory                512K        2 
===========                     =======  ======= 
TOTAL                              1.3G     1597 

-----------
Full Report
-----------

{"app_name":"GoldenDict","timestamp":"2022-11-05 15:18:44.00 +0800","app_version":"22.9","slice_uuid":"dc8faf03-b27a-3d97-be6c-b2e18f1da4f6","build_version":"","platform":1,"bundleID":"org.goldendict","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.0 (22A380)","roots_installed":0,"name":"GoldenDict","incident_id":"8237C30F-24B3-48E7-B67B-3C1617A54A60"}
{
  "uptime" : 200000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,4",
  "coalitionID" : 33287,
  "osVersion" : {
    "train" : "macOS 13.0",
    "build" : "22A380",
    "releaseType" : "User"
  },
  "captureTime" : "2022-11-05 15:18:43.8735 +0800",
  "incident" : "8237C30F-24B3-48E7-B67B-3C1617A54A60",
  "pid" : 77213,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2022-11-05 15:18:43.8334 +0800",
  "procStartAbsTime" : 4876584253808,
  "procExitAbsTime" : 4876585178950,
  "procName" : "GoldenDict",
  "procPath" : "\/Applications\/GoldenDict.app\/Contents\/MacOS\/GoldenDict",
  "bundleInfo" : {"CFBundleShortVersionString":"22.9","CFBundleIdentifier":"org.goldendict"},
  "storeInfo" : {"deviceIdentifierForVendor":"39702E5E-FBC8-595E-B63A-976E5DCD8C1F","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.goldendict",
  "crashReporterKey" : "C25BE915-49F2-8A4D-390D-8B9B9A1116AF",
  "wakeTime" : 114789,
  "sleepWakeUUID" : "A1FD7933-0B1E-4674-A1BC-BA8800BF4D96",
  "sip" : "disabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: \/usr\/local\/share\/vcpkg\/packages\/ffmpeg_arm64-osx-dynamic\/lib\/libavutil.56.dylib","Referenced from: <84D28425-BE8C-3818-B40D-1523EBD25B36> \/Applications\/GoldenDict.app\/Contents\/Frameworks\/libswresample.dylib","Reason: tried: '\/usr\/local\/share\/vcpkg\/packages\/ffmpeg_arm64-osx-dynamic\/lib\/libavutil.56.dylib' (no such file), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/usr\/local\/share\/vcpkg\/packages\/ffmpeg_arm64-osx-dynamic\/lib\/libavutil.56.dylib' (no such file), '\/usr\/local\/share\/vcpkg\/packages\/ffmpeg_arm64-osx-dynamic\/lib\/libavutil.56.dylib' (no such file), '\/usr\/local\/lib\/libavutil.56.dylib' (no such file), '\/usr\/lib\/libavutil.56.dylib' (no such file, not in dyld cache)Library not loaded: \/usr\/local\/share\/vcpkg\/packages\/ffmpeg_arm64-osx-dynamic\/lib\/libavcodec.58.dylib","Referenced from: <B4001F74-5EE1-3088-9333-DEEC34FB253E> \/Applications\/GoldenDict.app\/Contents\/Frameworks\/libavformat.dylib","Reason: tried: '\/usr\/local\/share\/vcpkg\/packages\/ffmpeg_arm64-osx-dynamic\/lib\/libavcodec.58.dylib' (no such"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":2226},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":3640501,"threadState":{"x":[{"value":6},{"value":1},{"value":6099017456},{"value":169},{"value":6099016432},{"value":0},{"value":0},{"value":0},{"value":32},{"value":9},{"value":1},{"value":10},{"value":0},{"value":55},{"value":5},{"value":18446744073709551615},{"value":521},{"value":6683366212,"symbolLocation":392,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6099016432},{"value":169},{"value":6099017456},{"value":1},{"value":6},{"value":8225817536,"symbolLocation":0,"symbol":"gProcessInfo"},{"value":6099022816},{"value":6099022408},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6683858624},"cpsr":{"value":4096},"fp":{"value":6099016384},"sp":{"value":6099016320},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6683815512,"matchesCrashFrame":1},"far":{"value":4373069824}},"frames":[{"imageOffset":462424,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":0},{"imageOffset":505536,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":0},{"imageOffset":505588,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":0},{"imageOffset":41124,"symbol":"dyld4::halt(char const*)","symbolLocation":328,"imageIndex":0},{"imageOffset":28824,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4204,"imageIndex":0},{"imageOffset":24004,"symbol":"start","symbolLocation":2404,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6683353088,
    "size" : 566448,
    "uuid" : "1f56ab4e-f398-3a9c-bfba-fbbd17808963",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 6682705920,
  "size" : 3403612160,
  "uuid" : "5667eb2d-1398-3b38-afff-a929572d4b88"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)\nWritable regions: Total=19.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=19.6M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__AUTH                             572K      132 \n__AUTH_CONST                      10.3M      276 \n__DATA                            15.1M      300 \n__DATA_CONST                      20.9M      313 \n__DATA_DIRTY                       678K       97 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       772.9M       37 \n__OBJC_CONST                      1160K      107 \n__OBJC_RO                         65.1M        1 \n__OBJC_RW                         1981K        1 \n__TEXT                           382.9M      327 \ndyld private memory                512K        2 \n===========                     =======  ======= \nTOTAL                              1.3G     1597 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "610d52e1fc54bc3389840408",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_ASR_ASSISTANT" : "6348ad0234d9d80ede80aabb",
        "SIRI_UNDERSTANDING_MORPHUN" : "62ec7220c682040ba94e6a20"
      },
      "deploymentId" : 240000484
    },
    {
      "rolloutId" : "6112d17137f5d11121dcd4e2",
      "factorPackIds" : {

      },
      "deploymentId" : 240000147
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,4, BootROM 8419.41.10, proc 10:8:2 processors, 32 GB, SMC 
Graphics: Apple M1 Max, Apple M1 Max, Built-In
Display: PHL 346P1C, 5120 x 2144, Main, MirrorOff, Online
Display: LG ULTRAWIDE, 1728 x 4096, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Sep  3 2022 02:35:52 version 20.10.965.9.8.7.129 FWID 01-b0e84a9b
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: USB 10/100/1000 LAN, Ethernet, en9
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB3.0 Hub
USB Device: USB2.0 Hub
USB Device: ROUTIST R2
USB Device: USB 2.0 Hub
USB Device: USB Keyboard
USB Device: USB31Bus
USB Device: 4-Port USB 3.0 Hub
USB Device: USB 10/100/1000 LAN
USB Device: 4-Port USB 3.0 Hub
USB Device: USB3.1 Hub
USB Device: 4-Port USB 2.0 Hub
USB Device: USB2.0 FHD UVC WebCam
USB Device: USB Audio
USB Device: 4-Port USB 2.0 Hub
USB Device: USB2.1 Hub
Thunderbolt Bus: Laptop, Apple Inc.
Thunderbolt Bus: Laptop, Apple Inc.
Thunderbolt Bus: Laptop, Apple Inc.

**Comment by xiaoyifang** [comment]
which version do you use
