### ISSUE TITLE
strange behaviour of  keyboard shortcuts in windows qt6 builds

### ISSUE THREAD

**Issue by ovdikklop** [xiaoyifang/goldendict#194]
I used to assign "ctrl+c+c" as clipboard lookup shortcut for years. And with last qt6 builds it seems to do something weird - copied text just don't reach clipboard even after just ctrl+c, and goldendict popup is showing, but with old clipboard content.
In qt5 builds everything is working fine

**Comment by xiaoyifang** [comment]
windows restriction of ctrl+C

`run as administrator` should solve this issue
