### ISSUE TITLE
查词时闪退

### ISSUE THREAD

**Issue by WritingWithFire** [xiaoyifang/goldendict#197]
有时候查到某个词时会闪退，好像是内存调用的问题？
这个bug不能复现，随机出现的，当你查词查的正欢的时候给你搞一下

**Comment by xiaoyifang** [comment]
版本号提供下

**Comment by WritingWithFire** [comment]
版本号：GoldenDict-v22.9.23
Processor：Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz
Edition	Windows 10 Pro
Version	21H2
Installed on	‎2021/‎11/‎18
OS build	19044.2130
Experience	Windows Feature Experience Pack 120.2212.4180.0

词典：

- The Little Dict By GaryPang 2019.3.13
- Longman Dictionary of Contemporary English (LDOCE) En-Cn 5++ 2.15 By Farefear090807
- thesaurus.com近义词反义词词典 by GaryPang 2018.8.26
- 优词词源词典 By aepicure 2016-09-09
- [谷歌翻译](https://github.com/xinebf/google-translate-for-goldendict)

操作方式：选中一个词，按ctrl+c+c，闪退

- 并不是说遇到某个特定的词就闪退，闪退后再打开查同一个词是可以正常查的

**Comment by xiaoyifang** [comment]
用最新的版本试一下。
https://github.com/xiaoyifang/goldendict/releases/tag/v22.9.24-alpha.221104.0e7b49b0

**Comment by WritingWithFire** [comment]
试了两天，没问题
