### ISSUE TITLE
收藏内容导入时只支持xml格式

### ISSUE THREAD

**Issue by ausonD** [xiaoyifang/goldendict#198]
![图片](https://user-images.githubusercontent.com/107112623/200997657-30742ef2-bc0b-482e-a01b-a0bc68cc815a.png)
在大量查词时，导入单词，使用历史/收藏浏览非常方便。但是导入覆盖历史的话，一方面查词历史就丢失了，另一方面如果查到一半，新查一些词，又会扰乱导入的内容，有些不方便。于是想导入收藏夹进行浏览，

但如果想替换历史查询内容时，可以用txt文件导入，但是想替换收藏内容时，只支持xml,却不支持txt文件，会显示配置错误。

不知能否麻烦大佬增加一下导入收藏时，同样支持txt文件?

**Comment by xiaoyifang** [comment]
不是大佬。

收藏有层次关系。txt不方便实现层级。
