### ISSUE TITLE
forvo可以免费使用吗

### ISSUE THREAD

**Issue by WritingWithFire** [xiaoyifang/goldendict#200]
![image](https://user-images.githubusercontent.com/66851780/201812970-75a484b0-0594-4899-8cab-bf185706d5c7.png)
forvo的发音听着太舒服了，不过好像不能白嫖？

![image](https://user-images.githubusercontent.com/66851780/201813242-d09d27e3-6284-4cf2-988b-4ff76c9433a7.png)

在github上找了一圈，没有相关的项目。。
真的没办法白嫖了吗

**Comment by xiaoyifang** [comment]
https://github.com/goldendict/goldendict/issues/1563
forvo开始收费了。

有个办法，
通过网站词典的方式，如将
https://zh.forvo.com/search/%GDWORD%/
添加为网站词典。
