### ISSUE TITLE
双屏情况下快捷键失效

### ISSUE THREAD

**Issue by WritingWithFire** [xiaoyifang/goldendict#201]
![image](https://user-images.githubusercontent.com/66851780/201866185-d1d1ffd1-ad07-4bd4-b629-fe590175b776.png)
图中两个切换至搜索框的快捷键在电脑接有**多个屏幕**的情况下失效

**Comment by xiaoyifang** [comment]
什么版本。

gd菜单-》帮助-》关于

**Comment by xiaoyifang** [comment]
估计是qt的bug。多屏支持不好。

**Comment by xiaoyifang** [comment]
close ,as  it is a qt issue.
