### ISSUE TITLE
能把原来按住控制键才会取词的功能加回吗？

### ISSUE THREAD

**Issue by binglius** [xiaoyifang/goldendict#203]
最近由于不想再为自己系统维护一个qtwebkit，尝试了你这个版本，发现原来的一个按功能键才会取词的功能被取消了，非常不习惯。虽然可以通过设置选中后弹出取词的flag(图标）实现类似的效果，但是这个在不需要的时候也会弹出，可控性不佳，用户体验也有所下降，因为弹出flag 有延迟，并且会遮挡屏幕上内容。谢谢。

"Show scan flag when world is selected"

**Comment by xiaoyifang** [comment]
之前的取词功能是有限制的，
1，只对文本有用
2，使用范围受限，只在win32系统上可用

你需要的应该是ocr取词的功能，建议结合capture2text使用。
https://github.com/xiaoyifang/goldendict/blob/staged/howto/How%20to%20use%20ocr%20together%20with%20GoldenDict.md

或者搜索gdocrtool

**Comment by binglius** [comment]
我是用Linux 系统的，之前也主要是用于文本取词，对屏幕取词现阶段需求不是太大。而现在这功能很别扭，我如果不启用 Tracking Clickboard，他不会弹出　"Scan Popup"　的图标(flag)，而我如果启用后会导致每次复制一个字符串的时候会弹出一个无意义的翻译窗口。而且goldendict 主要是单词取词，并不支持句子，更希望把基本功能的体验不要丢了。

**Comment by xiaoyifang** [comment]
后续确认下

**Comment by binglius** [comment]
感谢很快处理了这个问题。这个功能好像修复了一半，现在界面设置有了，也可以通过控制键来控制取词了，但是他也同样依赖于"Tracking Clicpboard"，需要启用这个功能，这样在复制的时候还是会自动弹出取词窗口。

**Comment by binglius** [comment]
对于Linux 系统，selection 分三种，primary, secondary 和clipboard（复制粘贴用到的）。平时选中的时候应该关联的 primary selection 并作取词动作，而不是和clipboard 关联。 这也是原来版本的做法。

更多信息可以参考下面链接。 

echo primary | xclip -sel p
echo secondary | xclip -sel p
echo clipboard | xclip -sel c

# Ctrl + Shift + v: clipboard
# Middle click: primary
# Paste selection: (Shift + Insert): primary


https://shallowsky.com/blog/linux/x-selection.html

**Comment by xiaoyifang** [comment]
应该可以了。

**Comment by binglius** [comment]
不启用 "Tracking Clicpboard  还是不会弹出。可能函数内部的逻辑什么时候也改动了。

**Comment by xiaoyifang** [comment]
后续再看下

**Comment by shenlebantongying** [comment]
我试了一下，代码是可以跑到这里的。

https://github.com/xiaoyifang/goldendict/blob/f19e8bb0704bf6f33c7423378d373a598bdaaf17/scanpopup.cc#L516

问题在于无论是 Selection 还是 Ctrl+C 的 Copy 都是 Clipboard，然后都会被发送到这个统一的处理 Clipboard change 的方法。

https://github.com/xiaoyifang/goldendict/blob/f19e8bb0704bf6f33c7423378d373a598bdaaf17/scanpopup.cc#L47

启用 “Tracking Clipboard” 才能显示 Scanpopup 应该是正确的行为，因为逻辑上划词做一个 Selection 就是修改 Clipboard 的内容（X 的术语反正是这样的）

我不清楚老版本的 gd 是什么样的。

我觉得这个问题的正确解法是在 Linux 上区分一下，

在 tray 或者设置里面多加一个设置选项，选择某种模式 （取词模式？）：

1. Selection mode
2. Ctrl+C Copy mode
3. Both

**Comment by shenlebantongying** [comment]
另外 mac 上也有两个剪切板，第二个叫 findbuffer 用 Command+E 来放进去内容，
https://github.com/xiaoyifang/goldendict/blob/f19e8bb0704bf6f33c7423378d373a598bdaaf17/scanpopup.cc#L57

我觉得我们也可以支持一下类似的行为，区分一下 Ctrl+C 的复制 和 额外的剪切板

https://endofline.wordpress.com/2009/07/17/using-the-mac-os-x-find-buffer-for-text-navigation/

**Comment by xiaoyifang** [comment]
> void ScanPopup::clipboardChanged( QClipboard::Mode m )

应该是这里的问题。

**Comment by shenlebantongying** [comment]
这个地方好像没有 ui 文件，我觉得可以区分开成三小部分

* 通用的 scanpopup 设置
* Clipboard tracking 监控剪切板
* Selection tracking 的设置 (包括按住某个功能键才能用的选项)

这样用户可以独立地设置，并且把 linux 的代码放在一起方便 #ifdef，设置 selection 部分可以直接一个 hide

Tray 里面的 “Track Clipboard Change” 可以改下名 “Enable Tracking”

![image](https://user-images.githubusercontent.com/20123683/202840511-2071df33-8786-402d-a485-cc8cebf9c375.png)

"Show scan flag when word is selected" 的功能我觉得可以删掉，

**Comment by xiaoyifang** [comment]
> "Show scan flag when word is selected" 的功能我觉得可以删掉，

有人需要。

**Comment by shenlebantongying** [comment]
那就 "Show scan flag when word is selected" 也放到 Selection tracking 里面

**Comment by xiaoyifang** [comment]
里面的相关逻辑蛮多的，方便调整吗，
另外应该与ctrl+c+c也有关系。

**Comment by shenlebantongying** [comment]
我先试试把，主要就是区分开 Selection 和 Clipboard 然后加一个设置选项是否处理 Selection。原有的 Clipboard 相关代码应该应该可以只增不减

**Comment by binglius** [comment]
感谢感谢，这个功能已经习惯了，并且非常实用。我用Linux大部分时间都是用鼠标中键，比Ctrl+c用得还要更多。很多windows用户可能都不知道滚轮其实同时也是个按键（鼠标中键)，我鼠标中键都按坏好几个了。

**Comment by shenlebantongying** [comment]
![image](https://user-images.githubusercontent.com/20123683/202851284-d5d5433a-0800-4990-bef9-fb8c006708d5.png)

看了一下代码又看了一下 Windows 上行为，这个地方逻辑上有问题

* 如果 不启用 “Send to main window”，那么 Scan popup 和 Tracking Clipboard 两者必须同时启用才有用，单独打开一个没有意义，因为原来的划词已经没有了
* 如果启用了 “Send to main window”，那么 Scan popup 那个按钮就没有意义了，而且需要启用 Tracking Clipboard。
* 在 github release 哪里下载的新版里面如果启用了 Tracking Clipboard 还会 override 上面 scan popup 的行为被
* 主界面上只有一个 enable popup 的按钮，如果用户选择 “Send to main window”，他需要从 Tray 哪里启用 Tracking Clipboard。而且如果他喜欢用主界面，很可能根本就没有 Tray 来让他启用
* ![image](https://user-images.githubusercontent.com/20123683/202851644-e8d6c1b4-187f-4f9f-a838-6b6663dec485.png) 这个东西唯一的作用应该就是让💡从工具栏里和 tray 上消失，基本没用

---

如果是新用户在这里应该会很迷惑，简化一成这几个变量

#### tray 和主界面

`enableScanning` -> 用同一个 “Enable Scanning” （💡）只要启用就会让 popup 在复制的时候显示

#### 设置里面

* `startWithScanPopupOn` -> 原来的 "Start with popup on"
* `scanToMainWindow` -> 原来的 “Send to main window”

如果是 linux，那就额外有

* `enableClipboardTracking` -> Ctrl+C
* `enableSelectionTracking` -> 划词
  * `showScanFlag` -> 
  * `enableScanPopupModifiers` -> 功能键

这样就清晰了

**Comment by shenlebantongying** [comment]
@binglius 有空的话可以试一下我刚发的 PR 里面的版本，按照下面这样设置就能实现你想要的那种效果。

还有一些问题要解决。已知的一个是 Hotkeys 里面的两个必须开启才能用。

<img src="https://user-images.githubusercontent.com/20123683/202868121-44728b55-3063-4fd6-b727-4d927b126df1.png" width="300"/><img src="https://user-images.githubusercontent.com/20123683/202868664-24a8d7e5-3c09-4f0c-a38e-83c276d6dcfe.png" width="300"/>

demo
![Peek 2022-11-19 14-25](https://user-images.githubusercontent.com/20123683/202868096-21d0dffe-ea6d-4319-8ee5-dbb7dcc1e206.gif)

**Comment by xiaoyifang** [comment]
> 么 Scan popup 那个按钮就没有意义了，而且需要启用 Tracking Clipboard。
> * 在 github release 哪里下载的新版里面如果启用了 Tracking Clipboard 还会 override 上面 scan popup 的行为被

tracking clipboard原则上不应该影响他们，如果影响了，感觉是实现问题。

**Comment by xiaoyifang** [comment]
> 如果是 linux，那就额外有
> 
> * `enableClipboardTracking` -> Ctrl+C

windows下也可以有这个ctrl+C的功能

**Comment by shenlebantongying** [comment]
> windows（mac?）下也可以有这个ctrl+C的功能

我的意思是 win/mac 上只有 Ctrl+C 取词的功能，Tracking Clipboard 和 Enable Scan Popup 基本是重叠的，不需要额外的配置选项来控制是否启用 tracking clipboard

**Comment by binglius** [comment]
好的，我试试看，我以前是同时启用"win"+"Alt"两个键，这两个在一起，用起来非常舒服。

**Comment by binglius** [comment]
测试了下，可以了，我的效率又回来了。。。。：）

**Comment by binglius** [comment]
FYI. 其实一个单词按住控制键，双击选中效率最高，因为 Linux 双击默认选中一个单词。
