### ISSUE TITLE
[Regression] Wiktionary in .zim format does not work correctly

### ISSUE THREAD

**Issue by Immunize2** [xiaoyifang/goldendict#210]
OS: Manjaro Stable (Latest version)
GoldenDict: 20.11.2022 (latest alpha) from AUR
German Wiktionary full version (with pictures) from September 2022.

Problem: GoldenDict shows a string of characters that make it difficult to read the Wiktionary:

![image](https://user-images.githubusercontent.com/111645935/202906979-83573976-cf9d-4ab3-99fa-ae7a962ab5d0.png)

![image](https://user-images.githubusercontent.com/111645935/202907075-46117c54-d0bd-42bb-a5fd-a0b3c414314a.png)

Also, images are not shown properly. Yesterday I saw images correctly using a version of GoldenDict from October 2022. It seems a regression related to the latest commits about .zim format.

**Comment by xiaoyifang** [comment]
ok ,I'll check that.
thanks

**Comment by Immunize2** [comment]
@xiaoyifang   **images are still not shown properly.**

The commit solved one part of the problem, but the issue with images persists:

![grafik](https://user-images.githubusercontent.com/111645935/203167810-75249626-0bd9-4214-a4b0-b7d991ec4020.png)

**Comment by xiaoyifang** [comment]
can you give me the .zim dictionary Link ,I need to take a look.

**Comment by Immunize2** [comment]
> Can you give me the .zim dictionary Link ,I need to take a look.

_German Wiktionary November 2022 (full version) :_ 
 https://download.kiwix.org/zim/wiktionary_de_all_maxi.zim

The German Wikipedia also has the same problem with images. As the full German Wikipedia is very large, you can try this shortened version:

https://download.kiwix.org/zim/wikipedia_de_geography_maxi.zim
(Geography Section only).

**Comment by Immunize2** [comment]
@xiaoyifang   

The lack of images seems not related with the index. After reindexing the problem persists:

![grafik](https://user-images.githubusercontent.com/111645935/203260558-68a046fd-600b-4013-8e5f-85437cc259ed.png)

**Comment by xiaoyifang** [comment]
images can show up now .
But the implementation stills need a little refinement .I'll leave it for a later time.

**Comment by Immunize2** [comment]
@xiaoyifang After your latest commits, images do not show up again !  :(

Seems another regression regarding the .zim format.

![grafik](https://user-images.githubusercontent.com/111645935/203865122-44564f60-c93e-4465-8cbb-4ce3f8f572c3.png)

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/203983050-7e69fecd-3c9d-412c-bec2-fa6eb40bc1a3.png)
works ok on my side.

I suspect that the very dictionary's index should be rebuilt.

**Comment by Immunize2** [comment]
Dictionaries in .zim format now work correctly after re-indexing. I apologize.

Thanks for your great job Xiao ! :D

![grafik](https://user-images.githubusercontent.com/111645935/204058187-6edf206d-fb82-4b3d-b298-3b8077cbe911.png)
