### ISSUE TITLE
`.deb` packaging

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict#211]
The proper way to deliver a `.deb` package is simply don't do it.

Instead, we should ship directly to the sources of all `.deb` distros: Debian.

I think our fork is pretty worthy to replace the original one

*  qtwebkit is dead and unlikely to get updates <https://blogs.gnome.org/mcatanzaro/2022/11/04/stop-using-qtwebkit/>.
    * OpenSUSE stops shipping qtwebkit and they picked up the goldendict of this repo.
* Original repo's owner isn't actively processing issues and PR from other contributors
* We have many enhancements and bug fixes
    * The original repo's changes are merged here
* New users on various forums like it
    * There is no statistics but based on the windows and AUR users, this repo's version is proven

I am not sure what we can do and what will be required. Let's communicate, and summon the Debian developer who maintains goldendict @hosiet

I saw his name in many places before and I am sure he will be helpful.

**Comment by xiaoyifang** [comment]
I think this repo can  keep as a fork such as goldendict-webengine version just like the AUR's doing.
There is no need to replace it ,Let's the final users to choose.

**Comment by xiaoyifang** [comment]
As far as I know,cmakefiles can be used to generate deb package.

**Comment by shenlebantongying** [comment]
Two problems if we build .deb:
* no auto update
* bloat, have to bundle qt (>200mb)

These two problems already exist in the `.appimage` format. There isn't much meaning to building a .deb package from our side.

**Comment by hosiet** [comment]
I believe having it into Debian as `goldendict-webengine` should be okay. I am preparing it under https://salsa.debian.org/byang/goldendict-webengine (which will later be moved to https://salsa.debian.org/debian/goldendict-webengine ). The remaining work is mostly per-file copyright in the source code.

You may find an example of deb package and its source package in the attachment.

[goldendict-webengine_22.11.22.LightSnow.221121.a2e258b3.src.zip](https://github.com/xiaoyifang/goldendict/files/10094324/goldendict-webengine_22.11.22.LightSnow.221121.a2e258b3.src.zip)
[goldendict-webengine_22.11.22.LightSnow.221121.a2e258b3-1~bpo11+1_amd64.deb.zip](https://github.com/xiaoyifang/goldendict/files/10094325/goldendict-webengine_22.11.22.LightSnow.221121.a2e258b3-1.bpo11%2B1_amd64.deb.zip)

**Comment by xiaoyifang** [comment]
> The remaining work is mostly per-file copyright in the source code.

should I do this ?

**Comment by hosiet** [comment]
I believe no more work is needed. It is now prepared, uploaded and queued for final review at https://ftp-master.debian.org/new.html . After the review is finished (and passed), it will appear at https://tracker.debian.org/pkg/goldendict-webengine .

**Comment by shenlebantongying** [comment]
https://github.com/xiaoyifang/goldendict/issues/239#issuecomment-1353585135

**Comment by hosiet** [comment]
Following project renaming, goldendict-ng will be available under the package name of `goldendict-ng` too: https://tracker.debian.org/pkg/goldendict-ng .

The CMake buildsystem is much cleaner than qmake, and thus I am building `goldendict-ng` there using **CMake and Qt6**. The old https://tracker.debian.org/pkg/goldendict-webengine is **kept to be using Qt5**, and I am not planning to drop old `goldendict-webengine` just now.

**Comment by shenlebantongying** [comment]
Thank you for taking care of this `:)`

The `libtiff-dev` & `libao-dev` should be removed from dependency as they are no longer needed.
