### ISSUE TITLE
Technical reasons to use `FFmpeg/libao` instead of `qtmultimedia`?

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict#212]
On linux, Qt5 seems to have only GStreamer.

However, in Qt6 there is a new ffmpeg backend for all platforms (parallel installable on linux), thus I suppose in qt6, qtmultimedia should support all audio formats that ffempeg/libao supports.

https://doc.qt.io/qt-6/qtmultimedia-index.html#target-platform-and-backend-notes
https://github.com/qt/qtmultimedia/tree/dev/src/plugins/multimedia/ffmpeg

Does FFmpeg/libao supports something that qtmultimedia don't support?
When built with Qt6, GD using qtmultimedia is good enough for users?

**Comment by xiaoyifang** [comment]
> However, in Qt6 there is a new ffmpeg backend for all platforms

this was introduced in qt6.4.0 and windows still not have it .

libao is already remove from the gd.

> Does FFmpeg/libao supports something that qtmultimedia don't support?
such as speex format audio 

> When built with Qt6, GD using qtmultimedia is good enough for users?
users can choose to enabled/disabled through `CONFIG+=no_ffmpeg_player` etc

**Comment by shenlebantongying** [comment]
> libao is already removed from the gd.

So remove all mention of libao from README.md?

**Comment by xiaoyifang** [comment]
yes ,that's reasonable.

**Comment by shenlebantongying** [comment]
I think I can just reorganize README a bit, they are all stacked build commands...
