### ISSUE TITLE
The situation of Qt6 on linux distros. Do we need to keep Qt5?

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict#216]
I thought debian only ships LTS versions of Qt, but they actually backported qt6.3 to their current stable.

Qt6.5 is LTS and scheduled around 2023.03.30

For windows & mac, we can control the versions anyway.

Data from https://repology.org for Major distros's Stable releases:

Debian 11 -> 6.3.1, Debian12 will be out January 2023
Fedora 37 -> 6.3.1
ubuntu 22.04 -> 6.2 (? if there is a 22.04.1 they will update to higher version?)
openSUSE leap 15.04 -> 6.2

Do we have serious bugs with 6.2? If we can find some workarounds, we may require Qt6.2 (LTS)+ for linux users and just stop caring Qt5?

For older distro users, we should make make a "last-qt5" release and setup a branch then stop supporting qt5.  

If we get Qt5 wayland related bug reports, I don't know if there is a meaning to fix or find a workaround, because qt5.15 on linux is in maintenance mode in KDE project and they only allow a list of people to touch it, so there will be almost no updates.

[![Packaging status](https://repology.org/badge/vertical-allrepos/qt.svg)](https://repology.org/project/qt/versions)

**Comment by xiaoyifang** [comment]
> Do we have serious bugs with 6.2

I remember there are .

In my memory ,no qt6 version has reached the production level until now.

**Comment by xiaoyifang** [comment]
> we may require Qt6.2 (LTS)+ for linux users and just stop caring Qt5?

qt 5 and qt6 currently shared the most same codebase with only minor code changes.  Let the users to choose qt6 or qt5.
They can compile there goldendict with their favorite qt version

**Comment by shenlebantongying** [comment]
Sure, let's wait for next qt release.
