### ISSUE TITLE
[Feature Request] 是否有一种类似于goldendict://...的链接可以用来查词？

### ISSUE THREAD

**Issue by WritingWithFire** [xiaoyifang/goldendict#221]
- 为什么会有这种问题？
  - 我不清楚xiaoyifang大大有没有用过[Obsidian](https://obsidian.md/)，这是一款非常牛逼的笔记软件，其中有个功能叫做[Obsidian URI](https://help.obsidian.md/Advanced+topics/Using+obsidian+URI)，就是支持一种`obsidian://.......`格式的链接，你在电脑上任意位置点击这个链接就可以打开Obsidian并且自动定位到你在链接中指定的笔记位置。熟练使用的话可以玩出花来，比如使用这种链接与Anki联动，复习的时候随时跳转到笔记的出处以复习上下文
![image](https://user-images.githubusercontent.com/66851780/203542106-e3050ee1-c50e-4fbd-9378-3bb40b465a86.png)
  - 隔壁欧陆词典也有这种玩法，链接语法相同`eudic://.......`，同样可以镶嵌到各种你想得到的地方，比如镶嵌到anki的模板里
``` html
<a onclick="event.stopPropagation();" href="eudic://x-callback-url/searchword?word={{text:Word}}&x-success=anki://">
<img class="icon" src="_goldendict.png"></a>
```
- 所以gd有没有这种链接？
---
- 如果是GD的这种链接，不妨点击之后产生和ctrl+c+c一样的效果，也就是弹出悬浮窗

**Comment by shenlebantongying** [comment]
URL scheme 在三个平台的实现是不一样的，要做的工作量会不小，不过 Linux 应该可以最先实现

windows 要改注册表
https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767914(v=vs.85)

linux 要创建一个文件
https://wiki.archlinux.org/title/XDG_MIME_Applications

Apple 要把一个处理函数嵌入到应用里面去
https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app

**Comment by WritingWithFire** [comment]
我发现了一个更好玩的，potplayer可以通过点击字幕中的单词进行搜索，而且这个搜索链接是可以自己定的
![image](https://user-images.githubusercontent.com/66851780/203553240-7fa78677-6fc7-4d81-b048-799851b6a7bb.png)
于是就可以设置成这样
![image](https://user-images.githubusercontent.com/66851780/203554379-b77c4332-41fc-49f2-aa0c-9a8593a00eb4.png)
然后点击字幕就可以瞬间查词啦

**Comment by shenlebantongying** [comment]
好像也不难，在 `HKEY_CLASSES_ROOT` 下面添加一个 key 就可以，

![image](https://user-images.githubusercontent.com/20123683/203561126-d225424a-d9ef-40d4-b6e2-d2304975177e.png)

![image](https://user-images.githubusercontent.com/20123683/203560527-180d55a8-cce0-4cbe-b2e6-120638bc3988.png)

问题是 `goldendict://word` 会包含整个 url，需要判断一下 `://` 的存在，然后做额外的处理

**Comment by WritingWithFire** [comment]
大佬，有没有什么办法可以让他像弹出悬浮窗那样显示，而不是发送到主程序里面

**Comment by shenlebantongying** [comment]
Disable the 2nd option.
<img width="300" src="https://github.com/user-attachments/assets/d97cec7b-fffd-4875-a3b8-437986576f8c">
