### ISSUE TITLE
[Bug] 无法发音

### ISSUE THREAD

**Issue by WritingWithFire** [xiaoyifang/goldendict#222]
The Little Dict附带的发音库无法发音，点击无反应
![image](https://user-images.githubusercontent.com/66851780/203706289-65c7ee61-82d6-4de2-aba1-3ec5b52524b1.png)

---
Goldendict 22.11.22-LightSnow.89c84421 on Wed Nov 23 01:19:14 2022
windows winnt 10.0.19044 Qt 6.4.1 x86_64-little_endian-llp64
Visual C++ Compiler: 192930146
Flags: MAKE_ZIM_SUPPORT MAKE_EXTRA_TIFF_HANDLER MAKE_CHINESE_CONVERSION_SUPPORT

Edition	Windows 10 Pro
Version	21H2
OS build	19044.2251
Experience	Windows Feature Experience Pack 120.2212.4180.0

**Comment by WritingWithFire** [comment]
Goldendict 22.11.22-LightSnow.3c0b6a91 on Wed Nov 23 23:19:06 2022
windows winnt 10.0.19044 Qt 6.3.2 x86_64-little_endian-llp64
Visual C++ Compiler: 192930146
Flags: MAKE_ZIM_SUPPORT MAKE_EXTRA_TIFF_HANDLER MAKE_CHINESE_CONVERSION_SUPPORT

这个版本是可用的

**Comment by xiaoyifang** [comment]
多谢。
是qt的bug
https://bugreports.qt.io/browse/QTBUG-108669

我先把qt6.4.1的windows版本移除。
