### ISSUE TITLE
All indexes need to be rebuilt after moving the dictionary path

### ISSUE THREAD

**Issue by WritingWithFire** [xiaoyifang/goldendict#223]
as the title said, I changed my entire dict path. then... gd rebuild the whole index of all dicts. the process looks very silly.
is there any way to solve this problem?

**Comment by xiaoyifang** [comment]
portable version seems a rescue.

**Comment by WritingWithFire** [comment]
I do use the portable version, the one unzipped from the .zip file of the release page. but the config folder is located in `%HOMEPATH%\Application Data\GoldenDict` automatically, maybe not portable enough.

**Comment by xiaoyifang** [comment]
goldendict portable mode:
create `portable` and `content` folder alongside with goldendict.exe. and put all your dictionaries into the `content` folder

But if there is not too much dictionaries ,just let the gd rebuild the index,it should not takes too much time to rebuild.
