### ISSUE TITLE
Error display sound button on some Mdict file

### ISSUE THREAD

**Issue by zenfas** [xiaoyifang/goldendict#226]
I download some dictionaries from downloads.freemdict.com, but display sound button not display

Ex: [https://downloads.freemdict.com/uploads/tempertemper's%20collection/MD~/Merriam-Websters/Merriam-Webster%20Dictionary%20Online%20%282020%29/](https://downloads.freemdict.com/uploads/tempertemper's%20collection/MD~/Merriam-Websters/Merriam-Webster%20Dictionary%20Online%20%282020%29/)

![image](https://user-images.githubusercontent.com/66258788/204094693-ae106268-af38-4c39-a855-14e33e5c7a1c.png)

**Comment by xiaoyifang** [comment]
What's the gd's version?

**Comment by zenfas** [comment]
Windows version GoldenDict-v22.11.24-alpha.221124.ff5d82d7

**Comment by zenfas** [comment]
the same for old verion on Windows

**Comment by xiaoyifang** [comment]
have you download all the mdd files

**Comment by zenfas** [comment]
I already downloaded:

![image](https://user-images.githubusercontent.com/66258788/204120489-c872d0ea-1d9f-498f-afd5-dceed3cd89d6.png)

![image](https://user-images.githubusercontent.com/66258788/204120508-f76de869-f20d-4046-ae40-cca0c90a9982.png)

Wordnet 3.1 display not correct also: https://downloads.freemdict.com/uploads/tempertemper's%20collection/MD~/X.Other%20English%20Dictionaries/WordNet/Wordnet/
![image](https://user-images.githubusercontent.com/66258788/204120535-0741333c-59ad-411f-92d5-ede30112bb7f.png)

![image](https://user-images.githubusercontent.com/66258788/204120549-114b51c7-f437-49b7-9311-250ecf494c51.png)

**Comment by xiaoyifang** [comment]
> I already downloaded:

the original mw dict has 4 files.  you only got 2.

as to the wordnet3.1 ,it is more likely dictionary making problem.

**Comment by zenfas** [comment]
Just display icon error, I click on this location, app still read

**Comment by zenfas** [comment]
I renamed 2 css and js file the same name mdx mdd file still got this error

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/204120903-f9e78c9d-679d-41ac-a74d-f86c2d3147c6.png)

**Comment by zenfas** [comment]
WN on Eudic is normal

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/204121050-658beb09-c4a3-4fc8-aeba-6819f1d94f35.png)


> I renamed 2 css and js file the same name mdx mdd file still got this error

do not rename

**Comment by zenfas** [comment]
Ohh, you're correct. Thank you.
