### ISSUE TITLE
[rfc] `shared_ptr` is a drop-in modernization of `sptr.hh` 

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict#228]
The idea and the APIs are pretty much the same. The similarity may imply the original author probably just copied the original version of boost.

Semantically, they both exist to ensure a single data chunk can be shared between all references.

Technically, they both hold an exact pointer and a reference counter.

Functions provided by `sptr.hh` is a subset of `shared_ptr`! (the count() never got used actually). We mostly used get() and reset() which are the same.

`tr1::` in the comment was the proposal that introduce the shared_ptr. 
https://github.com/xiaoyifang/goldendict/blob/53d443357bf8e6aec4555381a7eac86f8a11be90/sptr.hh#L7

I think we can replace sptr with shared_ptr.

I refactored `articleview.cc` and it works pretty well.

To refactor this, the main issue is just wrapping the return:

```
sptr <something> X= new something()
```
into

```
std::shared_ptr<sth> X = std::shared_ptr<sth>(new sth());
```

This helper probably helps.
```
template<T>
using sptr<T> = using shared_ptr<T>;
```

Main problems:

sptr.hh doesn't work with multi threads.
sptr.hh isn't standard

References

https://en.cppreference.com/w/cpp/memory/shared_ptr

https://learn.microsoft.com/en-us/cpp/standard-library/shared-ptr-class?view=msvc-170

https://learn.microsoft.com/en-us/cpp/cpp/how-to-create-and-use-shared-ptr-instances?view=msvc-170

https://www.boost.org/doc/libs/1_80_0/libs/smart_ptr/doc/html/smart_ptr.html#shared_ptr

**Comment by xiaoyifang** [comment]
sptr<> has offered some implict conversions which shared_ptr has not.

>`
template<T>
using sptr<T> = using shared_ptr<T>;
`

this method should not work . A little more work needs to be done .


I have tried to extend shard_ptr before ,see commit https://github.com/xiaoyifang/goldendict/commit/6318366a105bc8b9b5e79fd3c5cfba62618142cb

I forgot why I reverted it .

**Comment by xiaoyifang** [comment]
in order to reduce the modification work.

Is it possible to wrap shared_ptr and offer a new sptr<> ?

**Comment by shenlebantongying** [comment]
Copied from https://en.cppreference.com/w/cpp/memory/shared_ptr

> When shared_ptr is created by calling std::make_shared, the memory for both the control block and the managed object is created with a single allocation.

Based on my experiment here,`make_shared` only costs ~10 instructions, and `shared_ptr(new obj())` costs 4x instructions.

https://godbolt.org/z/TGxhcjaT4

(colour on left maps what each line compiled into)

We will get a slight performance improvement by using `make_shared` at `return` explicitly; this is probably a better approach.
