### ISSUE TITLE
5mb memory swing by just putting cursor on search box

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict#232]
Putting the cursor/focus on the search box and doing nothing will cause memory spikes in a _roughly_ fixed frequency.

I have not yet investigated what it is.

Plot: focus search box -> unfocus -> focus again -> unfocus again

![image](https://user-images.githubusercontent.com/20123683/204373332-b6be2ea4-362b-41e6-943d-d4bc13d38af6.png)

**Comment by xiaoyifang** [comment]
some qt paint issue？

**Comment by shenlebantongying** [comment]
> some qt paint issue？

I am not sure, but I think your guess is pretty close!

I used a better mem profiler https://github.com/koute/bytehound

The object is exactly 4.19 M for every iteration and there is a call to QImageData::create/QImageData::~QImageData

```
Allocated at:
#0 [goldendict] _start [start.S:115]
#2 [libc.so.6] 0x00007F2310A3C28F
#3 [goldendict] main [main.cc:439]
#9 [libglib-2.0.so.0.7400.1] g_main_context_dispatch
#10 [libQt6Core.so.6.4.1] 0x00007F231294F527
#11 [libQt6Core.so.6.4.1] QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)
#15 [libQt6Widgets.so.6.4.1] QWidgetRepaintManager::paintAndFlush()
#16 [libQt6Widgets.so.6.4.1] QWidgetRepaintManager::flush()
#18 [libQt6XcbQpa.so.6.4.1] 0x00007F22E452324B
#19 [libQt6Gui.so.6.4.1] QPlatformBackingStore::rhiFlush(QWindow*, double, QRegion const&, QPoint const&, QPlatformTextureList*, bool)
#20 [libQt6Gui.so.6.4.1] 0x00007F2312E136C5
#21 [libQt6Gui.so.6.4.1] 0x00007F2312E074E3
#26 [libQt6Gui.so.6.4.1] QImageData::create(QSize const&, QImage::Format)
#27 [libbytehound.so] malloc [api.rs:294]

Deallocated at:
#0 [goldendict] _start [start.S:115]
#2 [libc.so.6] 0x00007F2310A3C28F
#3 [goldendict] main [main.cc:439]
#9 [libglib-2.0.so.0.7400.1] g_main_context_dispatch
#10 [libQt6Core.so.6.4.1] 0x00007F231294F527
#11 [libQt6Core.so.6.4.1] QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)
#15 [libQt6Widgets.so.6.4.1] QWidgetRepaintManager::paintAndFlush()
#16 [libQt6Widgets.so.6.4.1] QWidgetRepaintManager::flush()
#18 [libQt6XcbQpa.so.6.4.1] 0x00007F22E452324B
#21 [libQt6Gui.so.6.4.1] QRhiCommandBuffer::beginPass(QRhiRenderTarget*, QColor const&, QRhiDepthStencilClearValue const&, QRhiResourceUpdateBatch*, QFlags<QRhiCommandBuffer::BeginPassFlag>)
#22 [libQt6Gui.so.6.4.1] 0x00007F2313088C43
#23 [libQt6Gui.so.6.4.1] 0x00007F23132263EF
#25 [libQt6Gui.so.6.4.1] QImageData::~QImageData()
#26 [libbytehound.so] free [api.rs:419]
```

**Comment by shenlebantongying** [comment]
The memory swing comes from here:

https://github.com/xiaoyifang/goldendict/blob/2404a5d34118b47eb3b8ca6fe0828305f697c1c3/translatebox.cc#L117-L128

Cursor blinking will lead to repaint event at here. Disable cursor blinking will stop the memory swing.

The problem should be on `painter.drawPixmap(pixmapRect, m_pixmap);`. I think the problem is that we resized the pixmap during paint event. For every cursor blinking, we are recreating a resized pixmap? The fix should be cache a scaled the pixmap and use an existing pixmap rather than resize via drawPixmap(pixmapRect,m_pixmap)?

https://github.com/xiaoyifang/goldendict/blob/2404a5d34118b47eb3b8ca6fe0828305f697c1c3/extlineedit.cc#L160-L176

**Comment by shenlebantongying** [comment]
https://forum.qt.io/post/750062
