### ISSUE TITLE
GoldenDict built from source didn't work on ubuntu 22.04

### ISSUE THREAD

**Issue by Canvis-Me** [xiaoyifang/goldendict#238]
The webengine backend goldendict cannot render main frame on ubuntu.

![20221204_21h00m09s_grim](https://user-images.githubusercontent.com/55122738/205492018-2fa45ef0-7ed4-4d1a-9d0d-ed527f1aed56.png)

The terminal output is:
[goldendict_not_render.txt](https://github.com/xiaoyifang/goldendict/files/10148543/goldendict_not_render.txt)

**Comment by xiaoyifang** [comment]
> QProcess: Destroyed while process ("trans") is still running.

seems you have a program dictionary ,try to disable it and try again.

**Comment by Canvis-Me** [comment]
It works now, thanks. It was the trans program missing issue, but it worked on webkit backend goldendict.

**Comment by xiaoyifang** [comment]
maybe in future , a timeout can be introduced into the gd.

**Comment by Canvis-Me** [comment]
OK, thanks for your work!
