### ISSUE TITLE
Some CC-BY-SA-2.0 licensed files rejected in Debian software package review

### ISSUE THREAD

**Issue by hosiet** [xiaoyifang/goldendict#239]
Hi,

I received a rejection notice from Debian FTP Masters as a result of goldendict-webengine package review:

> as the CC-2.0 license is not compatible with DFSG, please remove all svg files under this license from the source tarball.

I believe it refers to SVG files distributed under CC-BY-SA-2.0 license:

```
-> % grep -r '2\.0' | grep license | grep by-sa
icon32_zoomout.svg:           rdf:resource="http://creativecommons.org/licenses/by-sa/2.0/" />
icon32_zoomout.svg:         rdf:about="http://creativecommons.org/licenses/by-sa/2.0/">
icon32_zoombase.svg:           rdf:resource="http://creativecommons.org/licenses/by-sa/2.0/" />
icon32_zoombase.svg:         rdf:about="http://creativecommons.org/licenses/by-sa/2.0/">
reload.svg:           rdf:resource="http://creativecommons.org/licenses/by-sa/2.0/" />
reload.svg:         rdf:about="http://creativecommons.org/licenses/by-sa/2.0/">
advanced.svg:           rdf:resource="http://creativecommons.org/licenses/by-sa/2.0/" />
advanced.svg:         rdf:about="http://creativecommons.org/licenses/by-sa/2.0/">
icon32_zoomin.svg:           rdf:resource="http://creativecommons.org/licenses/by-sa/2.0/" />
icon32_zoomin.svg:         rdf:about="http://creativecommons.org/licenses/by-sa/2.0/">
```

According to [debian-legal guideline](https://wiki.debian.org/DFSGLicenses#Creative_Commons_Attribution_1.0_Generic_.28CC_BY_1.0.29), CC-BY-SA-2.0 license is not considered compatible with Debian. Newer CC licenses should be okay (as indicated in that webpage). Could you consider replacing these files with icons from other themes with a compatible license? Let me know if you have any comments Thanks!

**Comment by xiaoyifang** [comment]
ok, I'll try to replace them.

**Comment by xiaoyifang** [comment]
the icons has been replaced with LGPL icons

**Comment by xiaoyifang** [comment]
@hosiet let me know ,if any new issue has been found.

**Comment by hosiet** [comment]
What is the origin of https://github.com/xiaoyifang/goldendict/blob/90c1dbb8b9b597493ad07d02604632d2fc741d5f/icons/book.svg ? I noticed that it was added 11 months ago but without related git commit comments or embedded copyright notice.

**Comment by shenlebantongying** [comment]
It is the icon of foliate.

https://github.com/johnfactotum/foliate

**Comment by xiaoyifang** [comment]
https://github.com/goldendict/goldendict/issues/1441

**Comment by xiaoyifang** [comment]
complemented  https://github.com/xiaoyifang/goldendict/commit/55d13305caa40e7816eae73b32684c3a4452d89b

**Comment by hosiet** [comment]
I believe no other changes are needed. The package itself just got accepted into Debian, and I will make sure it enters the upcoming Debian 12 and Ubuntu 23.04+ later.

**Comment by thangisme** [comment]
> I believe no other changes are needed. The package itself just got accepted into Debian, and I will make sure it enters the upcoming Debian 12 and Ubuntu 23.04+ later.

Sorry for the noobs question. So, How do I official install it now? I tried installing the deb and got a bunch of errors
```
Selecting previously unselected package goldendict-webengine.
(Reading database ... 139644 files and directories currently installed.)
Preparing to unpack goldendict-webengine_22.11.22.LightSnow.221121.a2e258b3-1~bpo11+1_amd64.deb ...
Unpacking goldendict-webengine (22.11.22.LightSnow.221121.a2e258b3-1~bpo11+1) ...
dpkg: dependency problems prevent configuration of goldendict-webengine:
 goldendict-webengine depends on libeb16 (>= 4.4.3); however:
  Package libeb16 is not installed.
 goldendict-webengine depends on libopencc1.1 (>= 1.1.1+git20200624+ds2); however:
  Package libopencc1.1 is not installed.
 goldendict-webengine depends on libqt5core5a (>= 5.15.1); however:
  Version of libqt5core5a:amd64 on system is 5.12.8+dfsg-0ubuntu1.
 goldendict-webengine depends on libqt5gui5 (>= 5.14.1) | libqt5gui5-gles (>= 5.14.1); however:
  Version of libqt5gui5:amd64 on system is 5.12.8+dfsg-0ubuntu1.
  Package libqt5gui5-gles is not installed.
 goldendict-webengine depends on libqt5help5 (>= 5.15.1); however:
  Package libqt5help5 is not installed.
 goldendict-webengine depends on libqt5network5 (>= 5.15.1); however:
  Version of libqt5network5:amd64 on system is 5.12.8+dfsg-0ubuntu1.
 goldendict-webengine depends on libqt5webenginewidgets5 (>= 5.14.1); however:
  Version of libqt5webenginewidgets5:amd64 on system is 5.12.8+dfsg-0ubuntu1.1.
 goldendict-webengine depends on libqt5widgets5 (>= 5.15.1); however:
  Version of libqt5widgets5:amd64 on system is 5.12.8+dfsg-0ubuntu1.

dpkg: error processing package goldendict-webengine (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu2) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
 goldendict-webengine
```
I'm on Ubuntu 20

**Comment by shenlebantongying** [comment]
The binary package you grabbed is built for ubuntu 23.04. Installation like this will break your system.

You should download the `.AppImage` from Github's Releases, or compile it from the source. @thangisme 

If you have problems, please open a new issue.
