### ISSUE TITLE
使用在线网页词典跳转异常

### ISSUE THREAD

**Issue by hoochanlon** [xiaoyifang/goldendict#244]
问题：https://forum.freemdict.com/t/topic/11495/1851 ，求解决。

**Comment by xiaoyifang** [comment]
应该是缺少样式。检查下你下载的词典文件，最好把一个词典的所有文件放在一个单独的文件夹。

**Comment by hoochanlon** [comment]
搞不定，我换了的辞典了。另外就是软件的预设的网站查询不好用，包括我自己用 https://tio.freemdict.com/japi?key=%s 也不行...即便换成utf-8也是乱码。只做离线辞典，软件还是相当可以的。

**Comment by xiaoyifang** [comment]
> https://tio.freemdict.com/japi?key=%s

怎么配置的？如果是上面的配置，配置错了。 https://tio.freemdict.com/japi?key=%GDWORD%

**Comment by xiaoyifang** [comment]
你搜索的是哪个词？

**Comment by xiaoyifang** [comment]
从搜索栏看，你搜索的是   Protocol "" is unknown  这个词 ？

**Comment by hoochanlon** [comment]
都差不多的....


<img width="774" alt="截屏2022-12-06 21 48 03" src="https://user-images.githubusercontent.com/35732922/205929519-8e97797a-9c8e-432a-921f-249ec4e7059c.png">

**Comment by xiaoyifang** [comment]
有点奇怪，暂时没重现出来。先留存吧

**Comment by hoochanlon** [comment]
你的不会这样吗？你现在用的是多少版本的辞典？

2022年12月7日 09:04，xiaoyifang ***@***.***> 写道：



有点奇怪，暂时没重现出来。先留存吧

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/208233142-cdfcd82d-4718-45ef-9443-2532e2a155ff.png)

use the latest version and try to install openssl manualy 
`homebrew install openssl@1.1`

**Comment by hoochanlon** [comment]
我试下吧，我现在是macOS13.1，新系统搞不好又不行。

**Comment by hoochanlon** [comment]
可以使用了，但编码出了问题，我试用了：%GDUTF8%、%GDSHIFTJIS%、%GDISO2022-JP%、%GDEUC%、%GDEUC-JP%。还是乱码...
<img width="1021" alt="截屏2022-12-18 09 36 31" src="https://user-images.githubusercontent.com/35732922/208274214-4c10c314-63fe-4e96-a2a1-296964a05eed.png">

**Comment by xiaoyifang** [comment]
%GDWORD%用过了吗

**Comment by xiaoyifang** [comment]
原则上%GDWORD%就可以了，其他的在现代的网站上应该都不需要的。
如果%GDWORD%也失败了，只能暂时放一放了，
可能跟conent-encoding 有关。

你网站词典配置的地方，截个图看下。

**Comment by hoochanlon** [comment]
<img width="1056" alt="截屏2022-12-18 10 01 04" src="https://user-images.githubusercontent.com/35732922/208276160-bb774788-c251-4e16-a907-10abc570ea27.png">

<img width="1056" alt="截屏2022-12-18 10 00 28" src="https://user-images.githubusercontent.com/35732922/208276163-eee88592-079a-4759-a10d-38600eb33fde.png">

**Comment by hoochanlon** [comment]
没什么办法的话，那我重开一个issue，这个issue就现关了，我定向重开的issue上去。

**Comment by xiaoyifang** [comment]
ok
