### ISSUE TITLE
Dictionary headwords

### ISSUE THREAD

**Issue by Eosphorus** [xiaoyifang/goldendict#249]
Is it just me or has anybody else noticed that sorting in the headwords window is kind of messed up.  Thing is it's not from A to Z, it's more like an endless loop, more or less randomly displaying the dictionary's entries.  This really should be fixed. With this flaw it's hard to create new dictionaries when you can't see whether all entries are there.
Thanks for reading.

**Comment by xiaoyifang** [comment]
actually this is a feature.
currently the headwords are loaded in batch to avoid performance issue when dictiobary has too many headwords such as 6000000.

the original version can not handle such case.


if you want the whole headwords ，you can export to a file. the file will hold all the headword

**Comment by Eosphorus** [comment]
I see. Not a bug but a feature. Where have I heard that before (just kidding). Ok, I exported the list as you said and opened it in an editor. There the headwords are still not sorted in an A to Z fashion. 
"duopoly
option seller
option right
Department of Correction
repugnancy
shyster"

Of course now I can have the editor sort them alphabetically. But for one, I don't get the same number of headwords here, in this case 74,036 in GoldenDict vs. 66168 in my editor, for another it's a tad cumbersome.
Don't get me wrong. I'm all for speeding things up but this headword list should be - at least in some way - in alphabetic order to be useful (for me that is).

Apart from all that. Thanks for working on and improving this lovely app!

**Comment by xiaoyifang** [comment]
> in this case 74,036 in GoldenDict vs. 66168 in my editor

what's your dictionary's format? I guess the 74036 is written in the dictionary's metadata while 66168 is the actual number.





> now I can have the editor sort them alphabetically

this is a way ;-).

**Comment by xiaoyifang** [comment]
fixed
