### ISSUE TITLE
Installer Version?

### ISSUE THREAD

**Issue by loyukfai** [xiaoyifang/goldendict#25]
Would you make an installer version as well?

Cheers.

**Comment by xiaoyifang** [comment]
with nsis ,you can convert the zip to exe .

I do not want to make windows installer for now ,as I do not find the  a scriptable way to do this and handle it in the github action workflow.

**Comment by loyukfai** [comment]
Understood. Perhaps leave it on the todo list for a future consideration?

Cheers.

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/168117334-4fd4ce35-314b-4bf9-9cc4-f62d78066736.png)
