### ISSUE TITLE
[Bug] Search column overlaps dictionary results (regression)

### ISSUE THREAD

**Issue by Immunize2** [xiaoyifang/goldendict#251]
**OS:** Manjaro KDE (latest stable version)
**GoldenDict Version:** Latest from AUR repository

The "Search column" overlaps with dictionary results. In other words, when the search column is activated the dictionary definitions cannot be seen properly:

![grafik](https://user-images.githubusercontent.com/111645935/206785738-b08e970a-4f51-43a7-b6d3-c35ca5bdb68a.png)

I noticed the issue a few days ago. It should be related to commits made during November or December.

With this bug, the _“search column”_ becomes unusable. That feature is useful for languages which are richly inflected as German.

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/206820768-9323d994-5e0e-4ab4-a37f-3317f2715913.png)

the search column is dragable , do you accidently drag it out of the place?

**Comment by Immunize2** [comment]
> do you accidently drag it out of the place?
_That was the “issue”. Sorry Xiao. I apologize._   Thanks for your patience and hard work !
