### ISSUE TITLE
The dictionary group in the version of QT6.2.3 will be Chaotic

### ISSUE THREAD

**Issue by liuchanghuaX1** [xiaoyifang/goldendict#26]
The dictionary group in the version of QT6.2.3 will be Chaotic. And it can't be rearrange.
![image](https://user-images.githubusercontent.com/40064819/158182712-a0e3f2c4-94a5-4029-b36a-487c51067999.png)
![image](https://user-images.githubusercontent.com/40064819/158182932-47e8859e-4d31-4b4d-b3df-5bcfec88814e.png)

**Comment by xiaoyifang** [comment]
should be fixed in the new release.
have a try.
