### ISSUE TITLE
help wanted on refreshing example sentences in vocabulary.com

### ISSUE THREAD

**Issue by ausonD** [xiaoyifang/goldendict#260]
It seems a lasting problem failing to refresh example sentence in vocabulary.com by clicking "next", if the dictionary was not in the first order.

Disable some other dictionaries or put it in the first place might help but lousy.

Not happen in eudic.

the dictionary file is attached here.
链接：https://pan.baidu.com/s/180ozDDJjUQHQckNotCsXeQ?pwd=1234 
提取码：1234 

Thank you for your reading.

**Comment by xiaoyifang** [comment]
press F12 to open the devtool ,and investigate the event of  button `next`.
I guess it was affected by other dictionaries' js.

**Comment by ausonD** [comment]
Thanks for your reply.
I checked the code. Indeed, the bottom "next" and "prev" are controlled by a js file.(in the purple area)

Previously, the link order is almost at the end of the code.
So I tried to put it to the start and renamed the js file.

But the problem still remains.

Sometimes, the dict is even affected by some dicts without js file.
It seems that all dictionaries are parallel in html structure. 

So could you please give me some clues on solving this problem or in which circumstance, will a dict be affected by other dicts?

![20221217_193520](https://user-images.githubusercontent.com/107112623/208240324-6c8ce2a3-49d9-47bd-9451-253b4b5fd808.png)
![20221217，19 36 29](https://user-images.githubusercontent.com/107112623/208240325-98184f17-9509-4c02-a9a9-f19d3ea24d27.jpg)

**Comment by ausonD** [comment]
I'm not sure if "event" means this
![20221217_195758](https://user-images.githubusercontent.com/107112623/208240756-62e0bd1c-0dcd-47e9-8148-219174b03c4e.png)

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/208241666-bcbaba18-ccaa-4a19-bfa1-80d1879703eb.png)

**Comment by ausonD** [comment]
![20221217，20 42 40](https://user-images.githubusercontent.com/107112623/208242617-cc32b695-597e-4a6a-9b54-7943ff5132dd.jpg)
![20221217，20 48 48](https://user-images.githubusercontent.com/107112623/208242623-034a31d6-6a03-472b-bf01-3ed649678422.jpg)

**Comment by ausonD** [comment]
maybe a collison between js files?
It seems that js files apply to the whole html.

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/208275932-a7239a40-bffa-4f94-b87e-4962006b5e8a.png)

**Comment by ausonD** [comment]
not solved, maybe i should put it in the first order hhh.
anyhow, thank you so much for your help.

**Comment by shenlebantongying** [comment]
https://github.com/xiaoyifang/goldendict/blob/021645ffc64ba237023e3a90e7af6d63359fab99/article_maker.cc#L569

The thing after `gdfrom` is dictID.

@ausonD I think you have to figure out which dict is inferencing the webpage. To know which dict has this id `808f7b.....`, you have to right-click the dict icons one by one.

![image](https://user-images.githubusercontent.com/20123683/208357446-46340cf4-7db4-4c98-9ba1-a8314f33509c.png)

---

js inside iframes shouldn't be inferencing with each other. This kind of bug doesn't make sense. You should probably share the dict in question and let's see what js code executed would escalate to other iframes.

**Comment by ausonD** [comment]
@shenlebantongying
I just received an email seemingly you asked me to share all dicts that cause the problem. Here are them. Thank you for your reply.

808f7b is just from the dictionary in bug itself.

链接：https://pan.baidu.com/s/1AMR7laObLpMXAWcT3RJ5rg?pwd=1234 
提取码：1234 

链接：https://pan.baidu.com/s/1jAiBkfrm-KBYFG7ZkmBd8Q?pwd=1234 
提取码：1234 

链接：https://pan.baidu.com/s/1I81jMCWxODjFlfGix6LTIg?pwd=1234 
提取码：1234 

it functions well when it appears as the first dictionary.
just put "vocabulary.com" into the last order.
and you could disable other dictionaries one by one, different dictionaries cause bugs in different word items.
Maybe it is just a problem caused by the mdx file.........
but it works well in eudic.........
So i'm a little curious about this.

Once agian, thanks both of you replying and helping me.

**Comment by shenlebantongying** [comment]
For the record, the vocabulary.com mdx file downloaded from here also suffers the same problem.

Putting any other mdx dict before them will cause their `next` button to lose functionality.

https://downloads.freemdict.com/100G_Super_Big_Collection/%E8%8B%B1%E8%AF%AD/%E6%99%AE%E9%80%9A%E8%AF%8D%E5%85%B8/[%E8%8B%B1-%E8%8B%B1]/Vocabulary.com%20Dictionary%20v3%2C%2016-4-16/

I always thought the dicts are combined via `iframe`, and turn out that only online dicts are iframes. Cannot we just solve this and similar problems by just changing mdict article's container from `div` to `iframe`? Or we can wrap existing `div` with `iframe`.

**Comment by xiaoyifang** [comment]
write javascript carefully can solve this js conflict.   
1. first give your dictionary(mdx) a special html container ,
2. write your js on that container ,such as `$(container).click("element",function)`

**Comment by ausonD** [comment]
您的邮件已收到，谢谢！Sincerely Best wishes & kind regards Deng
