### ISSUE TITLE
在线日语词典编码存在异常，系统m1 macOS13.1

### ISSUE THREAD

**Issue by hoochanlon** [xiaoyifang/goldendict#261]
现象：[#244 ](https://github.com/xiaoyifang/goldendict/issues/244)

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/issues/262

**Comment by bgc2017** [comment]
和GD没有关系，和编码也没有关系。把在线词典重新命名，不要选作为链接就可以了。

<img width="958" alt="1" src="https://user-images.githubusercontent.com/45348499/208811962-b83caeb2-da02-46a5-b934-693ed7879a3c.png">

**Comment by hoochanlon** [comment]
看一下你的设置，我不太会操作

**Comment by hoochanlon** [comment]
我知道了

<img width="1179" alt="截屏2022-12-21 11 37 37" src="https://user-images.githubusercontent.com/35732922/208815983-8a46a669-875c-4d17-9390-f970ea01bb3c.png">
