### ISSUE TITLE
[feature] Dark article view through project darkreader.

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict#269]
We have UI's dark mode but article view is still light background.

Inverting colours for existing dictionaries seems to be an impossible job. We cannot make sure there are no glitches.

This browser extension has pretty high-quality colour inverting.

https://github.com/darkreader/darkreader

They also published a single js file for website use

https://www.jsdelivr.com/package/npm/darkreader

This is what I get by simply copying the entire [darkreader.js](https://cdn.jsdelivr.net/npm/darkreader@4.9.58/darkreader.js) to debug console, then just run this function

Brainlessly nice.

```
DarkReader.enable({
    brightness: 100,
    contrast: 90,
    sepia: 10
});

```

![image](https://user-images.githubusercontent.com/20123683/209293965-aaa2fe7f-ed05-48b4-84c2-5ed7a8c502a2.png)

**Comment by xiaoyifang** [comment]
looks nice,I'll try to implement it when I have time.
