### ISSUE TITLE
Failure to display images on .zim files

### ISSUE THREAD

**Issue by GPLv3-fan** [xiaoyifang/goldendict#27]
Images of the Wiktionary in .zim format are not shown properly:

![xiaoyifang german wiktionary](https://user-images.githubusercontent.com/58692066/158931510-5e3236f1-452b-4966-ae1e-e8cadf28ab12.png)

 To reproduce: 
Download a Wiktionary/Wikipedia with images on  https://wiki.kiwix.org/wiki/Content_in_all_languages

OS: Manjaro Linux KDE (Latest Stable)
Version: https://aur.archlinux.org/packages/goldendict-webengine-git

![image](https://user-images.githubusercontent.com/58692066/158932075-11e797cb-7fb1-4589-907a-b6f36232f7b8.png)

**Comment by xiaoyifang** [comment]
more likely  dictionary's  issue.

you can use F12 to inspect the image element. 
the original img is more likely small or the css style is wrong.

**Comment by shenlebantongying** [comment]
I downloaded some English `.zim` and works OK for me. Maybe you should mention exactly which one has this problem?
<img src="https://user-images.githubusercontent.com/20123683/158943335-4862da4a-da6c-4460-8e8a-1ef3268bcc95.png" width="200"/>
<img src="https://user-images.githubusercontent.com/20123683/158943425-71109e4c-50bf-4777-8176-d60df23e226d.png" width="200"/>

I think the possible cause is that

Deutsche Wiktionary is using this`|Bild 1=Fuji_apple.jpg|200px|1|''Apples''` to include image which result an image inside `<table>` as in https://de.wiktionary.org/w/index.php?title=Rahmen&action=edit

English Wiktionary is using `[[Image:Apple red delicius flower end.jpg|thumb|A red apple]]` which result an image inside `<div>` as in https://en.wiktionary.org/w/index.php?title=apple&action=edit

Perhaps Deutsche Wiktionary can use some update? Or the tool that convert that wikitionary messed up the `<table>` element?

If the saved HTML as mentioned above works in chrome but not GD, then the issue belong to here.

If it doesn't work, then exported .zim should be blamed.

**Comment by GPLv3-fan** [comment]
Thanks for your kind help. 

The German Wiktionary .zim "seems" to have a problem itself. However, it works perfectly.on "Kiwix" on Android.

 As a concrete example, the images for the word "Rahmen" in German Wiktionary appear properly but on GoldenDict those images are not shown correctly.

The issue affects your improved version of GoldenDict. I guess that also affects the "Official version maintained by @abs62 .

Several months ago I contacted tge "Kiwix Team" by email and they said about GoldenDict and .zim files:

"I'll be honest I had to ask about GoldenDict because I'd never heard of it. Turns out someone here had heard of it not too long ago but did not have time to investigate much. **The only finding so far is that it uses Pylibzim for its own purpose, and thus probably can not fully read all the zim files we produce (as illustrated by the issue you refer to; I don't know about non mediawiki zim files). "**

So, probably GoldenDict just does not support .zim files properly. Maybe could we improve that @Popolechien ?

Thanks for your hard work !

**Comment by GPLv3-fan** [comment]
**NEW FINDING:**   If the German Wiktionary is in a group ALONE, images are shown correctly. 

If it is put on a Group with other dictionaries, there is a misconfiguration and the bug appears. 

On the group there are HTML-based dictionaries and some of them might have a "bad" behaviour affecting the display of other dictionaries:

Check:  https://github.com/goldendict/goldendict/issues/290

http://goldendict.org/forum/viewtopic.php?f=4&t=2091&start=110

The issue of HTML dictionaries affecting global styles was supposed fixed by "Abs62" on 2013 but it still alive ! 
-----------------

On the other hand, the support for .zim files was added on 2013 on GoldenDict and some changes have happened since them on Python "libzim" and/or zim format.

**Comment by xiaoyifang** [comment]
> 2) If it is put on a Group with other dictionaries, there is a misconfiguration and the bug appears.
> 
> On the group there are HTML-based dictionaries (.mdx) and some of them might have a "bad" behaviour affecting the display of other dictionaries:

then it was affected by other dictionary's css style.   dictionary hasn't have  a standard css writing rule. and some dictionary use js to control the style. which is out of gd's ability to support.


> On the other hand, the support for .zim files was added on 2013 on GoldenDict and some changes have happened since them on Python "libzim" and/or zim format.

will investigate in the future ,but I think it has not related to this issue.

**Comment by GPLv3-fan** [comment]
Unfortunately, a single "bad" .mdx dictionary was affecting others (Forvo German Pronunciations: https://forum.freemdict.com/t/topic/7355/7 )

I am very sorry. It was difficult to pinpoint the issue. Thanks to everyone for their valuable help and insights !

**Comment by xiaoyifang** [comment]
> > On the other hand, the support for .zim files was added on 2013 on GoldenDict and some changes have happened since them on Python "libzim" and/or zim format.
> 
> will investigate in the future ,but I think it has not related to this issue.

gd seems do not use any libs to parse the zim format ,it just parse the file itself.

**Comment by data-man** [comment]
> gd seems do not use any libs to parse the zim format ,it just parse the file itself.

Yes. Some time ago I proposed to use [libzim](https://github.com/openzim/libzim/) in GD, but the author doesn't want it.

**Comment by xiaoyifang** [comment]
gd is gpl3.0+ while libzim is gpl2.0 ,will there be any license issue to use the lib.

**Comment by xiaoyifang** [comment]
https://github.com/goldendict/goldendict/issues/914

**Comment by Popolechien** [comment]
> gd is gpl3.0+ while libzim is gpl2.0 ,will there be any license issue to use the lib.

@xiaoyifang Please open a ticket at openzim/libzim but we think that GPL 2.0 is more permissive so this should not be an issue.

**Comment by shenlebantongying** [comment]
Actually they explicitly changed from `GPL2` to `GPL2+`

https://github.com/openzim/libzim/commit/f57bca28217be00587bbcf8e45b40db4e48249da

Plus this chart from gnu.org

https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility

their pervious discussion on this matter

https://github.com/openzim/libzim/issues/30
