### ISSUE TITLE
Perfect dark for linux and mac: remove all explict color for Qt widgets

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict#271]
I think we should remove them entirely.

The original design was to morph Goldendict to look like competing software by styling the entire app.

I found this screenshot on the internet. It was broken since the beginning and is still broken today.

The mac version is unlikely to be fixed by completing this feature. The details on mac are too much.

![image](https://user-images.githubusercontent.com/20123683/209453669-38f443d0-8a80-466e-9050-fa8539e2a66e.png)

----

On Linux, users can use a neither dark nor light background, for example, yellowish-grey, and it looks weird.

![image](https://user-images.githubusercontent.com/20123683/209453875-1676734e-5afd-414c-b35a-6e1f725f6381.png)

  ![image](https://user-images.githubusercontent.com/20123683/209453716-41d77cfa-170f-4a2b-b850-45481813146a.png)  ![image](https://user-images.githubusercontent.com/20123683/209453659-3d2c57f5-996f-4c84-bd0e-9e2e63f28c64.png)

So, I think we should remove explicit colouring qt widgets and let the qt's platform decide.

Also, rename this setting to "Article display style" (only change the style of articles).

![image](https://user-images.githubusercontent.com/20123683/209453901-71c5dade-1418-452c-8f3b-d6af8fd32ad5.png)

**Comment by xiaoyifang** [comment]
which means dark color can not work together with non-default qt styles.

Let's do it.

@shenlebantongying do you have time to work on this?

**Comment by shenlebantongying** [comment]
Yes.

Also, we only have that groupcombobox/searchbox that needs some extra styling. I plan to learn deeper about qt's styling and reimplement it with QStyle as recommended by a lead developer of KDE: https://www.kdab.com/say-no-to-qt-style-sheets/

**Comment by shenlebantongying** [comment]
Those two close icons should be replaced, they are too red.

kde Breeze's close icons are better. The default is grey, and works on both light & dark modes. 

https://github.com/xiaoyifang/goldendict/blob/7d6b6cc47359ea6b0160aa2087ae9f7c157e0399/qt-style.css#L52-L57

![image](https://user-images.githubusercontent.com/20123683/209455800-f6aa43e1-0fc1-4190-973c-b1d9389f653e.png)

![image](https://user-images.githubusercontent.com/20123683/209455962-e6427d7f-a043-419c-86cd-8abde152508d.png)

**Comment by shenlebantongying** [comment]
The remaining problem is to add a button that let Linux & mac users invert the article colour, but I want to do this after reviewing how the config works. Config related code is way too cumbersome.

**Comment by xiaoyifang** [comment]
darkreader seems have a feature to auto detect the platform style.

**Comment by shenlebantongying** [comment]
That thing doesn't work on Linux. Every desktop environment implements "dark" differently. There is no reliable way to detect it. The fragmentation is real.

Also, I think even on Windows we should have that option to prevent auto-inverting articleview's color.

There is a pretty popular vision problem that will make the white text on dark background blurry. Google "astigmatism dark mode".

It is possible that a user may use Dark UI and white text area.

The current built-in themes in GD also have a yellowish one and a bluish one, some may prefer them over dark. (We probably should also include a greenish one.)
