### ISSUE TITLE
Replace group icons/flags with emoji.

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict#278]
I encounter a bug that short word will be elided on macOS if a group is set.
<img width="200" alt="Screenshot 2022-12-26 at 2 01 03 PM" src="https://user-images.githubusercontent.com/20123683/209576896-8317a66c-99eb-4f4d-b4be-31b321083c81.png">

I revert before this, but it is broken too. This is probably a combination of Qt's and mac's version change.
https://github.com/xiaoyifang/goldendict/pull/272
<img width="200" alt="Screenshot 2022-12-26 at 1 58 51 PM" src="https://user-images.githubusercontent.com/20123683/209576777-134232cc-1b4b-4634-b3fa-4206f43643fa.png">

It works normally if the user doesn't use group icons.

---

Instead of fixing it, I think we can do better: replace them with emojis.

The `flag/` folder that we bundled is only used in two places: language choice and group icons.

To avoid breaking existing users, we can make it an editable combo box with country flags as selectable choices but users are free to use any emoji or any other symbols.

To ensure flags exist, we can reuse github's country flag selection:
https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md#country-flag

Also, remove the language flags due to this issue:
https://github.com/goldendict/goldendict/issues/1330

`flag/` folder can be removed entirely. Get rid of those 1.1Mb and reduce memory consumption.

The blur problem of those icons on HiDPI screen is also fixed by just not using them.

---

QString supports emoji directly, they should work out of the box.

**Comment by shenlebantongying** [comment]
Using emojis also fixes the imperfect icon & text alignment on Linux if a user doesn't use the default qt theme.

![image](https://user-images.githubusercontent.com/20123683/209578155-cd78a6b9-045c-464d-b2d1-73ad07d1dee3.png)
![image](https://user-images.githubusercontent.com/20123683/209578177-67282167-7d41-4bbc-b980-c84eea1e5a6c.png)

**Comment by xiaoyifang** [comment]
> but it is broken too. This is probably a combination of Qt's and mac's version change.

If this is the case ,can report it to qt bug.
https://bugreports.qt.io/secure/Dashboard.jspa

**Comment by xiaoyifang** [comment]
> Also, remove the language flags due to this issue:
> [goldendict#1330](https://github.com/goldendict/goldendict/issues/1330)

this issue is not setted , I think we should leave it for now.

**Comment by xiaoyifang** [comment]
https://bugreports.qt.io/browse/QTBUG-64630
