### ISSUE TITLE
Shortcut “Ctrl+H" is set 3 times.

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict#279]
I am exploring the possibility to make a shortcut editor, then I found this GEM (insanity)!

1.
https://github.com/xiaoyifang/goldendict/blob/bcfa3f0bd41dc8c84f94a1d760d1202bfa36d377/mainwindow.ui#L475-L485

2.
https://github.com/xiaoyifang/goldendict/blob/bcfa3f0bd41dc8c84f94a1d760d1202bfa36d377/mainwindow.cc#L530

3.
https://github.com/xiaoyifang/goldendict/blob/bcfa3f0bd41dc8c84f94a1d760d1202bfa36d377/mainwindow.cc#L2514-L2520

This is PR that the 3rd got added
https://github.com/xiaoyifang/goldendict/commit/3ed7772996f92401d6040e0bd8409b647894d92b

The reason why the 3 exists is that the 1 & 2 are conflicting, thus Qt cannot figure it out.

So the 3 is a HACK patch that "catches" the shortcut in the event filter.

1,2,3 should all be deleted.

Then should be unified as one `history_panel_toggle()` and only a single entry point.

```
auto history_panel_shortcut = QShortcut(QKeySequence("Ctrl+H"),this)
connect(history_panel_shortcut, activated, history_panel_toggle())
```

```
history_panel_toggle -> set Menubenu bar's "Show/Hide" and toggle the visibility of the history panel.
```

**Comment by xiaoyifang** [comment]
there are in different places.
![image](https://user-images.githubusercontent.com/105986/209620631-e6fb91f8-bc4d-4930-a282-6c5c5f863a47.png)

![image](https://user-images.githubusercontent.com/105986/209620665-88376aa6-0aaa-4639-92c4-874b3dba2065.png)

**Comment by shenlebantongying** [comment]
There is another useless even filter that does exact the same thing. I put it on another PR.

**Comment by shenlebantongying** [comment]
There is 4th conflict hidden.
A slot like this will be automagically connected to the .ui file's corresponding widget.
```
void on_<object name>_<signal name>(<signal parameters>);
```
https://doc.qt.io/qt-6/designer-using-a-ui-file.html#widgets-and-dialogs-with-auto-connect
https://doc.qt.io/qt-6/qmetaobject.html#connectSlotsByName

The on_on_showHideHistory_triggered is already connected and don't need these code at all.
https://github.com/xiaoyifang/goldendict/blob/bcfa3f0bd41dc8c84f94a1d760d1202bfa36d377/mainwindow.cc#L2514-L2519

---

A name change in UI file won't affect the C++ file. The code still compiles, but a connection will be gone. Changing a name requires changes in two places.

This feature is a foot gun and should be avoided like plague.
