### ISSUE TITLE
`enable scanning ` option has not been remembered after restart

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict#280]
![image](https://user-images.githubusercontent.com/105986/209622774-641f63aa-85af-4c57-ba08-a45a8c417cce.png)

@shenlebantongying can you plz check on this

**Comment by shenlebantongying** [comment]
I think this is set via here:
![image](https://user-images.githubusercontent.com/20123683/209624052-06f7e429-c481-4ccf-ba66-2777f3d53f3c.png)

Some users may start GD -> use scan popup -> shutdown via the tray -> Do he wants this popup enabled the next time the startup? 

Maybe not? I think the explicit setting it better.

**Comment by xiaoyifang** [comment]
reasonable.
