### ISSUE TITLE
[Feature Request] Add shortcut to automatically save audios

### ISSUE THREAD

**Issue by Memory383** [xiaoyifang/goldendict#282]
**Problem:** To create Anki Cards with audios it is necessary to manually click over a dictionary and "export" the audio. The process takes several clicks and is time consuming ! _This is important for people who make many Anki cards daily._

![grafik](https://user-images.githubusercontent.com/121114125/209638796-9c515d6b-7697-4931-abb1-e62ffaf27fa5.png)

**Possible solutions:** 
1) A new function on GoldenDict via AnkiConnect to export audios from an Article ?

2) A shortcut (e.g. CTRL + G) that would automate the process by automatically choosing the **first audio** among all the dictionaries. Then, saving it into a predetermined folder.  So, when a user is interested in exporting an audio to make an Anki Card simply pressing a shortcut would save time.  

@shenlebantongying since you been working with shortcuts. What do you think about this latter option?

**Comment by shenlebantongying** [comment]
![image](https://user-images.githubusercontent.com/20123683/209640470-00ca58db-947c-4d1e-83ab-c651d9106eab.png)
There is already a "Save Sound" in right-click menu, however, there is no shortcut. 

> automatically choosing the first audio in all the dictionaries.

I don't think this works as a general workflow that works for everyone.

`Put the cursor on a sound -> use shortcut` to export should be good enough.

> Then, save it into a predetermined folder.

I think KDE file chooser can preserve the path of "Save something". You don't need to set it once for each goldendict run.

Thus it becomes 

`Put the cursor on a sound -> use shortcut -> press Enter`

**Comment by shenlebantongying** [comment]
You can now do

Right Click -> `O` -> `Enter` to save audio.

O and Enter can be pressed in one hand, so this should already much faster than clicking.

I assume you use an arch-based distro, you can try upgrade now. @Memory383

**Comment by Memory383** [comment]
> I assume you use an arch-based distro, you can try upgrade now.

I cannot upgrade the AUR package on Manjaro Stable KDE.  

The latest succesfull update for me was on December 5th.

_Goldendict 22.11.24-alpha.03d92168 on Mon Dec 5 07:03:27 2022
manjaro linux 5.15.85-1-MANJARO Qt 5.15.7 x86_64-little_endian-lp64
GCC 12.2.0_

I use Yay with "development" packages always activated by default.  Somehow, GoldenDict is not being updated. 

Manjaro does not detect any change in GoldenDict verison from AUR:

![grafik](https://user-images.githubusercontent.com/121114125/209678354-cf77e796-0875-4d74-aa03-08f056fc01e2.png)


Maybe there is a problem in the PKG @shenlebantongying ?

_Anyone else having troubles with [AUR package](https://aur.archlinux.org/packages/goldendict-webengine-git) ?_

Btw, thanks for maintaning the AUR package @shenlebantongying  !!!

**Comment by shenlebantongying** [comment]
I am not sure about the problem. Have you tried to uninstall & reinstall?

Personally, I will delete try to delete `~/.cache/yay/goldendict-webengine-git` to force a repull. (I have zero idea if this is the right thing to do)

Also, `yay -Syu goldendict-webengine-git` will give you a prompt to do a cleanbuild which is almost the same thing.

**Comment by Memory383** [comment]
_> Have you tried to uninstall & reinstall?_
Issue solved ! Thanks.

Unfortunately, the new shortcuts do not work on my OS (Manjaro KDE). 
----
On the other hand, the LinguaLibre implementation is buggy. If I use only the "LinguaLibre" dictionary in a group it works perfectly. However, if I put the "lingualibre" dictionary with other dictionaries (.dsl/mdx) I get NO results from queries. In other words, it is impossible to search a new word.

**Comment by shenlebantongying** [comment]
> new shortcuts do not work

It seems in Germany, the key got translated to `K`

https://github.com/xiaoyifang/goldendict/blob/caa97a7120eb646f53d2c77bdc46976d36903c2c/locale/de_DE.ts#L313-L315

![image](https://user-images.githubusercontent.com/20123683/209743636-0eaf5f48-9085-461a-9262-6ae5e881d0af.png)

You hold alt to check it out. Personally, i set it to "always show"

![image](https://user-images.githubusercontent.com/20123683/209743779-cf9b59fa-0c22-425b-8b41-6a59c7276800.png)
