### ISSUE TITLE
Some interesting changes from @vedgy

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict#285]
The abundance of knowledge and professionalism of @vedgy is really amazing.

I checked his repo and there are some changes that we could probably use too,

- [x] get rid of all `qrcx://localhost` https://github.com/goldendict/goldendict/commit/c415cede8509b1bc431fbda81f681c95be0281e0 more context https://github.com/goldendict/goldendict/commit/bb06509582c9a1ab342f5b79c85c3e28a26b19bc
- [x] eliminate const_cast (which turns const to none-const. C++'s insane feature) We have 4 const_cast https://github.com/goldendict/goldendict/commit/eac39f7626690a7a7fdb27beeba74c9aa057ff61
- [ ] disable a zoom hack https://github.com/goldendict/goldendict/commit/7a1741b3df9005afdc4549ac4ac3356cd1e61dad follow up https://github.com/goldendict/goldendict/commit/17f9e4680f69d1c093636d39afdf1f561cbd6a78

minor ones:
- [x] https://github.com/goldendict/goldendict/commit/acdd40618519fba41948ec48cb280217fbd7c556
- [x] https://github.com/goldendict/goldendict/commit/1d57f49b5e058448ad9724b5a01db02539c01510

**Comment by Memory383** [comment]
@vedgy has very good ideas and believes in Free Software (GPLv3) !

 I also suggest to "cherry-pick" all his improvements into this fork of GoldenDict.

That is the real spirit of Free Software ! Thanks to all for your great work ! :D
