### ISSUE TITLE
Increase bus factor

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict#289]
One of the biggest bugs of the original repo is that the bus factor is 1 and it looks like going to be zero.

To avoid the risk of rare events or another costly fork in future, I think you should add me as a collaborator to ensure better longevity.

I will still submit patches via PR.

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository

unrelated
https://www.crummy.com/writing/segfault.org/Bus.html

**Comment by xiaoyifang** [comment]
done

**Comment by shenlebantongying** [comment]
thanks
