### ISSUE TITLE
Error with .mdx images from a Visual Dictionary

### ISSUE THREAD

**Issue by GPLv3-fan** [xiaoyifang/goldendict#29]
The "Official" GoldenDict-git version from Arch User Repository shows correctly this mdx:
https://forum.freemdict.com/t/topic/10452

The term "Orange" is shown as follows:
![image](https://user-images.githubusercontent.com/58692066/159142841-4e6bf844-abf8-41dc-a899-f346aa07dd92.png)

However, if you look the word "Orange" with @xiaoyifang version:

![image](https://user-images.githubusercontent.com/58692066/159142928-2319138e-9f58-43b9-ab1e-14936436859f.png)

The settings are exactly the same among both versions of GoldenDict. I exported the article as .html and checked on "Brave" browser and the images do not show properly either from the browser.  However, there is a clear difference among the versions of GoldenDict.

**Is there a way to solve this issue ?** 

We might not blame the .css / .mdx because it works properly on GD Official...

**Comment by xiaoyifang** [comment]
looks good on my side.
![image](https://user-images.githubusercontent.com/105986/159147207-2ffbdfda-039c-4a3a-ad2a-5a483e0afed3.png)

which version do you use.
disable your other dictionaries to verify again .
more chances that the other dictionaries's css have affect this dictionary.

**Comment by GPLv3-fan** [comment]
Duplicate of #27 

Thanks for your valuable insights. The issue was caused by a single .mdx file interfering with others (Forvo German : https://forum.freemdict.com/t/topic/7355/7 )

Unfortunately, .mdx dictionaries have a tendency to affect the display of other dictionaries. Sorry. I am closing this issue.
