### ISSUE TITLE
Replace `hotkeyedit.cc` with  `<QKeySequenceEdit>`

### ISSUE THREAD

**Issue by shenlebantongying** [xiaoyifang/goldendict#291]
`hotkeyedit.cc` is just `<QKeySequenceEdit>` for Qt4.

If we have a shortcut editor, then we have to interact more with this widget and there is no meaning to maintain our own one.

A side-effect is fixing https://github.com/goldendict/goldendict/issues/304

---

The current hotkeyedit.cc must be used because we cannot register arbitrary global keys right now. It must be one modifier + two normal keys.

**Comment by xiaoyifang** [comment]
agreed. a nice idea.
