### ISSUE TITLE
possibility to use libzim  to parse the zim dictionary

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict#30]
Actually, they explicitly changed from `GPL2` to `GPL2+`

https://github.com/openzim/libzim/commit/f57bca28217be00587bbcf8e45b40db4e48249da

Plus this chart from gnu.org

https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility

their previous discussion on this matter

https://github.com/openzim/libzim/issues/30

_Originally posted by @shenlebantongying in https://github.com/xiaoyifang/goldendict/issues/27#issuecomment-1073786973_

**Comment by xiaoyifang** [comment]
the cons and pros of using libzim,
pros:
- support super large zim dictionary >40G

cons:
- ?

**Comment by xiaoyifang** [comment]
https://github.com/goldendict/goldendict/issues/914

**Comment by ancientstraits** [comment]
Sure, I could contribute to this. Would `zim.cc` be the only file I would have to change?

**Comment by xiaoyifang** [comment]
great, AFAIK ,zim.cc is the file.

**Comment by xiaoyifang** [comment]
add some test data:
goldendict: wikipedia_zh_all_maxi_2022-01.zim  19G  ,parse with gd about 20 seconds and search is ok.
