### ISSUE TITLE
Last main window state is not saved on the Qt 6.4.2 Windows version

### ISSUE THREAD

**Issue by courrier1** [xiaoyifang/goldendict#312]
When using the 6.3.2 version and closing the program while maximized for example, the next time I launch the program it is back to its previous state, while on 6.4.2 it appears in a default state.

How **6.4.2** main window appear after I close it while maximized:
![Capture](https://user-images.githubusercontent.com/43888282/212374472-9dd4412e-afd9-427b-97d7-283f5117687b.PNG)

And this is how the 6.3.2 appears:
![Capture2](https://user-images.githubusercontent.com/43888282/212374944-ef272b4a-3bcd-4320-90dd-a34021e8c202.png)

**Comment by shenlebantongying** [comment]
We didn't change any of the code related to Window State.

It only happens in the Qt6 version, This might be a Qt Bug.

You can switch back to Qt5 (aka 5.15.2-GoldenDict____) to avoid this.

**Comment by courrier1** [comment]
I'm using the 6.3.2 version and it works fine, the problem is only with 6.4.x version.

**Comment by xiaoyifang** [comment]
the code of saveState and restoreState is in the mainwindow.cc
https://github.com/xiaoyifang/goldendict/blob/069714e3a2fd689969724d556ce24349697e3156/mainwindow.cc#L1094-L1095

more likely a qt bug.
