### ISSUE TITLE
Slow load time of dictionaries with websites/programs - Dictionaries don't lazy load in order

### ISSUE THREAD

**Issue by kanjieater** [xiaoyifang/goldendict#313]
In the [latest alpha versions of the official goldendict](https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Windows#150-rc2-372-gc3ff15f) dictionaries could load in sequence.
![image](https://user-images.githubusercontent.com/32607317/213318399-7565f239-3363-4e10-bd9a-88091c07e863.png)
I have these dictionaries installed, where the first 2 are local epwings and the next two use jisho.org and google images, then finally anki. The network calls are slow, and the epwings are instant, so i put the epwings at the top to see text before everything else has to load. 

With the latest alpha version, which is the first version of this fork I tried, it does not behave this way, and waits until everything loads before flashing in.

My request is that each entry (dictionary, website, program) could load independently from top to bottom, as it does in the original. Is this something that could be changed? Thanks for your work on modernizing this useful app!

**Comment by Memory383** [comment]
@kanjieater could you please describe what do you mean by "Anki" on your search results ?

Do you query "Ankiweb" in each single search made on GoldenDict ? If so, could you please briefly describe the method ?

@xiaoyifang  I also support the idea that dictionaries **should load independently from top to bottom.** 

 Sometimes I need to wait until 10 seconds to listen a pronunciation that is my first Dictionary in the list! :(

Thanks for your great work !

**Comment by kanjieater** [comment]
> @kanjieater could you please describe what do you mean by "Anki" on your search results ?
> 
> Do you query "Ankiweb" in each single search made on GoldenDict ? If so, could you please briefly describe the method ?
> 
> @xiaoyifang I also support the idea that dictionaries **should load independently from top to bottom.**
> 
> Sometimes I need to wait until 10 seconds to listen a pronunciation that is my first Dictionary in the list! :(
> 
> Thanks for your great work !

I am referring to this - an add-on/program to connect anki & GD: https://github.com/goldendict/goldendict/issues/1352

**Comment by xiaoyifang** [comment]
try this version https://github.com/xiaoyifang/goldendict/releases/tag/v23.02.07-alpha.230329.00e04597

**Comment by xiaoyifang** [comment]
use the latest release
