### ISSUE TITLE
chromium blocks calls to localhost/CORS

### ISSUE THREAD

**Issue by kanjieater** [xiaoyifang/goldendict#314]
I was hoping to migrate my goldendict add-ons to this fork. The issue I ran into is that when I try to make an ajax call from goldendict to a local server ([my anki addon w/ ankiconnect](https://github.com/goldendict/goldendict/issues/1352)), goldendict blocks my calls out, with status blocked:other and ERR_BLOCKED_BY_CLIENT. Could we enable client side calls to localhost in this version of chromium like the original goldendict did?

![image](https://user-images.githubusercontent.com/32607317/213325234-d279a512-7348-4113-b629-77f36a572583.png)
![image](https://user-images.githubusercontent.com/32607317/213325255-08ba0094-6004-42c7-88ef-a393e1e9359d.png)

I'm uncertain but my guess is you would have to enable [chrome flags](https://stackoverflow.com/questions/61816703/using-chrome-flags-with-qtwebengine-pyqt5) as I think (but am not certain) this is related to [this flag](https://stackoverflow.com/questions/35531347/localhost-blocked-on-chrome-with-privacy-error)

**Comment by shenlebantongying** [comment]
I see no this error. Exactly how to reproduce?
![image](https://user-images.githubusercontent.com/20123683/213329227-ac3c0245-7b62-43e3-89b4-0c169973673e.png)

Also, there is built-in dark theme now (Preference -> Interface -> Dark Mode & Dark Reader Mode). You don't need custom qt-style or article-style.css anymore.

**Comment by kanjieater** [comment]
Thank you for the note on the dark mode - it is appreciated. Have a local server running. Try to call it from the Goldendict Inspect console you have open in the picture.

Something like this will work if you add the goldenassets-win.exe as well (it uses jquery but if you want to write xhr requests that would work too). Then call any local server from the client. In my case it's `http://localhost:8765/`, because that's what I use for Anki with AnkiConnect add-on. I think any server should be able to simulate this though, as it's a client issue not a server one.

`C:\Users\KanjiEater\AppData\Roaming\Anki2\addons21\247820692\goldenassets-win.exe --input %GDWORD%`

```
 $.ajax({
          url: 'http://localhost:8765/', 
          type: "POST",
          dataType: "json",
          contentType: "application/json; charset=utf-8",
          data: JSON.stringify({
            action: "sendToAnki",
            version: 6,
            params: {
                "note": {
                  "fields": {
                      "vocab": window.gdword,
                      "definition": text
                  },
              }
            }
          }),
          success: function( resp ) {
            if (resp.error){
              var message = resp.error;
              flash(element, message, 5000);
            } else {
              var message = 'Sent to Anki!';
              flash(element, message);
            }  
          },
          error: function( req, status, err ) {
            console.log( 'something went wrong', status, err );
            var message = 'Failed!';
            flash(element, message);
          }
        })
```

**Comment by shenlebantongying** [comment]
I am sorry, I am not an expert of Web programming and I can't reproduce.

We do disabled chromium's security as discussed at https://stackoverflow.com/questions/10883211/why-does-my-http-localhost-cors-origin-not-work
https://github.com/xiaoyifang/goldendict/blob/52f11d4a4652909d76857f89d8a48c4d444ce50f/main.cc#L286

I fired up a local server with code copied from https://stackoverflow.com/a/27280939/12494649

Then I can make a POST request via fetch() and get the response inside goldendict.

![image](https://user-images.githubusercontent.com/20123683/213337746-f11bd30a-1323-4a0e-a66e-63fb5a7c2ce8.png)

**Comment by kanjieater** [comment]
Hmm. Thanks for looking! If it's ok to keep this open, I will try to reproduce and see exactly what the issue is and give feedback here. It might take me a few weeks as I will be unavailable for a few days.

**Comment by kanjieater** [comment]
Not sure what the issue was but it seems to be working just fine now. Thanks for the help.

I think I may have needed to change ankiconnect inside of the anki addon's config to `  "webBindAddress": "0.0.0.0",`
