### ISSUE TITLE
What is the best version to use?

### ISSUE THREAD

**Issue by darlopvil** [xiaoyifang/goldendict#316]
Hi, 
since you offer a huge variety of options, what files have i to download in order to run GD?
I'm on a new computer with no previous installations. So far, "goldendict.exe" cannot be executed but, what instead?

![imagen](https://user-images.githubusercontent.com/60988792/213566452-0b8b3e96-4aef-4dc9-a4a5-a2184912fda7.png)

**Comment by shenlebantongying** [comment]
Try

5.15.2-GoldenDict-v22.12.22-WinterSolstice-Installer.exe
5.15.2-GoldenDict.exe_windows-2019_20221220.zip

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/215301281-2f1fcb01-5750-41a4-b748-72465f88414c.png)
