### ISSUE TITLE
ERROR: vorbisfile development package not found

### ISSUE THREAD

**Issue by munzirtaha** [xiaoyifang/goldendict#317]
Hi, and thanks for your great work! I prefer to use your version because webengine solves the problem of displaying Arabic properly. However, I no longer can compile goldendict in archlinux (https://aur.archlinux.org/packages/goldendict-webengine-git). I am getting this error:

```
v22.11.24-alpha.221213.bdcf632b-99-g52f11d4a-dirty
Project MESSAGE: generate version.txt....
Project MESSAGE: Install Prefix is: /usr
Project MESSAGE: copy qt6.4.0 multimedia
Project ERROR: vorbisfile development package not found
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'goldendict-webengine-git-22.9.24.alpha.221116.9bb71336.r48.g9f65f3c1-1': 
error: packages failed to build: goldendict-webengine-git-22.9.24.alpha.221116.9bb71336.r48.g9f65f3c1-1
```

I checked and libvorbis is already installed and provides libvorbisfile.so

```
> pacman -Qi libvorbis
Name            : libvorbis
Version         : 1.3.7-3
Provides        : libvorbis.so=0-64  libvorbisenc.so=2-64  libvorbisfile.so=3-64

```

**Comment by shenlebantongying** [comment]
Have you tried a clean build (remove AUR helper's cache)? The output of `pkg-config --exists --print-errors vorbis`?

**Comment by munzirtaha** [comment]
I thought I did clear not only the cache but the whole directory, but seems I was wrong. Thanks a lot @shenlebantongying it compiles now.
