### ISSUE TITLE
macOS 端关闭主窗口后，点击 Dock 栏上的 GoldenDict 图标仍无法进入主界面

### ISSUE THREAD

**Issue by aoaim** [xiaoyifang/goldendict#318]

**Comment by aoaim** [comment]
测试了仓库下多个release版本均有这个问题，关闭主窗口但不退出后台后，只有通过状态栏的GD图标才能唤醒主页面，而不能直接通过Dock栏来唤醒。

**Comment by shenlebantongying** [comment]
试了一下确实会这样，暂时可以先点击黄色的 minimize 而不是红色的关闭，或者从设置面打开 Esc 缩小，或者 Command+F4

应该是和之前的原因是一样的 https://github.com/xiaoyifang/goldendict/issues/300

**Comment by aoaim** [comment]
> 

原来如此！谢谢老哥，我看到老哥已经merge上了。
