### ISSUE TITLE
Hotkey "translate word from keyboard" stopped working

### ISSUE THREAD

**Issue by epistularum** [xiaoyifang/goldendict#321]
I updated to:
```
Goldendict 22.12.24-alpha.52f11d4a on Sat Jan 21 17:05:24 2023
arch linux 6.1.7-arch1-1 Qt 5.15.8 x86_64-little_endian-lp64
GCC 12.2.1 20230111
Flags: MAKE_ZIM_SUPPORT MAKE_EXTRA_TIFF_HANDLER MAKE_CHINESE_CONVERSION_SUPPORT
```

and the previously working "Use the following hotkey to translate a word from clipboard" hotkey stopped working. I have tried multiple key combinations without any result. The "track clipboard change" feature does work which would mean that GD is able to read from the clipboard but perhaps just unable to understand the key presses?

I have also launched GD from the terminal in order to read the logs in case any error message pops up but nothing happens upon pressing the defined shortcut key.

**Comment by shenlebantongying** [comment]
Set it to `Ctrl+C, Ctrl+C`.

**Comment by epistularum** [comment]
That is already the shortcut I have been using up until now, it stopped working.

**Comment by shenlebantongying** [comment]
What's your desktop enviroment?

**Comment by epistularum** [comment]
@shenlebantongying I haven't updated in a long while, perhaps more than a month. My environment is kde/x11.

**Comment by shenlebantongying** [comment]
Can you try setting it to something else, then setting it back to `Ctrl+C Ctrl+C`? We changed the widget used in the hotkey setting dialog. Maybe the format doesn't match the one in the config?

**Comment by epistularum** [comment]
@shenlebantongying Unfortunately this doesn't resolve the issue.

**Comment by epistularum** [comment]
The issue suddenly disappeared, I am closing the issue.
