### ISSUE TITLE
Display incorrect in "Dark Reader Mode"

### ISSUE THREAD

**Issue by thenicegirl** [xiaoyifang/goldendict#332]
Some of my dictionaries become unreadable after I turn on "Dark Reader Mode", I like "Dark Reader Mode" very much. please fix it. @xiaoyifang 
![Snipaste_2023-02-07_03-09-29](https://user-images.githubusercontent.com/53411757/217065361-a31bf6b2-5057-4f1f-b8d5-5e51e42d3903.png)

**Comment by shenlebantongying** [comment]
Either this is already fixed, or this is a problem of that specific dict.

Another oxford dict looks OK to me.

![image](https://user-images.githubusercontent.com/20123683/221947663-ae226807-a5bc-45a9-a273-f2d370ae3625.png)
