### ISSUE TITLE
The newest version doesn't display the contents of dictionaries with dsl extension

### ISSUE THREAD

**Issue by zT2Dz** [xiaoyifang/goldendict#335]
Hello, have a nice day.
I have a dictionary with dsl extension, and it only shows the first character of its content when I search for a keyword.
This problem doesn't happen in the previous release version. Please help me to solve this. 
Thanks in advance.
My .dsl dictionary: [https://drive.google.com/file/d/1D4wwG0Y_tJd6sUkjPl4uTbm4PZcpVqqh/view?usp=share_link](url)
A picture of this issue:
![image](https://user-images.githubusercontent.com/43036863/217296541-92b6f6e1-3be2-4b24-a32c-2fa92d393f30.png)

**Comment by xiaoyifang** [comment]
fixed,try the latest version.
