### ISSUE TITLE
[Windows 11] No sounds on 6.4.2 Windows 11 22H2, but everything works normally on 5.15.2

### ISSUE THREAD

**Issue by bossdatmac** [xiaoyifang/goldendict#338]
[Windows] No sounds on 6.4.2 Windows, but everything works normally on 5.15.2

By the way, may I ask if there are any benefits of using 6.4.2 over 5.15.2? 

Thank you

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/issues/331

**Comment by xiaoyifang** [comment]
fixed with new release with qt6.4.3
