### ISSUE TITLE
what is the difference between 'experiental' version and the version without 'experiental'

### ISSUE THREAD

**Issue by safesummer** [xiaoyifang/goldendict#343]
the program is great but I am confused about the versions and releases .

Another question is the audio I played the first time will play the second time when I search  the other word!!!
version is 2.09 (without experiental ,Qt 6.42)

**Comment by safesummer** [comment]
win10 22h2 ,amd

**Comment by xiaoyifang** [comment]
> Another question is the audio I played the first time will play the second time when I search the other word!!!
> version is 2.09 (without experiental ,Qt 6.42)

https://github.com/xiaoyifang/goldendict/issues/341
