### ISSUE TITLE
不能在维基百科中通过打开新标签页的方式来打开超链接

### ISSUE THREAD

**Issue by doubanb** [xiaoyifang/goldendict#359]
Goldendict 23.02.06-LanternFestival.230208.c9bde81b
windows winnt 10.0.22000 Qt 6.4.2 x86_64-little_endian-llp64

非常希望增加wiki词条预览功能。。。（鼠标指针落在wiki词条内容中的超链接上就会出现一个小的预览窗口

**Comment by xiaoyifang** [comment]
右键菜单 ，在新标签页中打开。

**Comment by doubanb** [comment]
> 右键菜单 ，在新标签页中打开。

是的，这样可以打开，但是打开超链接在维基百科中也只能先左键选取后点击右键才可以显示“在新标签页中打开”的选项

**Comment by xiaoyifang** [comment]
ctrl+鼠标左键点击链接试下

**Comment by doubanb** [comment]
> ctrl+鼠标左键点击链接试下

可以的，感谢大佬。 但是后续您可以考虑将此条说明添加到快捷键文档中，因为这样可以避免后续的用户们也遇到同样的问题

**Comment by xiaoyifang** [comment]
这个地方有。
F1,打开帮助文档，
![image](https://user-images.githubusercontent.com/105986/224586013-4a90b234-e627-4e6a-9540-f6fd92ee933a.png)

**Comment by doubanb** [comment]
> 这个地方有。 F1,打开帮助文档， 

是的，我打开了但是。。没有看到有关打开超链接的说明。。
Shortcut | Action
-- | --
Alt++ | Increase font size for matches list
Alt+– | Decrease font size for matches list
Alt+0 | Restore default font size for matches list
Alt+Left, Backspace | (In main and popup windows) history navigation: show previous founded results
Alt+Right | (In main and popup windows) history navigation: show next founded results
Alt+Down | Jump to article from next dictionary
Alt+Up | Jump to article from previous dictionary
Alt+Enter, Ctrl+Enter | (Search line) Show translation in new tab
Alt+D, Ctrl+L | (In main and popup windows) go to search line
Alt+G | (In main and popup windows) choose dictionaries group from group list
Alt+S | (In main and popup windows) playback pronunciation for current word
Alt+W | (In popup window) transfer word from search line to main window
Alt+PgDown | (In main and popup windows) switch to next dictionaries group
Alt+PgUp | (In main and popup windows) switch to previous dictionaries group
Ctrl++ | Increase articles font size
Ctrl+– | Decrease articles font size
Ctrl+0 | Set default articles font size
Ctrl+MouseWheel | Increase/decrease articles font size
Ctrl+A | Select all articles in current page
Ctrl+C | Copy selected
Ctrl+D | Switch to dictionary headwords dialog (if it is open)
Ctrl+E | Add current tab to Favorites
Ctrl+F4 | (Main window) minimize to system tray
Ctrl+F5 | Rescan dictionaries
Ctrl+F | (In main and popup windows) search in page / (In dictionaries dialog) go to filter line
Ctrl+H | Show/hide history pane
Ctrl+I | Show/hide Favorites pane
Ctrl+M | Show/hide main menu
Ctrl+N | (In dictionary headwords dialog and full-text search dialog) switch to main window
Ctrl+O | Above all windows
Ctrl+P | (In main window) print current article
Ctrl+Q | (In main window) close GoldenDict
Ctrl+R | Show/hide results pane
Ctrl+S | Show/hide search pane
Ctrl+T | (In main window) create new tab
Ctrl+W | (In main window) close current tab
Ctrl+PgDown | (In main window) switch to next tab
Ctrl+PgUp | (In main window) switch to previous tab
Ctrl+Tab | (In main window) switch to next tab (can be changed in preferences)
Ctrl+8, Ctrl+* | (In main and popup windows) expand/collapse optional areas for all articles
Ctrl+Shift+A | Select current article only
Ctrl+Shift+C | Copy selected as text
Ctrl+Shift+F | Open/switch to full-text search dialog
Ctrl+Shift+W | Close all tabs
Del | (History) delete select line
Enter | (In main window) go to search line
Esc | (In main window) go to search line (the action for Esc key can be changed in preferences) / (in popup window) close popup window
F1 | GoldenDict reference
F2 | (In main window) save current page to html
F3 | Dictionaries dialog
F4 | GoldenDict preferences
F12 | Inspector

**Comment by xiaoyifang** [comment]
估计是太久了，好久没更新了。后续梳理下。
