### ISSUE TITLE
Belarusian update

### ISSUE THREAD

**Issue by antikruk** [xiaoyifang/goldendict#362]
Please, merge in your fork https://github.com/goldendict/goldendict/pull/1605

**Comment by xiaoyifang** [comment]
I’ll look into it later

**Comment by xiaoyifang** [comment]
the codebase has changed a little.  Can you make the chanages based on this file https://github.com/xiaoyifang/goldendict/blob/staged/locale/be_BY.ts and submit a PR to this repository?

**Comment by antikruk** [comment]
I can't fork your repository because I already forked the original repository. I am attached the file with changed url.
[be_BY.zip](https://github.com/xiaoyifang/goldendict/files/10868885/be_BY.zip)

**Comment by xiaoyifang** [comment]
5aa41027968a1c384820126330f9339cd9000a35

**Comment by antikruk** [comment]
Thanks. You can create a ppa for Ubuntu 22.04?

**Comment by xiaoyifang** [comment]
I do not know how to create ppa yet.
