### ISSUE TITLE
Protocol-relative URLs in CSS are broken

### ISSUE THREAD

**Issue by bershanskiy** [xiaoyifang/goldendict#363]
Some Wikipedia sources in articles have icons next to them. For example, [SVG](https://en.wikipedia.org/wiki/SVG) reference number 2 has a green padlock:
![image](https://user-images.githubusercontent.com/45960703/222264158-3f6d12eb-6ea6-4be4-ae9d-ff1e55159f27.png)
This icon is injected by the following style declaration in CSS:
![image](https://user-images.githubusercontent.com/45960703/222264716-e378c0b2-3ff5-4125-8e28-66f57e01f2c4.png)
The declaration uses protocol-relative URL which should be converted into `https://` URL, but instead it is converted to `gdlookup://` URL (to match the page protocol).

I noticed this while working on https://github.com/darkreader/darkreader/issues/10530

**Comment by xiaoyifang** [comment]
I'll check on this
