### ISSUE TITLE
无法在sway中弹出查询窗口。

### ISSUE THREAD

**Issue by buddhiko1** [xiaoyifang/goldendict#370]
在窗口管理器sway中无法弹出查询窗口（例如，按两次Ctrl+c），查询窗口只会闪一下就关闭了。

下面是sway相关的配置。
bindsym Mod5+g exec ~/Downloads/goldendict.AppImage 
for_window [title=".*GoldenDict"] resize set width 40 ppt
for_window [class="GoldenDict"] floating enable

原版的goldendict不会。

**Comment by buddhiko1** [comment]
@shenlebantongying  
好的，谢谢~
系统是gentoo，上次用第三方的构建脚本没有编译成功， 不过那是几个月以前了，我还是在等等，暂时还是用回老版本的。
感谢@xiaoyifang  为我们提供一个可持续的goldendict，毕竟老版本的太久没动静了，词典又真的太重要了~

**Comment by shenlebantongying** [comment]
> 用第三方的构建脚本没有编译成功
有什么报错呀，不贴一下有什么问题永远解决不了，等是没有用的，
