### ISSUE TITLE
Background of search bar does not work automatically

### ISSUE THREAD

**Issue by evenlee** [xiaoyifang/goldendict#395]
Goldendict 23.02.07-alpha.230311.3b1591e5
macos darwin 21.6.0 Qt 6.4.2 x86_64-little_endian-lp64
Clang 14.0.0 (clang-1400.0.29.202)
Flags: MAKE_ZIM_SUPPORT MAKE_CHINESE_CONVERSION_SUPPORT

When I switch between Dark/Light mode, the search bar doesn't follow until I restart app
if app starts in light mode, and switch Mac theme to dark:
<img width="645" alt="image" src="https://user-images.githubusercontent.com/4009476/226099452-bd3e0586-38ff-49b5-86bf-728103538a83.png">

if app starts in Dark mode, and switch Mac theme to light:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/4009476/226099473-40ee68ea-07e5-4a50-83aa-4a7dc2662621.png">

And can we enable ' Dark Reader Mode' automatically when Mac dark Mode is enabled, thanks.

**Comment by shenlebantongying** [comment]
You can just restart goldendict.

Problem is that Qt Stylesheets don't work well with macOS's global theme switching.

Unless someone put significant effort into porting the qt-style.css into QStyle, nothing we can do here.

**Comment by xiaoyifang** [comment]
the other controls in the mainwindow can follow the global style theme.

is there a way to let the search bar to do the same?

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/blob/f7d6328f40bdaf3a0d952387d9be1a75e2b649e3/src/qtstyle/qt-style.css#LL20

suspected line.

**Comment by shenlebantongying** [comment]
The other controls can follow the global style theme because we don't modify them at all :sweat_smile:. We removed all of them at https://github.com/xiaoyifang/goldendict/pull/272 so that the system level dark theme works on macOS.

You can replicate the same problem by changing the colour theme on Linux with qt5ct or KDE/lxqt. Anything touched by qt stylesheets is "damned". They needs a restart to apply system-level theme changes. 

We have to replace the stylesheets with QStyle (which is a lot to learn).

Related: this blog post from a KDE's lead dev https://www.kdab.com/say-no-to-qt-style-sheets/

![image](https://user-images.githubusercontent.com/20123683/226105501-d4f2b503-6ef2-4d31-8c5a-8b2aea88421a.png)

**Comment by evenlee** [comment]
thanks for details @xiaoyifang , possible to enable ' Dark Reader Mode' automatically when Mac dark Mode is enabled?

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/releases/tag/v23.02.07-alpha.230321.383e45c7

@evenlee  can you try this test version and check if the issue still existed. I just removed the QSS parts of the search line

**Comment by xiaoyifang** [comment]
> thanks for details @xiaoyifang , possible to enable ' Dark Reader Mode' automatically when Mac dark Mode is enabled?

this senario is not in frequent use ,   will leave for further consideration.

**Comment by xiaoyifang** [comment]
> We have to replace the stylesheets with QStyle (which is a lot to learn).

qstyle is not the rescue , it also have bugs , the recent one I found is that when applied the QStyle ,the following qss will not take effect.
https://bugreports.qt.io/browse/QTBUG-103326

**Comment by shenlebantongying** [comment]
I think the bugreport will be closed. See the blog post:

![image](https://user-images.githubusercontent.com/20123683/226498081-447ff08c-f25b-46d1-b687-11c58eff8b40.png)

**Comment by evenlee** [comment]
> 

the background works now, thanks

**Comment by evenlee** [comment]
> > thanks for details @xiaoyifang , possible to enable ' Dark Reader Mode' automatically when Mac dark Mode is enabled?
> 
> this senario is not in frequent use , will leave for further consideration.

I think auto dark/light mode is popular in Mac user too, but understood your point, will keep on eye on following udpates
