### ISSUE TITLE
Consider renaming this fork

### ISSUE THREAD

**Issue by 1over137** [xiaoyifang/goldendict#40]
First, I would like to express my appreciation for your work. Goldendict is a great program which sadly became unmaintained. This seem to be the only major efforts at cleaning up goldendict for future use. Thank you!

I think you should consider renaming this fork, such as adding a suffix (e.g. goldendict-ng, goldendict-webengine). This is so that the Linux distro packaging teams can add this package without having to replace the original package, if they have one. This should also help attract some attention to your project.

I am a maintainer for a gentoo user overlay (::guru), and I would like to add a build script for this package.

On another note, if possible, please document as much as you can how this program works as you go along cleaning things up, by adding comments to the code or writing an ARCHITECTURE.md file under root, so that more people can understand it and help you. I haven't looked at the code in detail yet, but the 300+ files under the project root looks daunting. 

也可以用中文回复。

**Comment by xiaoyifang** [comment]
> I think you should consider renaming this fork, such as adding a suffix (e.g. goldendict-ng, goldendict-webengine). This is so that the Linux distro packaging teams can add this package without having to replace the original package, if they have one. This should also help attract some attention to your project.
> 
> I am a maintainer for a gentoo user overlay (::guru), and I would like to add a build script for this package.

thanks for you idea . rename the project will be considered but I think will not in the near future. This project in the first place is just want to contribute to the original official project.

I think  gentoo can choose the  script  name as goldendict-webengine ,it does not have to rely on upstream project name. just like arch linux did.  https://aur.archlinux.org/packages/goldendict-webengine-git
by this way ,the original goldendict script can remain unchanged.





> On another note, if possible, please document as much as you can how this program works as you go along cleaning things up, by adding comments to the code or writing an ARCHITECTURE.md file under root, so that more people can understand it and help you. I haven't looked at the code in detail yet, but the 300+ files under the project root looks daunting.

I already write some documents under the folder   `howto/`  ,  I also put the thirdparty dependency in the `thirdparty`. They are in the processing .  300+ files though daunting ,but they are more simplier than first thinking . As goldendict aims to support many dictionary formats .    each dictionary format is in a single file,such as mdx is used to parse & index mdx dictionary ,zim.cc(hh) is used to parse & index zim dictionary ,etc.

but a better file folder restructure is also welcome ,though not in emergency.

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/issues/489
