### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by 1over137** [xiaoyifang/goldendict#41]
Hi,

Can future tags be in a [semantic versioning](https://semver.org/) scheme? This would make it much easier to package this for Linux distributions. As you are still working on this actively, using the master branch is not ideal. However, the tags assigned and your release names are difficult to compare for a computer.  

For example, on the next release, please tag it as "v23.0.0"

**Comment by xiaoyifang** [comment]
current tags are like this  v22.4.alpha-githash
https://github.com/xiaoyifang/goldendict/tags

**Comment by xiaoyifang** [comment]
will be changed in the next release.

**Comment by 1over137** [comment]
That looks good.
Though, there's really no need to have a hash in there. You can just use `git show-ref` to see which tags are associated with which commit.

**Comment by xiaoyifang** [comment]
the hash not only used in tagname ,but also in application version.
It can save us the effort to run `git show-ref`

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/162566705-cb87b0d3-0be7-477c-be8a-9a6f5c7837d5.png)
