### ISSUE TITLE
macOS package doesn't work until you brew install ffmpeg nettle

### ISSUE THREAD

**Issue by ngn999** [xiaoyifang/goldendict#42]
I think there is a bug in `macdeployqt`, it can't deal with ffmpeg and nettle installed from homebrew.

there is a thread about it:

https://forum.qt.io/topic/86527/how-to-fix-path-in-third-party-libs-which-usage-another-third-party-libs-after-macdeployqt

I build a fixed version locally and had uploaded a new Apple Silicon version under #24 .

@NIXFOREVERNIX reported this bug under #24 , but he deleted the comment.

and after upgrading ffmpeg, my GoldenDict has broken too.

**Comment by xiaoyifang** [comment]
what about       `install_name_tool -change `  manually .

before macdeployqt has been merged into official.

**Comment by xiaoyifang** [comment]
https://www.geek-share.com/detail/2711912051.html

**Comment by ngn999** [comment]
yes, `install_name_tool` manually is a workaround.
maybe need some  hardcode  path.

**Comment by xiaoyifang** [comment]
IF this  is a problem ,can we put the `install_name_tool` command into the github action workflow. execute the install_name_tool command before `macdeployqt` ?
the path can be hard coded as they should not changed in the github container..

**Comment by ngn999** [comment]
we can get the path with `otool -L`, I'll file a PR after some test  this weakend.

**Comment by NIXFOREVERNIX** [comment]
I'm not use homebrew, I use [nix](https://nixos.org/download.html#nix-install-macos), So my dylib installed on /nix path, This my workaround:
```console
$ ls /usr/local/lib/
lrwxr-xr-x 78 root  7 Apr 17:31 libavcodec.59.dylib -> /nix/store/8pvqd2y1wvfwr7z37idlzyyjr2hk92da-ffmpeg-5.0/lib/libavcodec.59.dylib
lrwxr-xr-x 77 root  7 Apr 17:31 libavutil.57.dylib -> /nix/store/8pvqd2y1wvfwr7z37idlzyyjr2hk92da-ffmpeg-5.0/lib/libavutil.57.dylib
lrwxr-xr-x 78 root  7 Apr 17:31 libnettle.8.dylib -> /nix/store/kid59xrrhnirc8ib8dvvgclaizpk1lgq-nettle-3.7.3/lib/libnettle.8.dylib
lrwxr-xr-x 80 root  7 Apr 17:31 libswresample.4.dylib -> /nix/store/8pvqd2y1wvfwr7z37idlzyyjr2hk92da-ffmpeg-5.0/lib/libswresample.4.dylib
```

**Comment by NIXFOREVERNIX** [comment]
So this is a bug? I thought I had to fix it myself, so I deleted the message. :)

**Comment by xiaoyifang** [comment]
I got an idea(has not verified),
if symbol links has caused the issue.
what about remove the symbol links and copy the real file with the symbol name

**Comment by ngn999** [comment]
> I got an idea(has not verified), if symbol links has caused the issue. what about remove the symbol links and copy the real file with the same filename as symbol link
it should works. but it's another workaround. and needs to change homebrew.

I have add those change_install_name, but the github action interrupt at uploading stage:

https://github.com/ngn999/goldendict/actions/workflows/macos.yml

@xiaoyifang  can you have a look at it.

**Comment by xiaoyifang** [comment]
fixed
