### ISSUE TITLE
The scroll bar has jumping and width changes

### ISSUE THREAD

**Issue by EsuRt** [xiaoyifang/goldendict#420]
**Describe the bug**
在查询页面，用滚轮或鼠标移动滚动条，会出现跳动和滚动条长度变化的问题。

**To Reproduce**
1. 查询框输入单词
2. 滚动鼠标滚轮或点击鼠标移动

**Expected behavior**
希望能正常滚动。

**Screenshots**

https://user-images.githubusercontent.com/15177069/227716343-b1b6a605-a6bc-43ed-8dba-7b73604e7ddd.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 22621.1413
 - Browser: Brave
 - Version: Goldendict 23.02.07-alpha.230323.37673bb5

**Comment by xiaoyifang** [comment]
这其实是个特性，滚动条虽然有变动，但是左侧的内容滚动基本没收到影响。

滚动条变动的原因：   页面必须必须渲染完了，才能知道真实的高度，浏览器才能设置滚动条的大小，页面启用了一个新特性https://developer.mozilla.org/en-US/docs/Web/CSS/contain-intrinsic-size
在页面加载渲染的过程中，先用一个预估的高度计算。渲染的过程中，真实更新。这个造成了页面的计算高度随之变化。

**Comment by EsuRt** [comment]
> 

虽然影响不大，不知是否能优化下。

**Comment by xiaoyifang** [comment]
暂无计划

**Comment by darnn** [comment]
This is actually immensely distracting, and one of the reasons I don't use this new branch yet. GD++ has resolved this ages ago. I'm not sure how, but I think each page only loads within the results window once its final size is calculated. And there's an option to resize iframes in case there's an issue.

**Comment by xiaoyifang** [comment]
https://web.dev/content-visibility/

there is a video in the above page. pay attention to the scrollbar height in the video.
