### ISSUE TITLE
help needed, why clang-format not indent this line

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict#424]
**Describe the bug**
![image](https://user-images.githubusercontent.com/105986/227755889-9f0e064c-c5dc-4a7f-86c1-33b2c93ecee4.png)

**To Reproduce**
I have tried vs2022,clion ,both do not indent this line.

the following code  can also trigger this issue.
```
  if( true ) {

    for( int x = 0; x < 10; ++x ) {

      if( true ) {
      printf( "a" );
      }
    }
  }
```

@shenlebantongying  do you know the reason?

**Comment by shenlebantongying** [comment]
Solution 1:

`clang-format -style=llvm -dump-config > .clang-format` then readjust clang-format

Solution 2:

Reformat the entire `Class load(){}`, then the clang-format will work normally. (wtf :sweat_smile:)


---

The problem only exists when formatting part of the code in this file.

If you put the code in a new file, there is no problem. 

No idea why this file is so special.

(git can ignore formatting commits via `git config blame.ignoreRevsFile .git-blame-ignore-revs` See https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#navigate After decided to move files to subfolders, we should maybe redo the clang-format with complete settings like Solution 1 and run clang format to entire codebase?)
