### ISSUE TITLE
The position: fixed in the dictionary file is not supported

### ISSUE THREAD

**Issue by actforjason** [xiaoyifang/goldendict#431]
比如常用的牛津和朗文的切换工具位置不能固定了，会变得一直靠下或靠上。
QT5版的position: fixed显示正常，但比较模糊。

6.4.3-GoldenDict-v23.02.07-alpha-Installer.exe

**Comment by xiaoyifang** [comment]
应该是受到这个影响https://developer.mozilla.org/en-US/docs/Web/CSS/contain-intrinsic-size #420 
暂无计划修改
