### ISSUE TITLE
Dictionary content not displayed

### ISSUE THREAD

**Issue by epistularum** [xiaoyifang/goldendict#432]
I updated and goldendict is now unusable because it doesn't display the content of the dictionaries, only blank pages.
Dictionaries are properly loaded, I have performed several rescans. Add-on style is set to none.

![image](https://user-images.githubusercontent.com/34507493/228396161-5921dd9e-7953-4f35-a217-97b173f14d7c.png)
![image](https://user-images.githubusercontent.com/34507493/228396649-ed8669f4-8dc3-40cb-8652-2871d107d5e3.png)
[Screencast from 2023-03-29 09-30-25.webm](https://user-images.githubusercontent.com/34507493/228396313-e59e3899-b3ba-4b94-8b4f-9aedfe649a38.webm)

**Comment by xiaoyifang** [comment]
I pull back a possible problemic commit , try to update again.

**Comment by epistularum** [comment]
I have rebuilt goldendict and I can confirm that the issue has been solved!

**Comment by epistularum** [comment]
I have created a new dictionary group and tested dictionaries one by one. They all experience the same bug, single whitepage. They're all in the mdx format.

**Comment by xiaoyifang** [comment]
got it ,will investigate

**Comment by xiaoyifang** [comment]
@epistularum  can you verify this branch `feature/nonblock` again ,I have made some changes ,and play around with it in the Windows ,  seems ok.

the weird thing is that the previous version is also ok in Windows , maybe some platform difference involved also.

**Comment by xiaoyifang** [comment]
close for now

**Comment by xiaoyifang** [comment]
Do you mean that the word `症状` is not found in this dictionary 
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/5532790d-2e7c-4e4c-b648-ce361cdffd5f)

**Comment by xiaoyifang** [comment]
> Do you mean that the word `症状` is not found in this dictionary ![image](https://user-images.githubusercontent.com/105986/243349434-5532790d-2e7c-4e4c-b648-ce361cdffd5f.png)

Have you tried the original gd version?

**Comment by epistularum** [comment]
@xiaoyifang
I'm building the original GD from source in order to test. That being said, I had no issues with previous builds of GD-ng so something must have changed.

**Comment by xiaoyifang** [comment]
try search `*症状*` in the translate line .and tell me the result

**Comment by xiaoyifang** [comment]
@epistularum try this branch https://github.com/xiaoyifang/goldendict-ng/pull/820

**Comment by epistularum** [comment]
@xiaoyifang 
I have tried the branch but I have the same issue. The dicts are in mdx format perhaps this is useful information? I see that the edited file is called epwing_book.cc

I do not understand what is the translate line, is this correct?
![image](https://github.com/xiaoyifang/goldendict-ng/assets/34507493/b2358bab-ba82-491a-820e-78cc5dd7bca2)

**Comment by xiaoyifang** [comment]
can not find this dictionary ,can you share one with me?

epistularum ***@***.***> 于2023年6月5日周一 21:56写道：

**Comment by epistularum** [comment]
@xiaoyifang 
Sure:
https://mega.nz/folder/GM4TBAAS#GGJi-CMyJ3Y5e66dKt05eQ

**Comment by xiaoyifang** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/874c53e3-b5d0-4f8c-b967-a75a2f19d3ab)

Can not reproduce this issue.

**Comment by epistularum** [comment]
@xiaoyifang 
Since it works on your system I started to brainstorm what could be the issue. I figured it might be that the indexed dictionary data has somehow been corrupted. I delete the goldendict dict cache folder and it now works as expected. (.cache/goldendict)

Could it be possible that re-building and installing a new version of GD might have corrupted the index data?

**Comment by xiaoyifang** [comment]
the index data structure has not changed for a while.
