### ISSUE TITLE
[Feature Request] Option to Pronounce the Second Audio Source

### ISSUE THREAD

**Issue by ted1277** [xiaoyifang/goldendict#438]
I'm a new user of GD, finding it extremely good. Thank you for maintaining and fixing it!

By default, GD pronounces a word using its first audio source, which is the British pronunciation in most English dictionaries. Howerver, like many others, I usually use American pronunciation (the second audio source).

I'm not sure if adding an option to GD's settings to pronounce the second audio source is easy, but it would tremendously increase the usability of the tool.

**Comment by xiaoyifang** [comment]
not in plan.
