### ISSUE TITLE
Looking for complete list of supported dictionary formats

### ISSUE THREAD

**Issue by michaelbeijer** [xiaoyifang/goldendict#442]
Hi there!

Where can I find a **complete list of supported dictionary formats**? I'm currently testing the various forks of GoldenDict available, in the hope of finding one that supports **tab-delimited text files** as a dictionary format, since this is the format I store and manage my large terminology collection during my work as a technical translator & terminologist.

Michael

**Comment by xiaoyifang** [comment]
> Where can I find a **complete list of supported dictionary formats**?

https://xiaoyifang.github.io/goldendict/formats.html



> **tab-delimited text files** as a dictionary format

what's detail of this dictionary format

**Comment by michaelbeijer** [comment]
Hi xiaoyifang,

Thanks for the link!

I keep my glossaries in UTF-8 text tiles, with extension .tsv, with the data as follows:

> **Dutch**[tab]**English**[tab]**Notes**[tab]**Source**[tab]**URL**

---

Incidentally, of the various forks I have been looking at as adopting for my work, I think yours is the best. 

The original (https://github.com/goldendict/goldendict) seems very slow to release Windows binaries. The latest they have are from 2019! Also, new user registration is apparently also permanently disabled for their user forum (http://goldendict.org/forum/). Plus their website (goldendict.org) is strangely outdated.

The other main fork, by nonwill (https://github.com/nonwill/GoldenDict-OCR), looks very interesting, but is very hard to understand as it's mainly in Chinese, plus the files are not hosted on GitHub, but on some Chinese website I can't figure out. I wouldn't feel comfortable using a program as my main terminology app (and recommending it to fellow translators) if I need to use Google Translate just to figure out where to download it.
