### ISSUE TITLE
Hope to add support for win on arm

### ISSUE THREAD

**Issue by LatencyHearn** [xiaoyifang/goldendict#444]
希望能够增加对huawei matebook e go以及surface pro x/9 这样的 windows on arm设备的支持，编译一份arm64的exe

**Comment by xiaoyifang** [comment]
目前的自动编译，依赖github提供的action hoster.貌似没有你的这种系统。

目前编译都比较简单，你可以自己试着编译一下。

**Comment by xiaoyifang** [comment]
not in plan

**Comment by kekeqwq** [comment]
唉现有的版本可以运行但是查词的时候太卡了
