### ISSUE TITLE
Capture2text does not open popup window

### ISSUE THREAD

**Issue by BEST8OY** [xiaoyifang/goldendict#448]
**Describe the bug**
Capture2text does not open popup window.

**To Reproduce**
Try capturing a word with Capture2text. 

**Expected behavior**
It should open popup window but it does not anymore.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
It was okay with previous official release.

**Comment by xiaoyifang** [comment]
how do you configure the capature2text? do you enable scanpopup in gd

**Comment by xiaoyifang** [comment]
I got your idea,  
and the scanpopup should not enabled,they are different function.

Will check later

**Comment by xiaoyifang** [comment]
@shenlebantongying can you help to check this,seems has some relation with recent scanpopup changes

**Comment by shenlebantongying** [comment]
I cannot reproduce anything. Yestarday's version works fine on windows. The scanning is not enabled.

https://user-images.githubusercontent.com/20123683/229656880-517823f6-36cf-4785-bb08-9e839d7a209f.mp4

**Comment by BEST8OY** [comment]
> I cannot reproduce the problem. Yestarday's version works fine on windows. The scanning is not enabled.

Okay.
Problem was on my part.
I extracted the GD in my installation place and it's working again.
I'm not sure what happened there.
I'm truly sorry for my mistake. 🥲
