### ISSUE TITLE
in libao code, dlopen is used to load some plugins

### ISSUE THREAD

**Issue by ngn999** [xiaoyifang/goldendict#46]
but the path is hardcode here:  https://github.com/xiph/libao/blob/master/src/audio_out.c#L298
and `macdeployqt` can't handle dependencies like this.

the original maclibs/libao.dylib looks like has some hack:

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/284726/163343188-f64f3583-c4a2-4f97-9a21-8a90451b1e19.png">

I'm looking for a solution.

EDIT: 
the patch version is here: 

https://github.com/timonwong/libao/commits/goldendict

https://github.com/goldendict/goldendict/blob/b2e673961d28ca5eb920a909091252d3321f09d6/maclibs/scripts/libao.txt

**Comment by ngn999** [comment]
I think this is a more stable solution: https://github.com/xiph/libao/issues/10

**Comment by xiaoyifang** [comment]
should the plugins be disabled?
is the plugin neccessary for the play sound method.

**Comment by ngn999** [comment]
someone has build alsa as build-in: https://github.com/Tslabdev/tslab_libao_library/commits/master
I can build  macos.so as build-in.

**Comment by ngn999** [comment]
QWebEngine contains a chromium, but it can't play audio without libao+ffmpeg?

**Comment by xiaoyifang** [comment]
as far as I know ,chromium can not play speex format.

if libao+ffmpeg does not work ,try to chagne the audio play engine to qtmultimedia and have a try.
