### ISSUE TITLE
Dictionary groups became blank

### ISSUE THREAD

**Issue by v-fox** [xiaoyifang/goldendict#47]
I've recently made fresh package from dev branch and all dictionary groups became blank even though they are correctly listed in ~/.goldendict/config They still listed in "All" group but custom groups are ignored.

Maybe this has to do with these changes ?:
c664ac315cb4bffe8bdd4b81713a0a5f74b98847
0560785a659cf2c9ac0f6f5bb93c96be56495743
687cd26c3af6ee108d9b36160957159e9b404d0b

**Comment by xiaoyifang** [comment]
provide a screenshot plz.I'll look into it.
the dev branch has been used for a while .
this issue has not been reported before.

**Comment by v-fox** [comment]
> provide a screenshot plz.I'll look into it. the dev branch has been used for a while . this issue has not been reported before.

Screenshot of what ? An empty windows to see that it's empty ?
And I've been using goldendict for years with this config and the issue has not been seen by you. So I reporting it now. 20220210T153832.5e8be7d9 was previously known good commit.

![goldendict](https://user-images.githubusercontent.com/362763/163425147-01bf8676-494f-4cc3-a352-52b064f6ff62.jpg)

**Comment by xiaoyifang** [comment]
![Uploading image.png…]()
only part of the group dictionaries has been displayed.  is this what you really mean?

**Comment by xiaoyifang** [comment]
following is my guess:
the dictionary's id has somehow changed ,and can not matched with dictionary id in config file.

**Comment by v-fox** [comment]
> only part of the group dictionaries has been displayed. is this what you really mean?

Well, "part" is an understatement for 3 out of like 50.

> following is my guess: the dictionary's id has somehow changed ,and can not matched with dictionary id in config file.
> 
> steps to try： pick one dictionary which is not show，search by dicionary name in config file。 if found other item，compare the dictionaryid

I tried re-adding "Babylon Russian-English" and, indeed, it has different id: old one is c98d7fd49952e93e54459701a651779c and new one is b99b8e6421fda21203d296e0eb4e6cd1. Adding it also nuked whole list. Luckily, I made backup. It seems that changes to that code changed id generation logic.

**Comment by xiaoyifang** [comment]
in your config file ,  checkout the same dictionary'id under `dictionaryOrder.dictionary`  and `groups.group.dictionary`
![image](https://user-images.githubusercontent.com/105986/163504056-200a17d8-81c8-498e-8bef-9bf0701027cd.png)

this is the reason:in the very beginning ,goldendict match the dictionary by dictionary name.
![image](https://user-images.githubusercontent.com/105986/163504460-0b3b8943-a8c1-48cc-b880-7c46a5272add.png)

but match by name will pose other problem,so I removed the logic.

**Comment by v-fox** [comment]
> in your config file , checkout the same dictionary'id under `dictionaryOrder.dictionary` and `groups.group.dictionary`

ids and names are the same in dictionaryOrder and group.

> dictionary id logic has not changed. the match logic has changed

I just told you that re-adding generates different id number.

> but match by name will pose other problem,so I removed the logic.

If you're going to change id generation and there is name fallback then i's up to you to automatically convert old id format to new one by matching names and re-writing config without loses

> there are two solutions:
> 1,Change your config file manually.
> your config file should already contain the correct dictionary id , changed the dictionary id under groups.group.dictionary to the same id as dictionaryOrder.dictionary(if the above has been confirmed)

ids are already matching but both lists have old ids. As I've already said, re-adding a single one deletes entire group.

> 2,rearrange your dictionary group.
> there is no need to add them again, drag from the all dictionary panel to your group

If I drag all then it just be same list of all. What is this phrase even supposed to mean: "don't re-add, just re-add" ?
Redoing more than 10 lists of more than 50 dictionaries is a major hustle. It's up to you to make such changes without breaking compatibility.

**Comment by xiaoyifang** [comment]
have not intended to keep this compatibility.  I'll gradually remove some old code and features from the codebase.

> If you're going to change id generation

id generation has not changed.
