### ISSUE TITLE
history panel and favorite panel do not respond to arrow up/down keys.

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict#470]
> 1, In the history panel, the up and down keys of the keyboard cannot be used;
> 

_Originally posted by @github-actions[bot] in https://github.com/xiaoyifang/goldendict/issues/464#issuecomment-1501600936_

**Comment by shenlebantongying** [comment]
The true cause is this line:

https://github.com/xiaoyifang/goldendict/blob/ddb9655938eb24d71864a0ba4088970de7e17aec/src/ui/articleview.cpp#L555-L557

Right after load finished, the focus on QListWidget is moved to ArticleView, thus shortcut (up/down) no longer works.

Removing this line will solve the problem, but I don't know why this line exist and the consequences of removing it.

**Comment by xiaoyifang** [comment]
> The true cause is this line:
> 
> https://github.com/xiaoyifang/goldendict/blob/ddb9655938eb24d71864a0ba4088970de7e17aec/src/ui/articleview.cpp#L555-L557
> 
> Right after load finished, the focus is moved from QListWidget to ArticleView, thus shortcut (up/down) no longer works.
> 
> Removing this line will solve the problem, but I don't know why this line exist and the consequences of removing it -> [52f11d4](https://github.com/xiaoyifang/goldendict/commit/52f11d4a4652909d76857f89d8a48c4d444ce50f)

As far as I can remember ,   someone has reported that when finished the search ,  they can use page up/down to scroll the article.
