### ISSUE TITLE
Use the builtin chromium engine to play sound as an extra option

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict#49]
there is a period of time ,I have used chromium engine to play sound .
https://github.com/xiaoyifang/goldendict/commit/096f21f61a7a135723e467ac6097a89703f8307a

maybe we can add built-in chromium engine as a third option for user to choose.
![image](https://user-images.githubusercontent.com/105986/163505593-56762276-3c80-42b4-bad1-53fccb1da2cd.png)

_Originally posted by @xiaoyifang in https://github.com/xiaoyifang/goldendict/issues/46#issuecomment-1099717541_

**Comment by 1over137** [comment]
You might as well remove the other methods, since Chromium can play all the common codecs.
https://www.chromium.org/audio-video/
This should help reduce the complexity of the program for future maintainability.

**Comment by xiaoyifang** [comment]
as far as I can know ,does not support speex.

**Comment by GPLv3-fan** [comment]
**Just two comments:**
1) Many Linux users use only Firefox and they do not have installed Chromium. Specially in old machines where space is an issue people choose the "default" browser on Linux and never install Chromium.

2).spx format is very important (although the .opus format is its successor).

.spx format is good for human voices. Many .mdx dictionaries include sounds in .spx  format. _Therefore, support for .xps format is really necessary._ If Chromium cannot provide .spx support, then it should not be the only option for users.

**Comment by 1over137** [comment]
What is playing the speex files in the current version? Is it Qt or ffmpeg?
How do you use ffmpeg on windows?

**Comment by GPLv3-fan** [comment]
On Manjaro I can only play speex files with QT:

![image](https://user-images.githubusercontent.com/58692066/163720596-dbea2170-3686-466e-a2f7-e9f2f5473451.png)

ffmpeg+libao does not work with speex files (I have all the dependencies installed)

![image](https://user-images.githubusercontent.com/58692066/163720580-ae544da4-c2c3-44ee-960a-11d78d74c7a5.png)

_> How do you use ffmpeg on windows?  No idea. I do not even install Windows in a VM because of their data collection_ : 
https://en.wikipedia.org/wiki/Surveillance_capitalism

**Comment by xiaoyifang** [comment]
> How do you use ffmpeg on windows?

windows version has a bundled version of precompiled ffmpeg  libraries under `winlibs/msvc`

**Comment by xiaoyifang** [comment]
> ffmpeg+libao does not work with speex files (I have all the dependencies installed)

how do you install the  ffmpeg ? speex is a feature ,if you build from source ,you have to enable the speex  feature.
If you uses the system's prebuilt package, you can check you ffmpeg's build option to find out whether the speex has been enabled.
