### ISSUE TITLE
screen capture can not work.

### ISSUE THREAD

**Issue by haoisli9** [xiaoyifang/goldendict#50]
I use goldendict 6.2.4-GoldenDict-staged.9ce48c16-102528 in win10, but screen capture can not work. do I miss something?

**Comment by xiaoyifang** [comment]
no that's expected.If you mean the mouseover function ,I remove this function .
check this.
https://github.com/xiaoyifang/goldendict/blob/staged/howto/How%20to%20use%20ocr%20together%20with%20GoldenDict.md
