### ISSUE TITLE
qt5 appimage in debian 11 can not work with fcitx5

### ISSUE THREAD

**Issue by dwdcth** [xiaoyifang/goldendict#58]
最新git release 版qt5 解压appimage后,发现 usr/plugins/platforminputcontexts/ 目录没有打包libfcitx5platforminputcontextplugin.so

复制系统的/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so 可以正常输入,希望打包的时候,能加入

**Comment by xiaoyifang** [comment]
目前建议先从源码编译。

appimage貌似总会遇到各种缺少的so文件。

**Comment by xiaoyifang** [comment]
maybe generate a deb executable in the future

**Comment by susanooxyz** [comment]
> 目前建议先从源码编译。

从源码编译的话如何添加fcitx5的相关依赖呢？之前在archlinux中下载了aur中打包的goldendict-webengine-git，但是好像不支持fcitx5，只能输入英文，不能输入其他语言文字，打开关闭输入法也没有反应。

**Comment by xiaoyifang** [comment]
https://marketplace.qt.io/products/fcitx5-qt

**Comment by CyrusYip** [comment]
在 KDE Plasma 6 Wayland 用 Flatpak 版的 GoldenDict-ng 24.01.22，一样是用不了 Fcitx5。参照 [Fcitx5 - ArchWiki](https://wiki.archlinux.org/title/Fcitx5#IM_modules) 使用 `QT_IM_MODULE=fcitx` 就行了。这是我修改过的 `.desktop` 文件。

```
[Desktop Entry]
Type=Application
Terminal=false
Categories=Office;Dictionary;Education;Qt;
Name=GoldenDict (support Fcitx5)
GenericName=Multiformat Dictionary
Comment=A feature-rich dictionary lookup program
Icon=goldendict
Exec=env QT_IM_MODULE=fcitx goldendict %u
MimeType=x-scheme-handler/goldendict;x-scheme-handler/dict;
```
