### ISSUE TITLE
can not search word by google translate

### ISSUE THREAD

**Issue by haoisli9** [xiaoyifang/goldendict#59]
I config google translate address like: https://translate.google.cn/m?sl=en&tl=zh-CN&hl=zh-CN&q=%GDWORD%, but it can not translate. I put this address in edge browser, it can work correct. Do I miss something?
Thanks.

**Comment by darnn** [comment]
Try this:
https://github.com/xinebf/google-translate-for-goldendict

**Comment by haoisli9** [comment]
It works, thank you.
But, do you mean that the web translate can not be used in this version?
and how can I use other dictionary web address like baidu translate or
youdao translate?

Thanks again.

-- 
sent from Emacs+Gnus

**Comment by darnn** [comment]
Google Translate specifically can't be used without a plugin, as far as I know. Other websites should work, but I can't test it myself since this fork doesn't load any websites at all for me (but I suspect it might just be something specific to me).

**Comment by xiaoyifang** [comment]
seems can not handle urls which contain hashtag #

**Comment by haoisli9** [comment]
Is it an issue? and will it be fixed?

Thanks.



***@***.***
 
From: xiaoyifang
Date: 2022-05-05 21:42
To: xiaoyifang/goldendict
CC: haoisli9; Author
Subject: Re: [xiaoyifang/goldendict] can not search word by google translate (Issue #59)
seems can not handle urls which contain hashtag #
―

**Comment by xiaoyifang** [comment]
check this https://github.com/NinthCode/GoldenDict

**Comment by haoisli9** [comment]
不好使啊，谷歌的那个，查询报错说ttk设置错误，百度翻译倒是没有报错，但是并没有信息返回；Appid和AppKey都已经申请了，看起来也没有问题；
这个包已经很老了，是不是接口都已经变化了啊；

我是直接下载的jar包，这个应该不需要重新编译吧？

谢谢；



***@***.***
 
From: xiaoyifang
Date: 2022-05-09 23:12
To: xiaoyifang/goldendict
CC: haoisli9; Author
Subject: Re: [xiaoyifang/goldendict] can not search word by google translate (Issue #59)
check this https://github.com/NinthCode/GoldenDict

**Comment by xiaoyifang** [comment]
maybe the transaltion api wrapper is a little outduted ,wish someone can perfect it？
