### ISSUE TITLE
Upload build artifacts in Actions

### ISSUE THREAD

**Issue by cg31** [xiaoyifang/goldendict#60]
It will be very useful to package all the binary files (artifacts) and upload it to github, like qBittorrent:
https://github.com/qbittorrent/qBittorrent/blob/master/.github/workflows/ci_windows.yaml#L156

then people can download a package of a build.

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/releases
package can be download here

**Comment by cg31** [comment]
Yes, I knew the release downlaod.

But uploading build artifacts in actions will keep track of every commit.

**Comment by xiaoyifang** [comment]
for simplicity，i just remove the artifacts

**Comment by cg31** [comment]
It doesn't matter you removed old artifacts.

It is about future. If you add an upload-action, people can try the result from a new change, in future.

**Comment by xiaoyifang** [comment]
not in plan
