### ISSUE TITLE
script-extension Using Powershell

### ISSUE THREAD

**Issue by Sertoli2022** [xiaoyifang/goldendict#63]
Hello xiaoyifang. Thank you very much for your excellent work.
I need your help: What is the shortcut command in Powershell for Goldendict popup?
What is the script to enable Goldendict popup?
I need create a script-extension Using Powershell program code.
I'm trying to make a plugin for Goldendict on Pantherbar (Snipdo.)
See below: 
https://snipdo-app.com/

**Comment by xiaoyifang** [comment]
invoke the command directly`goldendict.exe “word”`
