### ISSUE TITLE
[Bug] Full-text search does not work on latest alpha

### ISSUE THREAD

**Issue by GPLv3-fan** [xiaoyifang/goldendict#69]
Full-text search crashes the application.
OS:  Manjaro Linux (the latest stable)
GoldenDict Version: 22.4.24-alpha.bde86d7b  (the latest alpha from May 18, 2022)

After writing the “term” and clicking “Search” all the results appear in a list but if I click any result to see it GoldenDict crashes.

 I reproduced the issue with .dsl and .mdx files:

**Comment by xiaoyifang** [comment]
confirmed
