### ISSUE TITLE
屏幕取词

### ISSUE THREAD

**Issue by xiaobinchen** [xiaoyifang/goldendict#70]
屏幕取词功能不能生效

**Comment by xiaoyifang** [comment]
the original ocr mode is not cross platform and has problem built on win64 .I remove it and  replaced with this solution.
check  this
https://github.com/xiaoyifang/goldendict/blob/staged/howto/How%20to%20use%20ocr%20together%20with%20GoldenDict.md

or use community solutions called [GoldenDictOCR] and [GdOcrTool]

**Comment by xiaobinchen** [comment]
thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月20日(星期五) 上午7:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaoyifang/goldendict] 屏幕取词 (Issue #70)





 
the original ocr mode is not cross platform and has problem built on win64 .I remove it and  replaced with this solution.
 check  this
 https://github.com/xiaoyifang/goldendict/blob/staged/howto/How%20to%20use%20ocr%20together%20with%20GoldenDict.md
 
or use community solutions called [GoldenDictOCR] and [GdOcrTool]
