### ISSUE TITLE
[Bug] Audios cannot be saved 

### ISSUE THREAD

**Issue by GPLv3-fan** [xiaoyifang/goldendict#72]
The latest commits (last 24 hours or so) introduced the following bugs:

**1)  Audios from Dictionaries cannot be saved in the PC. Steps to reproduce:**

Choose any pronunciation dictionary (.mdx, dsl or “Sound Library”) and try to **“Save Sound”** in the computer. 

![grafik](https://user-images.githubusercontent.com/58692066/169671142-87d9f530-c37f-4c9c-88c9-680011efe762.png)

After click "Save Sound" the audio is not downloaded. The window that allows to choose a folder to download the audio does not appear. Instead, this appears:

![grafik](https://user-images.githubusercontent.com/58692066/169671172-8eb2cc1a-04cf-4f07-bc41-10b82f48bbfb.png)

**2) Images cannot be saved in the computer. Same bug as above, but with dictionary images.**

**Comment by GPLv3-fan** [comment]
On Manjaro there is also a problem of random crashes being more often than before May 21.  It seems to be a regression introduced by the Commits of May 21, 2022.  

I am trying to pinpoint what is causing the crashes, but I do not find any specific reason or cause. If I find a specific relation between settings and crashes, I will write again.

_PS. I am using the latest alpha of GoldenDict, updated once daily from AUR._

**Comment by xiaoyifang** [comment]
> 1) Audios from Dictionaries cannot be saved in the PC. Steps to reproduce:

confirmed

**Comment by xiaoyifang** [comment]
> > 1. Audios from Dictionaries cannot be saved in the PC. Steps to reproduce:
> 
> confirmed

fixed.
