### ISSUE TITLE
[Bug] Cannot print to PDF

### ISSUE THREAD

**Issue by GPLv3-fan** [xiaoyifang/goldendict#73]
**Query results cannot be printed into PDF.**

There is a PDF file that is produced but is corrupted. PDF readers cannot open it.

OS: Manjaro KDE
Version: latest from AUR

**Comment by xiaoyifang** [comment]
can you print normal html webpage to pdf?

**Comment by GPLv3-fan** [comment]
> can you print normal html webpage to pdf using web browser?

Yes, I can print normal HTML webpage to PDF using Firefox and Chromium.

Firefox:
![grafik](https://user-images.githubusercontent.com/58692066/169924256-b80c6bd5-1732-42da-885f-e9bda06751b0.png)

Chromium:
![grafik](https://user-images.githubusercontent.com/58692066/169924443-ce403e83-9e60-429a-b5c1-053706eaa8bf.png)

The problem is with GoldenDict only. It can save as .html but cannot print as PDF because the file produced is corrupt:

![grafik](https://user-images.githubusercontent.com/58692066/169924502-1957424d-d7d9-4a25-b535-44326e98a39c.png)

**Comment by GPLv3-fan** [comment]
I just found that "Evince PDF" can open PDF documents produced by GoldenDict but Okular cannot.

So, I guess that it might be a bug with Okular. Sorry. I will report the issue to them...
