### ISSUE TITLE
[Feature Request] Add "Exact Match" function on Search (Ctrl + F)

### ISSUE THREAD

**Issue by GPLv3-fan** [xiaoyifang/goldendict#79]
Problem: The German Wiktionary has many inflections for verbs, nouns and adjectives. Verbs have very large tables with all the inflections. 

If a user tries to look an inflected verb (e.g. "flohen") GoldenDict highlights many results that include the word "flohen" but are not exact matches. For example:

![grafik](https://user-images.githubusercontent.com/58692066/170805609-9c705c4a-a3a4-40e9-a301-3258033683dc.png)

The problem is that on a simple search, there is no function to perform an exact match. That is only available on "Full Text Search" but that option is not suitable because a full text search on Wiktionary would take a huge amount of time (i.e. > 5 -10 minutes).

That problem affects highly inflected languages as German and all Romance languages (Spanish, French, etc). Slavic languages are also severely affected. 

**Could it be possible to Add  "Exact Match" function on Search (Ctrl + F) ?**

**Comment by xiaoyifang** [comment]
seems not an easy way to achieve this

**Comment by xiaoyifang** [comment]
this behaviour is supported by ::FindText ,  while webkit support exactmatch ,webengine does not support it .

a workaround:
search " flohen"  with a leading space .

**Comment by xiaoyifang** [comment]
seems  `fulltext match ` is a solution.

**Comment by xiaoyifang** [comment]
`void ArticleView::highlightFTSResults()` 
wish someone can implement this.
