### ISSUE TITLE
i cant use fcitx within goldendict-ng

### ISSUE THREAD

**Issue by darkralts** [xiaoyifang/goldendict#795]
**Describe the bug**
fcitx usually works in all my qt and gtk programs, but i think because goldendict-ng is using qt6, that its ignoring all of my set variables, being 
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export QT_QPA_PLATFORMTHEME=gtk2

**To Reproduce**
1. open goldendict
2. try to switch to mozc with the fcitx keybind
3. see it not switch to japanese
**Affected Dictionaries**
n/a
If certain dictionaries don't work, list their names and types.

If possible, please attach the dictionary files or provide a downloadable link. (GitHub allows uploading 25MiB zip file as attachment)

**Expected behavior**
i expected fcitx to work within goldendict, but i think its because of qt6, which i dont think supports fictx.
i have downloaded all of the necesarry fcitx qt6 packages though (void linux)
**Screenshots**
(i dont think screenshots would help, it would just be a screenshot of the goldendict search part)
![image](https://github.com/xiaoyifang/goldendict-ng/assets/16366107/9964fb16-c95e-4f8f-80e4-36076d1d92fb)
![image](https://github.com/xiaoyifang/goldendict-ng/assets/16366107/b85d92fe-a2b2-4836-aad8-337b981d6db0)
other qt apps look like this and are able to use mozc

**OS and software versions**

Copy & paste `help` -> `about` -> `Copy version info` to here

- OS: void linux
- latest rolling as of posting

**Additional context**

i think it may be because qt6, if anyone has any idea how to get it to work with qt6, please let me know. i dont know if this is goldendict specific or not, but i hope someone here can help me out

alternatively, if you do have qt5 appimages i can download (the ubuntu ones didnt work as im on void linux), i would love to try those. 

thank you

**Comment by darkralts** [comment]
i have tried building manually, but it is just too complicated for me to figure out

**Comment by shenlebantongying** [comment]
The problem is that fcitx's module is not included.

We have to bundle one of:
* https://packages.ubuntu.com/kinetic/fcitx-frontend-qt5
* https://packages.ubuntu.com/kinetic/fcitx-frontend-qt6

**Comment by shenlebantongying** [comment]
I think just install one of the packages, then it will be automatically included:
https://github.com/probonopd/linuxdeployqt/blob/8428c59318b250058e6cf93353e2871072bbf7f9/tools/linuxdeployqt/shared.cpp#L1379-L1381

**Comment by shenlebantongying** [comment]
https://github.com/void-linux/void-packages/pull/44234

**Comment by darkralts** [comment]
thank you, i absolutely agree! void should add goldendict-ng as a replacement for the now defunct goldendict

**Comment by darkralts** [comment]
👍 i can try building it with the srcpkg :D thank you for everything you've
done

**Comment by darkralts** [comment]
weird, i have no idea why but it still doesnt work with the latest appimages, i tried compiling with the srcpkg that was made, it goes well until here


```
=> libarchive-3.6.2_2: installing host dependencies: pkgconf-1.9.3_1 ...
=> libarchive-3.6.2_2: installing target dependencies: zlib-devel-1.2.13_1 bzip2-devel-1.0.8_2 liblzma-devel-5.4.3_1 acl-devel-2.3.1_1 libzstd-devel-1.5.5_1 liblz4-devel-1.9.4_1 openssl-devel-1.1.1t_1 ...
=> libarchive-3.6.2_2: running pre-build hook: 02-script-wrapper ...
=> libarchive-3.6.2_2: running do_build ...
make  all-am
make[1]: Entering directory '/builddir/libarchive-3.6.2'
  CCLD     libarchive.la
/usr/bin/ld: /usr/lib64/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../lib64/libz.a(zutil.o): warning: relocation against `z_errmsg' in read-only section `.text'
/usr/bin/ld: /usr/lib64/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../lib64/libz.a(deflate.o): relocation R_X86_64_PC32 against symbol `z_errmsg' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:4372: libarchive.la] Error 1
make[1]: Leaving directory '/builddir/libarchive-3.6.2'
make: *** [Makefile:3877: all] Error 2
=> ERROR: libarchive-3.6.2_2: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 2
=> ERROR:   in do_build() at common/build-style/gnu-configure.sh:15
[ichigo@gensokyo ~/ダウンロード/void-packages-master]$ 

```

**Comment by darkralts** [comment]
and for some reason goldendict ignores all of my qt arguments, regardless of if its 5 or 6, i think something else might be going on here i have no idea, but i need fcitx to work with it or something

**Comment by jycyouyas** [comment]
> and for some reason goldendict ignores all of my qt arguments, regardless of if its 5 or 6, i think something else might be going on here i have no idea, but i need fcitx to work with it or something

i think i get the same problem on fedora 41 kde，l can't input chinese on goldendict. have you get a solution? if so ,please tell me ,thank you!
