### ISSUE TITLE
[Feature Request] Adding a "Bookmark" feature 

### ISSUE THREAD

**Issue by GPLv3-fan** [xiaoyifang/goldendict#81]
**Background:** GoldenDict can be used as an e-book reader. For example, all the books from the [Project Gutenberg ](https://www.gutenberg.org/)are available in [.zim format](https://wiki.kiwix.org/wiki/Content_in_all_languages), and they can be read within GoldenDict. It is convenient to use GoldenDict both as an e-book reader and dictionary at the same time. 

**Problem:** While reading books on GoldenDict, the software does not remember the position of the latest paragraph read by users. Hence, it is necessary to open the book again and look manually the latest paragraph. It is both time-consuming and discouraging.

**Possible Solution:** Adding a Bookmark feature to GoldenDict. That function might allow selecting text and _“bookmark”_ the exact sentence that the user is reading and store that into a Bookmarks section.

 In such a way, users can close GD and quickly continue reading a book or Wikipedia Article exactly where they left off.

_Screenshot:_
![grafik](https://user-images.githubusercontent.com/58692066/171016119-583c290e-3e38-4d8f-a12d-111192b62330.png)

**Comment by xiaoyifang** [comment]
reuse favorite panel to achieve this.

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/171783470-4946cf72-721e-4099-ad8a-a58ac118b6b7.png)
