### ISSUE TITLE
add export words history command in cli 

### ISSUE THREAD

**Issue by bre01** [xiaoyifang/goldendict#858]
**Is your feature request related to a problem? Please describe.**

not related

**Describe the solution you'd like**

add cli command to export words history to txt file, so it can be run as scheduled using tool like cron and then using some tool like git or rsync to sync the history with other devices 

**Additional context**
<img width="341" alt="image" src="https://github.com/xiaoyifang/goldendict-ng/assets/64588494/c246a4ae-cd20-4c39-9846-32d11d27bb2f">

**Comment by shenlebantongying** [comment]
Just

```bash
cat ~/.local/share/goldendict/history | cut -c 3-
```

**Comment by bre01** [comment]
thank you very much  
btw it's in the ~/.goldendict/history on OSX. 



> Just
> 
> ```shell
> cat ~/.local/share/goldendict/history | cut -c 3-
> ```
