### ISSUE TITLE
Slow display of content when using certain dictionaries

### ISSUE THREAD

**Issue by blucca** [xiaoyifang/goldendict#966]
**Describe the bug**

When using 「Weblio類語辞典」 to search for words, the speed of displaying content is significantly slower than the original version of GoldenDict.

**Test video**

https://github.com/xiaoyifang/goldendict-ng/assets/127029904/7099e630-3ed6-452f-93ac-893bec922eff

**Affected Dictionaries**

[Weblio類語辞典](https://mdx.mdict.org/Recommend/Weblio%E9%A1%9E%E8%AA%9E%E8%BE%9E%E5%85%B8.zip)

**Software versions**

GoldenDict-ng version [23.06.02-alpha.230713.224d3278](https://github.com/xiaoyifang/goldendict-ng/releases/tag/valpha.224d3278)
GoldenDict version [1.5.0](https://github.com/goldendict/goldendict/releases/tag/1.5.0)

**Comment by xiaoyifang** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/9ca54e1a-d32f-488d-b1a2-8254480d3ab1)

有个css文件比较大，占了0.6s时间。
qwebengine有个问题，就是浏览器缓存有问题。等到了qt6.6才能支持,  到时候这个问题应该就好了。

**Comment by xiaoyifang** [comment]
用这个样式替换你词典文件夹中   thesaurus.css的内容。简单处理的。
```
td,
th {
    border: 1px solid #ddd;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: #f2f2f2;
}

tr:hover {
    background-color: #ddd;
}

th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: #c2ceca;
    color: white;
}
```

效果
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/6610e857-14ed-4094-8203-4b705206acba)

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/releases/tag/tag-alpha.dbb1f300

可以用这里的版本先试一下。
